const copy = {
  es: {
    title: 'Mejora tu anuncio',
    hardTitle: 'Corrige esto antes de continuar',
    warningIntro: 'Detectamos detalles que pueden reducir la calidad del anuncio.',
    hardIntro: 'Estos puntos deben corregirse antes de publicar.',
    continueAnyway: 'Continuar de todos modos',
    checkAgain: 'Revisar de nuevo',
    checking: 'Revisando calidad...',
    previewUnavailable: 'No pudimos revisar la calidad ahora. Puedes continuar; la validación final seguirá activa al publicar.',
    unknown: 'Revisa este detalle antes de continuar.',
    codes: {
      title_too_short: 'Haz el título un poco más descriptivo.',
      description_too_short: 'Añade más detalles útiles en la descripción.',
      title_placeholder: 'Sustituye el texto provisional del título por un título real.',
      description_placeholder: 'Sustituye el texto provisional de la descripción por información útil.',
      price_zero: 'Revisa el precio; parece ser cero.',
      photo_recommended: 'Añade al menos una foto útil del artículo cuando sea posible.',
      contact_data_in_copy: 'Quita teléfonos, correos o enlaces del título y la descripción; usa los campos de contacto.',
      keyword_stuffing: 'Reduce palabras repetidas o listas de palabras clave.',
      title_description_duplicate: 'Evita repetir el título como descripción.',
      incomplete_preview_payload: 'Completa los campos obligatorios antes de revisar la calidad.',
    },
  },
  en: {
    title: 'Improve your listing',
    hardTitle: 'Fix this before continuing',
    warningIntro: 'We found details that may reduce listing quality.',
    hardIntro: 'These items must be fixed before publishing.',
    continueAnyway: 'Continue anyway',
    checkAgain: 'Check again',
    checking: 'Checking quality...',
    previewUnavailable: 'We could not check quality right now. You can continue; final validation will still run when you publish.',
    unknown: 'Review this detail before continuing.',
    codes: {
      title_too_short: 'Make the title a little more descriptive.',
      description_too_short: 'Add more useful details to the description.',
      title_placeholder: 'Replace the placeholder title with a real title.',
      description_placeholder: 'Replace the placeholder description with useful information.',
      price_zero: 'Check the price; it appears to be zero.',
      photo_recommended: 'Add at least one useful photo when possible.',
      contact_data_in_copy: 'Remove phone numbers, email addresses or links from the title and description; use the contact fields.',
      keyword_stuffing: 'Reduce repeated words or keyword lists.',
      title_description_duplicate: 'Avoid repeating the title as the description.',
      incomplete_preview_payload: 'Complete the required fields before checking quality.',
    },
  },
  pt: {
    title: 'Melhore seu anúncio',
    hardTitle: 'Corrija isto antes de continuar',
    warningIntro: 'Encontramos detalhes que podem reduzir a qualidade do anúncio.',
    hardIntro: 'Estes pontos devem ser corrigidos antes da publicação.',
    continueAnyway: 'Continuar mesmo assim',
    checkAgain: 'Verificar novamente',
    checking: 'Verificando qualidade...',
    previewUnavailable: 'Não foi possível verificar a qualidade agora. Você pode continuar; a validação final continuará ativa ao publicar.',
    unknown: 'Revise este detalhe antes de continuar.',
    codes: {
      title_too_short: 'Deixe o título um pouco mais descritivo.',
      description_too_short: 'Adicione mais detalhes úteis à descrição.',
      title_placeholder: 'Substitua o título provisório por um título real.',
      description_placeholder: 'Substitua a descrição provisória por informações úteis.',
      price_zero: 'Revise o preço; ele parece estar zerado.',
      photo_recommended: 'Adicione pelo menos uma foto útil quando possível.',
      contact_data_in_copy: 'Remova telefones, e-mails ou links do título e da descrição; use os campos de contato.',
      keyword_stuffing: 'Reduza palavras repetidas ou listas de palavras-chave.',
      title_description_duplicate: 'Evite repetir o título como descrição.',
      incomplete_preview_payload: 'Preencha os campos obrigatórios antes de verificar a qualidade.',
    },
  },
  fr: {
    title: 'Améliorez votre annonce',
    hardTitle: 'Corrigez ceci avant de continuer',
    warningIntro: 'Nous avons détecté des éléments pouvant réduire la qualité de l’annonce.',
    hardIntro: 'Ces éléments doivent être corrigés avant la publication.',
    continueAnyway: 'Continuer quand même',
    checkAgain: 'Vérifier à nouveau',
    checking: 'Vérification de la qualité...',
    previewUnavailable: 'La qualité ne peut pas être vérifiée maintenant. Vous pouvez continuer; la validation finale restera active lors de la publication.',
    unknown: 'Vérifiez ce détail avant de continuer.',
    codes: {
      title_too_short: 'Rendez le titre un peu plus descriptif.',
      description_too_short: 'Ajoutez davantage de détails utiles à la description.',
      title_placeholder: 'Remplacez le titre provisoire par un vrai titre.',
      description_placeholder: 'Remplacez la description provisoire par des informations utiles.',
      price_zero: 'Vérifiez le prix; il semble être égal à zéro.',
      photo_recommended: 'Ajoutez au moins une photo utile lorsque c’est possible.',
      contact_data_in_copy: 'Retirez les téléphones, e-mails ou liens du titre et de la description; utilisez les champs de contact.',
      keyword_stuffing: 'Réduisez les mots répétés ou les listes de mots-clés.',
      title_description_duplicate: 'Évitez de répéter le titre dans la description.',
      incomplete_preview_payload: 'Complétez les champs obligatoires avant de vérifier la qualité.',
    },
  },
  zh: {
    title: '完善你的广告',
    hardTitle: '继续前请先修正这些内容',
    warningIntro: '我们发现了一些可能降低广告质量的细节。',
    hardIntro: '这些问题必须在发布前修正。',
    continueAnyway: '仍然继续',
    checkAgain: '重新检查',
    checking: '正在检查质量...',
    previewUnavailable: '暂时无法检查质量。你可以继续，发布时仍会执行最终验证。',
    unknown: '继续前请检查此项。',
    codes: {
      title_too_short: '请让标题更具体一些。',
      description_too_short: '请在描述中添加更多有用信息。',
      title_placeholder: '请将临时标题替换为真实标题。',
      description_placeholder: '请将临时描述替换为有用信息。',
      price_zero: '请检查价格，它似乎为零。',
      photo_recommended: '如条件允许，请至少添加一张有用的照片。',
      contact_data_in_copy: '请从标题和描述中移除电话、邮箱或链接，并使用联系信息字段。',
      keyword_stuffing: '请减少重复词或关键词堆砌。',
      title_description_duplicate: '请不要直接用标题重复作为描述。',
      incomplete_preview_payload: '请先填写必填字段，再检查质量。',
    },
  },
  ko: {
    title: '광고 품질 개선',
    hardTitle: '계속하기 전에 수정하세요',
    warningIntro: '광고 품질을 낮출 수 있는 항목을 찾았습니다.',
    hardIntro: '이 항목은 게시 전에 수정해야 합니다.',
    continueAnyway: '그래도 계속',
    checkAgain: '다시 확인',
    checking: '품질 확인 중...',
    previewUnavailable: '지금은 품질을 확인할 수 없습니다. 계속할 수 있으며 게시 시 최종 검증은 그대로 실행됩니다.',
    unknown: '계속하기 전에 이 항목을 확인하세요.',
    codes: {
      title_too_short: '제목을 조금 더 구체적으로 작성하세요.',
      description_too_short: '설명에 유용한 정보를 더 추가하세요.',
      title_placeholder: '임시 제목을 실제 제목으로 바꾸세요.',
      description_placeholder: '임시 설명을 유용한 정보로 바꾸세요.',
      price_zero: '가격을 확인하세요. 0으로 보입니다.',
      photo_recommended: '가능하면 유용한 사진을 한 장 이상 추가하세요.',
      contact_data_in_copy: '제목과 설명에서 전화번호, 이메일, 링크를 제거하고 연락처 필드를 사용하세요.',
      keyword_stuffing: '반복 단어나 키워드 나열을 줄이세요.',
      title_description_duplicate: '제목을 설명에 그대로 반복하지 마세요.',
      incomplete_preview_payload: '품질 확인 전에 필수 항목을 완료하세요.',
    },
  },
  de: {
    title: 'Anzeige verbessern',
    hardTitle: 'Vor dem Fortfahren korrigieren',
    warningIntro: 'Wir haben Punkte gefunden, die die Qualität der Anzeige verringern können.',
    hardIntro: 'Diese Punkte müssen vor der Veröffentlichung korrigiert werden.',
    continueAnyway: 'Trotzdem fortfahren',
    checkAgain: 'Erneut prüfen',
    checking: 'Qualität wird geprüft...',
    previewUnavailable: 'Die Qualität kann gerade nicht geprüft werden. Du kannst fortfahren; die finale Prüfung läuft beim Veröffentlichen weiterhin.',
    unknown: 'Prüfe diesen Punkt, bevor du fortfährst.',
    codes: {
      title_too_short: 'Formuliere den Titel etwas aussagekräftiger.',
      description_too_short: 'Füge der Beschreibung weitere nützliche Details hinzu.',
      title_placeholder: 'Ersetze den Platzhaltertitel durch einen echten Titel.',
      description_placeholder: 'Ersetze die Platzhalterbeschreibung durch nützliche Informationen.',
      price_zero: 'Prüfe den Preis; er scheint null zu sein.',
      photo_recommended: 'Füge nach Möglichkeit mindestens ein hilfreiches Foto hinzu.',
      contact_data_in_copy: 'Entferne Telefonnummern, E-Mail-Adressen oder Links aus Titel und Beschreibung und nutze die Kontaktfelder.',
      keyword_stuffing: 'Reduziere wiederholte Wörter oder Keyword-Listen.',
      title_description_duplicate: 'Wiederhole den Titel nicht einfach als Beschreibung.',
      incomplete_preview_payload: 'Fülle die Pflichtfelder aus, bevor du die Qualität prüfst.',
    },
  },
  it: {
    title: 'Migliora il tuo annuncio',
    hardTitle: 'Correggi prima di continuare',
    warningIntro: 'Abbiamo rilevato dettagli che possono ridurre la qualità dell’annuncio.',
    hardIntro: 'Questi punti devono essere corretti prima della pubblicazione.',
    continueAnyway: 'Continua comunque',
    checkAgain: 'Controlla di nuovo',
    checking: 'Controllo qualità...',
    previewUnavailable: 'Non è possibile controllare la qualità adesso. Puoi continuare; la verifica finale resterà attiva al momento della pubblicazione.',
    unknown: 'Controlla questo dettaglio prima di continuare.',
    codes: {
      title_too_short: 'Rendi il titolo un po’ più descrittivo.',
      description_too_short: 'Aggiungi più dettagli utili alla descrizione.',
      title_placeholder: 'Sostituisci il titolo provvisorio con un titolo reale.',
      description_placeholder: 'Sostituisci la descrizione provvisoria con informazioni utili.',
      price_zero: 'Controlla il prezzo; sembra essere zero.',
      photo_recommended: 'Aggiungi almeno una foto utile quando possibile.',
      contact_data_in_copy: 'Rimuovi telefoni, e-mail o link dal titolo e dalla descrizione; usa i campi di contatto.',
      keyword_stuffing: 'Riduci le parole ripetute o gli elenchi di parole chiave.',
      title_description_duplicate: 'Evita di ripetere il titolo come descrizione.',
      incomplete_preview_payload: 'Completa i campi obbligatori prima del controllo qualità.',
    },
  },
  ar: {
    title: 'حسّن إعلانك',
    hardTitle: 'صحّح هذه النقاط قبل المتابعة',
    warningIntro: 'وجدنا تفاصيل قد تقلل من جودة الإعلان.',
    hardIntro: 'يجب تصحيح هذه النقاط قبل النشر.',
    continueAnyway: 'المتابعة رغم ذلك',
    checkAgain: 'التحقق مرة أخرى',
    checking: 'جارٍ التحقق من الجودة...',
    previewUnavailable: 'تعذر التحقق من الجودة الآن. يمكنك المتابعة، وسيظل التحقق النهائي فعالاً عند النشر.',
    unknown: 'راجع هذه النقطة قبل المتابعة.',
    codes: {
      title_too_short: 'اجعل العنوان أكثر وصفاً قليلاً.',
      description_too_short: 'أضف تفاصيل مفيدة أكثر إلى الوصف.',
      title_placeholder: 'استبدل العنوان المؤقت بعنوان حقيقي.',
      description_placeholder: 'استبدل الوصف المؤقت بمعلومات مفيدة.',
      price_zero: 'راجع السعر؛ يبدو أنه صفر.',
      photo_recommended: 'أضف صورة مفيدة واحدة على الأقل عندما يكون ذلك ممكناً.',
      contact_data_in_copy: 'احذف أرقام الهاتف أو البريد الإلكتروني أو الروابط من العنوان والوصف واستخدم حقول التواصل.',
      keyword_stuffing: 'قلل الكلمات المكررة أو قوائم الكلمات المفتاحية.',
      title_description_duplicate: 'تجنب تكرار العنوان نفسه كوصف.',
      incomplete_preview_payload: 'أكمل الحقول المطلوبة قبل التحقق من الجودة.',
    },
  },
  ru: {
    title: 'Улучшите объявление',
    hardTitle: 'Исправьте это перед продолжением',
    warningIntro: 'Мы нашли детали, которые могут снизить качество объявления.',
    hardIntro: 'Эти пункты нужно исправить до публикации.',
    continueAnyway: 'Всё равно продолжить',
    checkAgain: 'Проверить снова',
    checking: 'Проверяем качество...',
    previewUnavailable: 'Сейчас не удалось проверить качество. Можно продолжить; финальная проверка всё равно сработает при публикации.',
    unknown: 'Проверьте этот пункт перед продолжением.',
    codes: {
      title_too_short: 'Сделайте заголовок немного более информативным.',
      description_too_short: 'Добавьте в описание больше полезных деталей.',
      title_placeholder: 'Замените временный заголовок настоящим.',
      description_placeholder: 'Замените временное описание полезной информацией.',
      price_zero: 'Проверьте цену: похоже, она равна нулю.',
      photo_recommended: 'По возможности добавьте хотя бы одну полезную фотографию.',
      contact_data_in_copy: 'Уберите телефон, email или ссылки из заголовка и описания и используйте поля контактов.',
      keyword_stuffing: 'Сократите повторяющиеся слова и списки ключевых слов.',
      title_description_duplicate: 'Не повторяйте заголовок как описание.',
      incomplete_preview_payload: 'Заполните обязательные поля перед проверкой качества.',
    },
  },
  ja: {
    title: '出品内容を改善',
    hardTitle: '続行する前に修正してください',
    warningIntro: '出品の品質を下げる可能性がある項目が見つかりました。',
    hardIntro: 'これらの項目は公開前に修正する必要があります。',
    continueAnyway: 'このまま続行',
    checkAgain: 'もう一度確認',
    checking: '品質を確認中...',
    previewUnavailable: '現在は品質を確認できません。続行できます。公開時の最終検証は引き続き実行されます。',
    unknown: '続行する前にこの項目を確認してください。',
    codes: {
      title_too_short: 'タイトルをもう少し具体的にしてください。',
      description_too_short: '説明に役立つ情報を追加してください。',
      title_placeholder: '仮のタイトルを実際のタイトルに置き換えてください。',
      description_placeholder: '仮の説明を役立つ情報に置き換えてください。',
      price_zero: '価格を確認してください。0になっているようです。',
      photo_recommended: '可能であれば、役立つ写真を1枚以上追加してください。',
      contact_data_in_copy: 'タイトルや説明から電話番号、メール、リンクを削除し、連絡先欄を使用してください。',
      keyword_stuffing: '同じ単語の繰り返しやキーワードの羅列を減らしてください。',
      title_description_duplicate: 'タイトルをそのまま説明として繰り返さないでください。',
      incomplete_preview_payload: '品質確認の前に必須項目を入力してください。',
    },
  },
};

export function getListingQualityGuidance(lang = 'es') {
  return copy[lang] || copy.es;
}

export function listingQualityMessage(lang, code) {
  const localized = getListingQualityGuidance(lang);
  return localized.codes[code] || localized.unknown;
}

export const listingQualityGuidanceLanguages = Object.freeze(Object.keys(copy));
