export const mexicoLocations = {
  'Aguascalientes': ['Aguascalientes', 'Jesús María', 'Calvillo', 'Rincón de Romos', 'Pabellón de Arteaga', 'San Francisco de los Romo', 'Asientos', 'Tepezalá', 'Cosío', 'El Llano', 'San José de Gracia'],
  'Baja California': ['Tijuana', 'Mexicali', 'Ensenada', 'Playas de Rosarito', 'Tecate', 'San Quintín', 'San Felipe'],
  'Baja California Sur': ['La Paz', 'Los Cabos', 'Cabo San Lucas', 'San José del Cabo', 'Loreto', 'Mulegé', 'Santa Rosalía', 'Ciudad Constitución', 'Comondú'],
  'Campeche': ['Campeche', 'Ciudad del Carmen', 'Champotón', 'Escárcega', 'Calkiní', 'Hecelchakán', 'Hopelchén', 'Tenabo', 'Palizada', 'Calakmul', 'Candelaria'],
  'Chiapas': ['Tuxtla Gutiérrez', 'Tapachula', 'San Cristóbal de las Casas', 'Comitán de Domínguez', 'Chiapa de Corzo', 'Palenque', 'Ocosingo', 'Villaflores', 'Tonalá', 'Huixtla', 'Arriaga', 'Pichucalco', 'Reforma', 'Cintalapa', 'Jiquipilas', 'Motozintla', 'Frontera Comalapa'],
  'Chihuahua': ['Chihuahua', 'Ciudad Juárez', 'Delicias', 'Hidalgo del Parral', 'Cuauhtémoc', 'Nuevo Casas Grandes', 'Camargo', 'Jiménez', 'Ojinaga', 'Guachochi', 'Aldama', 'Meoqui', 'Guerrero', 'Ascensión'],
  'Ciudad de México': ['Álvaro Obregón', 'Coyoacán', 'Cuauhtémoc', 'Miguel Hidalgo', 'Tlalpan', 'Benito Juárez', 'Iztapalapa', 'Gustavo A. Madero', 'Tláhuac', 'Xochimilco', 'Venustiano Carranza', 'Iztacalco', 'Azcapotzalco', 'Cuajimalpa de Morelos', 'La Magdalena Contreras', 'Milpa Alta'],
  'Coahuila': ['Saltillo', 'Torreón', 'Monclova', 'Piedras Negras', 'Acuña', 'Sabinillas', 'San Pedro', 'Parras de la Fuente', 'Frontera', 'Ramos Arizpe', 'Múzquiz', 'Sabinas', 'Francisco I. Madero', 'Matamoros'],
  'Colima': ['Colima', 'Manzanillo', 'Tecomán', 'Villa de Álvarez', 'Armería', 'Comala', 'Coquimatlán', 'Cuauhtémoc', 'Ixtlahuacán', 'Minatitlán'],
  'Durango': ['Durango', 'Gómez Palacio', 'Lerdo', 'Santiago Papasquiaro', 'El Salto', 'Pueblo Nuevo', 'Cuencamé', 'Vicente Guerrero', 'Guadalupe Victoria', 'Mapimí', 'Canatlán'],
  'Estado de México': ['Toluca', 'Ecatepec de Morelos', 'Nezahualcóyotl', 'Naucalpan de Juárez', 'Tlalnepantla de Baz', 'Chimalhuacán', 'Cuautitlán Izcalli', 'Atizapán de Zaragoza', 'Tultitlán', 'Tecámac', 'Valle de Chalco Solidaridad', 'Ixtapaluca', 'Chalco', 'Coacalco de Berriozábal', 'Tultitlán', 'Texcoco', 'Metepec', 'Huixquilucan', 'Chicoloapan', 'La Paz', 'Zumpango', 'Nicolás Romero', 'Cuautitlán', 'Lerma', 'Atlacomulco', 'Teotihuacán', 'Valle de Bravo', 'Ixtlahuaca', 'Tenancingo'],
  'Guanajuato': ['León', 'Irapuato', 'Celaya', 'Salamanca', 'Guanajuato', 'Silao de la Victoria', 'San Miguel de Allende', 'Dolores Hidalgo', 'Pénjamo', 'Acámbaro', 'San Francisco del Rincón', 'Valle de Santiago', 'Cortazar', 'Moroleón', 'Uriangato', 'Yuriria', 'Salvaterra', 'San Luis de la Paz'],
  'Guerrero': ['Acapulco de Juárez', 'Chilpancingo de los Bravo', 'Iguala de la Independencia', 'Zihuatanejo', 'Taxco de Alarcón', 'Chilapa de Álvarez', 'Tlapa de Comonfort', 'Ometepec', 'Tecpan de Galeana', 'Coyuca de Benítez', 'Tixtla de Guerrero'],
  'Hidalgo': ['Pachuca de Soto', 'Tulancingo de Bravo', 'Tula de Allende', 'Mineral de la Reforma', 'Huejutla de Reyes', 'Ixmiquilpan', 'Tepeji del Río de Ocampo', 'Actopan', 'Apan', 'Tizayuca', 'Tepeapulco', 'Huichapan', 'Zacualtipán'],
  'Jalisco': ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Tlajomulco de Zúñiga', 'Tonalá', 'Puerto Vallarta', 'Lagos de Moreno', 'Tepatitlán de Morelos', 'Ciudad Guzmán', 'Ocotlán', 'Arandas', 'Tala', 'Autlán de Navarro', 'Ameca', 'San Juan de los Lagos', 'Sayula', 'Atotonilco el Alto', 'La Barca'],
  'Michoacán': ['Morelia', 'Uruapan', 'Zamora', 'Lázaro Cárdenas', 'Apatzingán de la Constitución', 'La Piedad de Cabadas', 'Zitácuaro', 'Sahuayo', 'Maravatío', 'Pátzcuaro', 'Ciudad Hidalgo', 'Jacona', 'Tarímbaro', 'Tacámbaro', 'Puruándiro', 'Zacapu', 'Los Reyes'],
  'Morelos': ['Cuernavaca', 'Jiutepec', 'Cuautla', 'Temixco', 'Yautepec', 'Emiliano Zapata', 'Xochitepec', 'Jojutla', 'Zacatepec', 'Tepoztlán', 'Puente de Ixtla', 'Yecapixtla'],
  'Nayarit': ['Tepic', 'Bahía de Banderas', 'Santiago Ixcuintla', 'Compostela', 'Xalisco', 'Acaponeta', 'Tecuala', 'Ixtlán del Río', 'Tuxpan', 'San Blas'],
  'Nuevo León': ['Monterrey', 'San Pedro Garza García', 'Guadalupe', 'Apodaca', 'San Nicolás de los Garza', 'General Escobedo', 'Santa Catarina', 'Juárez', 'García', 'Cadereyta Jiménez', 'Linares', 'Montemorelos', 'Allende', 'Santiago', 'Sabinas Hidalgo', 'Doctor Arroyo'],
  'Oaxaca': ['Oaxaca de Juárez', 'Salina Cruz', 'Puerto Escondido', 'Santa María Huatulco', 'San Juan Bautista Tuxtepec', 'Heroica Ciudad de Juchitán de Zaragoza', 'Santo Domingo Tehuantepec', 'San Pedro Mixtepec', 'Miahuatlán de Porfirio Díaz', 'Santiago Pinotepa Nacional', 'Heroica Ciudad de Tlaxiaco', 'Putla Villa de Guerrero'],
  'Puebla': ['Puebla de Zaragoza', 'Tehuacán', 'Atlixco', 'Cholula de Rivadavia', 'San Martín Texmelucan', 'Teziutlán', 'Huauchinango', 'Xicotepec', 'Zacatlán', 'Chignahuapan', 'Izúcar de Matamoros', 'Tepeaca', 'Acatlán de Osorio', 'Libres'],
  'Querétaro': ['Querétaro', 'San Juan del Río', 'Corregidora', 'El Marqués', 'Tequisquiapan', 'Cadereyta de Montes', 'Pedro Escobedo', 'Jalpan de Serra', 'Ezequiel Montes', 'Colón'],
  'Quintana Roo': ['Cancún', 'Playa del Carmen', 'Tulum', 'Chetumal', 'Cozumel', 'Isla Mujeres', 'Felipe Carrillo Puerto', 'José María Morelos', 'Bacalar', 'Puerto Morelos'],
  'San Luis Potosí': ['San Luis Potosí', 'Soledad de Graciano Sánchez', 'Ciudad Valles', 'Matehuala', 'Rioverde', 'Tamazunchale', 'Cárdenas', 'Salinas', 'Xilitla', 'Ciudad del Maíz', 'Santa María del Río'],
  'Sinaloa': ['Culiacán Rosales', 'Mazatlán', 'Los Mochis', 'Guasave', 'Navolato', 'Salvador Alvarado', 'Guamúchil', 'El Fuerte', 'Escuinapa', 'Rosario', 'Mocorito', 'Sinaloa de Leyva'],
  'Sonora': ['Hermosillo', 'Ciudad Obregón', 'Nogales', 'Guaymas', 'Navojoa', 'San Luis Río Colorado', 'Agua Prieta', 'Caborca', 'Empalme', 'Puerto Peñasco', 'Cananea', 'Magdalena de Kino', 'Huatabampo'],
  'Tabasco': ['Villahermosa', 'Cárdenas', 'Comalcalco', 'Huimanguillo', 'Macuspana', 'Teapa', 'Tenosique', 'Paraíso', 'Frontera', 'Tacotalpa', 'Jalpa de Méndez', 'Cunduacán'],
  'Tamaulipas': ['Tampico', 'Reynosa', 'Matamoros', 'Ciudad Victoria', 'Nuevo Laredo', 'Ciudad Madero', 'Altamira', 'El Mante', 'Río Bravo', 'Valle Hermoso', 'San Fernando', 'Miguel Alemán'],
  'Tlaxcala': ['Tlaxcala de Xicohténcatl', 'Apizaco', 'Huamantla', 'Chiautempan', 'San Pablo del Monte', 'Zacatelco', 'Calpulalpan', 'Tlaxco', 'Contla'],
  'Veracruz': ['Veracruz', 'Xalapa-Enríquez', 'Coatzacoalcos', 'Poza Rica de Hidalgo', 'Boca del Río', 'Orizaba', 'Córdoba', 'Minatitlán', 'Tuxpan', 'Tuxpam de Rodríguez Cano', 'Coatepec', 'Papantla', 'San Andrés Tuxtla', 'Cosoleacaque', 'Álamo', 'Tierra Blanca', 'Martinez de la Torre', 'Acayucan'],
  'Yucatán': ['Mérida', 'Valladolid', 'Progreso', 'Tizimín', 'Kanasín', 'Motul', 'Ticul', 'Umán', 'Oxkutzcab', 'Tekax', 'Hunucmá', 'Izamal', 'Peto', 'Halachó'],
  'Zacatecas': ['Zacatecas', 'Fresnillo', 'Guadalupe', 'Jerez de García Salinas', 'Sombrerete', 'Río Grande', 'Calera', 'Valparaíso', 'Nochistlán', 'Jalpa', 'Loreto', 'Ojocaliente']
};

export const subcategoriesMap = {
  'motor': ['Compactos', 'SUV', 'Pickup', 'Sedán', 'Hatchback', 'Coupé', 'Deportivos', 'Clásicos', 'Eléctricos', 'Accesorios', 'Camiones', 'Autobuses', 'Motos', 'Scooters', 'Cuatrimotos', 'UTV', 'Motos de agua', 'Refacciones', 'Cascos', 'Equipamiento', 'Bicicletas eléctricas', 'Patines eléctricos', 'Monociclos eléctricos', 'Karts de golf', 'Micro autos'],
  'inmobiliaria': ['Casas en venta', 'Casas en renta', 'Departamentos', 'Terrenos', 'Locales comerciales', 'Oficinas', 'Bodegas', 'Renta vacacional'],
  'empleo': ['Ventas', 'Chofer', 'Construcción', 'Administración', 'Atención al cliente', 'Tecnología', 'Hotelería', 'Medio tiempo'],
  'servicios': ['Mudanzas', 'Limpieza', 'Plomería', 'Electricidad', 'Cerrajería', 'Clases', 'Diseño', 'Eventos'],
  'moda': ['Ropa mujer', 'Ropa hombre', 'Calzado', 'Bolsos', 'Accesorios', 'Joyería', 'Cosmética'],
  'hogar': ['Muebles', 'Decoración', 'Electrodomésticos', 'Cocina', 'Jardín', 'Herramientas', 'Organización'],
  'electronica': ['Smartphones', 'Laptops', 'Tablets', 'PCs', 'Componentes', 'Monitores', 'TV y video', 'Audio', 'Smartwatches', 'Cámaras', 'Drones', 'Fundas y Carcasas', 'Cargadores y Cables', 'Impresoras', 'Redes', 'Accesorios', 'Repuestos'],
  'ocio': ['Bicicletas', 'Gym', 'Running', 'Camping', 'Pesca', 'Surf', 'Kayak', 'Arte', 'Antigüedades', 'Cómics', 'Monedas y Billetes', 'Música y Vinilos', 'Instrumentos musicales', 'Entradas', 'Juegos'],
  'infantil': ['Carriolas', 'Autoasientos', 'Cunas', 'Juguetes', 'Ropa infantil', 'Ropa bebé', 'Baño y cuidado', 'Escolar', 'Muebles infantiles', 'Seguridad'],
  'mascotas': ['Perros', 'Gatos', 'Aves', 'Peces', 'Accesorios', 'Alimento', 'Veterinaria'],
  'negocios': ['Traspasos', 'Franquicias', 'Equipamiento', 'Maquinaria', 'Industria', 'Inversión'],
  'formacion': ['Libros', 'Cursos', 'Idiomas', 'Universidad', 'Infantil', 'Programación'],
  'boletos': ['Conciertos', 'Deportes', 'Teatro y Cultura', 'Festivales', 'Cine', 'Conferencias'],
  'turismo': ['Hoteles y Hospedaje', 'Tours y Viajes', 'Boletos a Eventos', 'Artículos de Viaje y Outdoor', 'Souvenirs y Regalos', 'Renta de Transporte', 'Guías y Servicios', 'Atracciones y Experiencias', 'Retiros y Bienestar'],
  'hospedaje': ['Hoteles', 'Casas de huéspedes', 'Villas y Cabañas', 'Hostales'],
  'tours': ['Aventura y Naturaleza', 'Tours Culturales', 'Excursiones de Playa'],
  'boletos_turismo': ['Conciertos', 'Deportes', 'Teatro y Cultura'],
  'articulos_camping': ['Casas de campaña y Sacos', 'Mochilas y Maletas', 'Ropa de senderismo', 'Utensilios de cocina y Estufas', 'Linternas y GPS'],
  'souvenirs': ['Artesanías locales', 'Recuerdos de viaje', 'Regalos típicos'],
  'renta_vehiculos': ['Renta de Autos', 'Motos y Scooters', 'Renta de Bicicletas', 'Yates y Barcos', 'Motos Acuáticas y Jetski', 'Surf, Kayaks y Tablas', 'Quads, Buggies y ATV', 'Campers y Casas Rodantes'],
  'guias_servicios': ['Guías y Traductores', 'Fotógrafos de Viaje', 'Transfers y Taxis'],
  'atracciones_exp': ['Parques y Entradas', 'Gastronomía y Catas', 'Buceo y Deportes de agua'],
  'retiros_bienestar': ['Spa y Termas', 'Yoga y Meditación', 'Salud y Bienestar']
};
