export const mexicoLocations = {
  'Aguascalientes': ['Aguascalientes', 'Jesús María', 'Calvillo'],
  'Baja California': ['Tijuana', 'Mexicali', 'Ensenada', 'Playas de Rosarito', 'Tecate'],
  'Baja California Sur': ['La Paz', 'Los Cabos', 'San José del Cabo', 'Loreto'],
  'Campeche': ['Campeche', 'Ciudad del Carmen', 'Champotón'],
  'Chiapas': ['Tuxtla Gutiérrez', 'Tapachula', 'San Cristóbal de las Casas', 'Comitán'],
  'Chihuahua': ['Chihuahua', 'Ciudad Juárez', 'Delicias', 'Hidalgo del Parral'],
  'Ciudad de México': ['Álvaro Obregón', 'Coyoacán', 'Cuauhtémoc', 'Miguel Hidalgo', 'Tlalpan', 'Benito Juárez'],
  'Coahuila': ['Saltillo', 'Torreón', 'Monclova', 'Piedras Negras'],
  'Colima': ['Colima', 'Manzanillo', 'Tecomán'],
  'Durango': ['Durango', 'Gómez Palacio', 'Lerdo'],
  'Estado de México': ['Toluca', 'Ecatepec', 'Nezahualcóyotl', 'Naucalpan', 'Tlalnepantla'],
  'Guanajuato': ['León', 'Irapuato', 'Celaya', 'Salamanca', 'Guanajuato'],
  'Guerrero': ['Acapulco', 'Chilpancingo', 'Iguala', 'Zihuatanejo'],
  'Hidalgo': ['Pachuca', 'Tulancingo', 'Tula'],
  'Jalisco': ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Tlajomulco', 'Lagos de Moreno'],
  'Michoacán': ['Morelia', 'Uruapan', 'Zamora', 'Lázaro Cárdenas'],
  'Morelos': ['Cuernavaca', 'Jiutepec', 'Cuautla'],
  'Nayarit': ['Tepic', 'Bahía de Banderas', 'Santiago Ixcuintla'],
  'Nuevo León': ['Monterrey', 'San Pedro Garza García', 'Guadalupe', 'Apodaca', 'San Nicolás'],
  'Oaxaca': ['Oaxaca', 'Salina Cruz', 'Puerto Escondido', 'Huatulco'],
  'Puebla': ['Puebla', 'Tehuacán', 'Atlixco', 'Cholula'],
  'Querétaro': ['Querétaro', 'San Juan del Río', 'Corregidora'],
  'Quintana Roo': ['Cancún', 'Playa del Carmen', 'Tulum', 'Chetumal', 'Cozumel'],
  'San Luis Potosí': ['San Luis Potosí', 'Ciudad Valles', 'Matehuala'],
  'Sinaloa': ['Culiacán', 'Mazatlán', 'Los Mochis', 'Guasave'],
  'Sonora': ['Hermosillo', 'Ciudad Obregón', 'Nogales', 'Guaymas'],
  'Tabasco': ['Villahermosa', 'Cárdenas', 'Comalcalco'],
  'Tamaulipas': ['Tampico', 'Reynosa', 'Matamoros', 'Ciudad Victoria', 'Nuevo Laredo'],
  'Tlaxcala': ['Tlaxcala', 'Apizaco', 'Huamantla'],
  'Veracruz': ['Veracruz', 'Xalapa', 'Coatzacoalcos', 'Poza Rica', 'Boca del Río'],
  'Yucatán': ['Mérida', 'Valladolid', 'Progreso'],
  'Zacatecas': ['Zacatecas', 'Fresnillo', 'Guadalupe']
};

export const subcategoriesMap = {
  'coches': ['Compactos', 'SUV', 'Pickup', 'Sedán', 'Hatchback', 'Coupé', 'Deportivos', 'Clásicos', 'Eléctricos', 'Accesorios'],
  'motor': ['Motos', 'Scooters', 'Cuatrimotos', 'UTV', 'Motos de agua', 'Refacciones', 'Cascos', 'Equipamiento'],
  'inmobiliaria': ['Casas en venta', 'Casas en renta', 'Departamentos', 'Terrenos', 'Locales comerciales', 'Oficinas', 'Bodegas', 'Renta vacacional'],
  'empleo': ['Ventas', 'Chofer', 'Construcción', 'Administración', 'Atención al cliente', 'Tecnología', 'Hotelería', 'Medio tiempo'],
  'servicios': ['Mudanzas', 'Limpieza', 'Plomería', 'Electricidad', 'Cerrajería', 'Clases', 'Diseño', 'Eventos'],
  'moda': ['Ropa mujer', 'Ropa hombre', 'Calzado', 'Bolsos', 'Accesorios', 'Joyería', 'Cosmética'],
  'hogar': ['Muebles', 'Decoración', 'Electrodomésticos', 'Cocina', 'Jardín', 'Herramientas', 'Organización'],
  'electronica': ['Smartphones', 'Laptops', 'Tablets', 'PCs', 'Componentes', 'Monitores', 'TV y video', 'Audio', 'Smartwatches', 'Cámaras', 'Drones', 'Fundas y Carcasas', 'Cargadores y Cables', 'Impresoras', 'Redes', 'Accesorios', 'Repuestos'],
  'ocio': ['Bicicletas', 'Gym', 'Running', 'Camping', 'Pesca', 'Surf', 'Kayak', 'Arte', 'Antigüedades', 'Cómics', 'Monedas y Billetes', 'Música y Vinilos', 'Instrumentos musicales', 'Entradas', 'Juegos'],
  'infantil': ['Carriolas', 'Autoasientos', 'Cunas', 'Juguetes', 'Ropa infantil', 'Ropa bebé', 'Baño y cuidado', 'Escolar', 'Muebles infantiles', 'Seguridad'],
  'mascotas': ['Perros', 'Gatos', 'Aves', 'Peces', 'Accesorios', 'Alimento', 'Veterinaria'],
  'negocios': ['Traspasos', 'Franquicias', 'Equipamiento', 'Maquinaria', 'Industria', 'Inversión'],
  'formacion': ['Libros', 'Cursos', 'Idiomas', 'Universidad', 'Infantil', 'Programación'],
  'boletos': ['Conciertos', 'Deportes', 'Teatro y Cultura', 'Festivales', 'Cine', 'Conferencias']
};
