export const mexicoLocations = {
  'Aguascalientes': ['Aguascalientes', 'Jesús María', 'Calvillo'],
  'Baja California': ['Tijuana', 'Mexicali', 'Ensenada', 'Playas de Rosarito', 'Tecate'],
  'Baja California Sur': ['La Paz', 'Los Cabos', 'San José del Cabo', 'Loreto'],
  'Campeche': ['Campeche', 'Ciudad del Carmen', 'Champotón'],
  'Chiapas': ['Tuxtla Gutiérrez', 'Tapachula', 'San Cristóbal de las Casas', 'Comitán'],
  'Chihuahua': ['Chihuahua', 'Ciudad Juárez', 'Delicias', 'Hidalgo del Parral'],
  'Ciudad de México': ['Álvaro Obregón', 'Coyoacán', 'Cuauhtémoc', 'Miguel Hidalgo', 'Tlalpan', 'Benito Juárez'],
  'Coahuila': ['Saltillo', 'Torreón', 'Monclova', 'Piedras Negras'],
  'Colima': ['Colima', 'Manzanillo', 'Tecomán'],
  'Durango': ['Durango', 'Gómez Palacio', 'Lerdo'],
  'Estado de México': ['Toluca', 'Ecatepec', 'Nezahualcóyotl', 'Naucalpan', 'Tlalnepantla'],
  'Guanajuato': ['León', 'Irapuato', 'Celaya', 'Salamanca', 'Guanajuato'],
  'Guerrero': ['Acapulco', 'Chilpancingo', 'Iguala', 'Zihuatanejo'],
  'Hidalgo': ['Pachuca', 'Tulancingo', 'Tula'],
  'Jalisco': ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Tlajomulco', 'Lagos de Moreno'],
  'Michoacán': ['Morelia', 'Uruapan', 'Zamora', 'Lázaro Cárdenas'],
  'Morelos': ['Cuernavaca', 'Jiutepec', 'Cuautla'],
  'Nayarit': ['Tepic', 'Bahía de Banderas', 'Santiago Ixcuintla'],
  'Nuevo León': ['Monterrey', 'San Pedro Garza García', 'Guadalupe', 'Apodaca', 'San Nicolás'],
  'Oaxaca': ['Oaxaca', 'Salina Cruz', 'Puerto Escondido', 'Huatulco'],
  'Puebla': ['Puebla', 'Tehuacán', 'Atlixco', 'Cholula'],
  'Querétaro': ['Querétaro', 'San Juan del Río', 'Corregidora'],
  'Quintana Roo': ['Cancún', 'Playa del Carmen', 'Tulum', 'Chetumal', 'Cozumel'],
  'San Luis Potosí': ['San Luis Potosí', 'Ciudad Valles', 'Matehuala'],
  'Sinaloa': ['Culiacán', 'Mazatlán', 'Los Mochis', 'Guasave'],
  'Sonora': ['Hermosillo', 'Ciudad Obregón', 'Nogales', 'Guaymas'],
  'Tabasco': ['Villahermosa', 'Cárdenas', 'Comalcalco'],
  'Tamaulipas': ['Tampico', 'Reynosa', 'Matamoros', 'Ciudad Victoria', 'Nuevo Laredo'],
  'Tlaxcala': ['Tlaxcala', 'Apizaco', 'Huamantla'],
  'Veracruz': ['Veracruz', 'Xalapa', 'Coatzacoalcos', 'Poza Rica', 'Boca del Río'],
  'Yucatán': ['Mérida', 'Valladolid', 'Progreso'],
  'Zacatecas': ['Zacatecas', 'Fresnillo', 'Guadalupe']
};

export const subcategoriesMap = {
  'coches': ['Compactos', 'SUV', 'Pickup', 'Sedán', 'Hatchback', 'Coupé', 'Deportivos', 'Clásicos', 'Eléctricos', 'Accesorios'],
  'motor': ['Motos', 'Scooters', 'Cuatrimotos', 'UTV', 'Motos de agua', 'Refacciones', 'Cascos', 'Equipamiento'],
  'inmobiliaria': ['Casas en venta', 'Casas en renta', 'Departamentos', 'Terrenos', 'Locales comerciales', 'Oficinas', 'Bodegas', 'Renta vacacional'],
  'empleo': ['Ventas', 'Chofer', 'Construcción', 'Administración', 'Atención al cliente', 'Tecnología', 'Hotelería', 'Medio tiempo'],
  'servicios': ['Mudanzas', 'Limpieza', 'Plomería', 'Electricidad', 'Cerrajería', 'Clases', 'Diseño', 'Eventos'],
  'moda': ['Ropa mujer', 'Ropa hombre', 'Calzado', 'Bolsos', 'Accesorios', 'Joyería', 'Cosmética'],
  'hogar': ['Muebles', 'Decoración', 'Electrodomésticos', 'Cocina', 'Jardín', 'Herramientas', 'Organización'],
  'electronica': ['Laptops', 'Tablets', 'TV y video', 'Audio', 'Cámaras', 'Drones', 'Accesorios'],
  'telefonos': ['Smartphones', 'Fundas y Carcasas', 'Smartwatches', 'Cargadores y Cables', 'Repuestos'],
  'deportes': ['Bicicletas', 'Gym', 'Running', 'Camping', 'Pesca', 'Surf', 'Kayak'],
  'infantil': ['Juguetes', 'Ropa infantil', 'Escolar', 'Muebles infantiles', 'Seguridad'],
  'bebes': ['Carriolas', 'Autoasientos', 'Ropa bebé', 'Baño y cuidado', 'Cunas', 'Juguetes bebé'],
  'mascotas': ['Perros', 'Gatos', 'Aves', 'Peces', 'Accesorios', 'Alimento', 'Veterinaria'],
  'negocios': ['Traspasos', 'Franquicias', 'Equipamiento', 'Maquinaria', 'Industria', 'Inversión'],
  'formacion': ['Libros', 'Cursos', 'Idiomas', 'Universidad', 'Infantil', 'Programación'],
  'informatica': ['PCs', 'Componentes', 'Monitores', 'Impresoras', 'Redes'],
  'coleccionismo': ['Arte', 'Antigüedades', 'Cómics', 'Monedas y Billetes', 'Música y Vinilos', 'Instrumentos musicales', 'Entradas']
};

export const mockAds = [
  { id: 1, title: 'MacBook Pro M2 2023 512GB', price: 25000, currency: 'MXN', location: 'Polanco, CDMX', category: 'informatica', image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=400&h=300', description: 'Computadora en perfecto estado, batería al 100%. Entrego con caja y accesorios originales.', type: 'particular', promoted: false },
  { id: 2, title: 'Hermoso Departamento con vista panorámica', price: 280000, currency: 'MXN', location: 'Querétaro, Querétaro', category: 'inmobiliaria', image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=400&h=300', description: 'Totalmente amueblado. Amenidades incluyen piscina, gimnasio y seguridad 24/7.', type: 'pro', promoted: 'destacado' },
  { id: 3, title: 'Honda Civic 2020 EX - Único dueño', price: 320000, currency: 'MXN', location: 'Monterrey, Nuevo León', category: 'motor', image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=400&h=300', description: 'Todos los mantenimientos en agencia. Listo para carretera.', type: 'particular', promoted: 'urgente' },
];

export const translations = {
  es: {
    home: 'Inicio', search: 'Buscar', post: 'Publicar', profile: 'Perfil', categories: 'Categorías', recent_ads: 'Nuevos Anuncios',
    search_placeholder: 'Buscar en mercasto.com', all_mexico: 'Todo México',
    post_title: 'Pon tu anuncio', 
    ad_title: 'Título del anuncio', ad_desc: 'Descripción detallada', ad_price: 'Precio', publish_btn: 'Publicar Ahora',
    destacado: 'Destacado', urgente: 'Urgente', free_ad: 'Gratis',
    motor: 'Motor', inmobiliaria: 'Inmuebles', empleo: 'Empleo', servicios: 'Servicios', informatica: 'Informática', telefonia: 'Telefonía', hogar: 'Hogar', moda: 'Moda', bebes: 'Bebés', mascotas: 'Mascotas', ocio: 'Ocio', boletos: 'Boletos',
    dashboard: 'Panel de Usuario', my_ads: 'Mis Anuncios', logout: 'Cerrar sesión', admin_panel: 'Panel de Admin',
    upgrade_pro: 'Conviértete en PRO', upgrade_pro_desc: 'Vende más rápido con herramientas para profesionales.', settings: 'Ajustes', favorites: 'Favoritos',
    tariffs: 'Tarifas', pricing_title: 'Planes de Tarifas', tab_individuals: 'Para Particulares', tab_businesses: 'Para Negocios',
    plan_free: 'Gratuito', plan_plus: 'Pack Plus', plan_pro_basic: 'PRO Estándar', plan_pro_max: 'PRO Ilimitado',
    buy_plan: 'Contratar', current_plan: 'Plan Actual', particular: 'Particular', company_profile: 'Perfil de Empresa', mass_upload: 'Subida masiva (XML/CSV)',
    delete_ad: 'Eliminar', confirm_delete: '¿Estás seguro de que deseas eliminar este anuncio?',
    views: 'vistas', leads: 'contactos', active_ads: 'Activos', total_views: 'Vistas', promote: 'Promocionar',
    login: "Iniciar Sesión", register: "Crear Cuenta", email: "Correo", password: "Contraseña", name: "Nombre",
    forgot_password: '¿Olvidaste tu contraseña?', send_link: 'Enviar Enlace', reset_password: 'Restablecer Contraseña', new_password: 'Nueva Contraseña',
    noAds: "NO HAY RESULTADOS", search_results: "RESULTADOS DE BÚSQUEDA",
    heroTitle: "COMPRA Y VENDE EN TODO MÉXICO",
    heroDesc: "Únete a Mercasto. Publica tu anuncio gratis en segundos de forma fácil y segura.",
    heroTag: "MERCADO LÍDER", heroAction: "PON TU ANUNCIO",
    card1: "COMPRA SEGURA", card2: "VENDE RÁPIDO", card3: "SOPORTE 24/7",
    cardDesc1: "Moderación activa y protección contra fraudes.",
    cardDesc2: "Miles de compradores visitan Mercasto buscando ofertas.",
    cardDesc3: "Estamos aquí para ayudarte en cada paso de tu venta.",
    back_to_list: 'Volver al listado', back: 'Volver',
    category_stats: 'Estadísticas de Categorías', personal_info: 'Información Personal', 
    update_photo: 'Actualiza tu foto de perfil...', edit_profile: 'Editar Perfil', security: 'Seguridad', 
    update_password: 'Actualiza tu contraseña...', curr_password: 'Contraseña actual',
    conf_password: 'Confirmar nueva contraseña', update_pass_btn: 'Actualizar Contraseña', email_settings: 'Correo Electrónico', 
    update_email: 'Actualiza la dirección...', new_email: 'Nuevo correo electrónico', req_change: 'Solicitar Cambio', 
    notifications: 'Notificaciones', choose_alerts: 'Elige qué tipo de alertas quieres...', email_alerts: 'Alertas por correo', 
    push_alerts: 'Notificaciones Push', marketing_alerts: 'Promociones y boletín', save_prefs: 'Guardar Preferencias', 
    interface: 'Interfaz', customize_app: 'Personaliza la apariencia...', autoplay: 'Autoplay en carrusel', danger_zone: 'Zona de Peligro',
    del_warning: 'Una vez que elimines tu cuenta perderás todo...', del_account: 'Eliminar Cuenta', export_json: 'Exportar JSON', 
    cover_photo: 'Foto de Portada', upload_cover: 'Subir portada', comp_name: 'Nombre de la Empresa', comp_desc: 'Descripción del Negocio',
    website: 'Sitio Web', phone: 'Teléfono de Contacto', address: 'Dirección Comercial', save_changes: 'Guardar Cambios',
    cat_tab: 'Categorías', users_tab: 'Usuarios', mod_tab: 'Moderación', coupons_tab: 'Cupones', reports_tab: 'Reportes', 
    add_cat: 'Añadir Nueva Categoría', edit_cat: 'Editar Categoría', slug: 'Slug (identificador único)', icon: 'Icono', 
    name_es: 'Nombre en Español', name_en: 'Nombre en Inglés', sort_order: 'Orden', save_cat: 'Guardar Categoría', cancel: 'Cancelar', 
    existing_cats: 'Categorías Existentes', pending_ads: 'Anuncios Pendientes', no_pending: 'No hay anuncios para moderar', 
    approve: 'Aprobar', reject: 'Rechazar', coupon_gen: 'Generador de Cupones', code: 'Código', credits: 'Créditos', 
    max_uses: 'Usos Máx.', create: 'Crear', no_coupons: 'No hay cupones activos', report_center: 'Centro de Reportes', 
    reported_ad: 'Anuncio', reason: 'Motivo', comments: 'Comentarios', reported_by: 'Reportado por', action: 'Acción', 
    no_reports: 'No hay reportes', reported_user: 'Usuario Reportado', user_mgmt: 'Gestión de Usuarios', search_users: 'Buscar nombre o email...',
    role: 'Rol', hidden_ip: 'IP oculta', no_users: 'No se encontraron usuarios', ad_photos: 'Fotos del anuncio', 
    drag_photos: 'Arrastra tus fotos aquí o', browse: 'explora', max_photos: 'Máximo 10 fotos', category: 'Categoría', 
    select: 'Seleccionar...', condition: 'Estado', new: 'Nuevo', used: 'Usado', location: 'Ubicación', loc_placeholder: 'Escribe tu ciudad...', 
    video_opt: 'Video (Opcional)', report_ad: 'Reportar este anuncio', verified_seller: 'Vendedor Verificado', id_confirmed: 'Identidad confirmada',
    show_qr: 'Mostrar QR de Contacto', similar_ads: 'Anuncios similares', client_reviews: 'Reseñas de clientes', leave_review: 'Deja tu opinión', 
    publish_review: 'Publicar reseña', no_reviews: 'Este vendedor aún no tiene reseñas', scan_qr: 'Escanear QR', report_seller: 'Reportar a este vendedor', 
    verified_id: 'Identidad verificada', high_rep: 'Alta reputación', product_desc: 'Descripción del producto', no_desc: 'El vendedor no ha proporcionado una descripción.',
    download_pdf: 'Descargar Ficha PDF', contacts_qr: 'Contactos (QR)', conversion: 'Conversión',
    share_whatsapp: 'Compartir por WhatsApp', check_this_ad: '¡Mira este anuncio en Mercasto!',
    all: 'Todo', state: 'Estado', city: 'Ciudad / Municipio', all_cities: 'Todas las ciudades', apply: 'Aplicar',
    search_btn: 'Buscar', search_placeholder_short: 'Buscar producto...', guest: 'Invitado', post_ad: 'Publicar',
    mark_all_read: 'Marcar todas leídas', no_notifications: 'No tienes notificaciones',
    footer_desc: 'El marketplace local de más rápido crecimiento en México. Compra, vende, renta y encuentra empleo de forma segura.',
    buyers: 'Compradores', how_to_buy: 'Cómo comprar', safety_tips: 'Consejos de seguridad',
    sellers: 'Vendedores', pricing: 'Precios', promote_ad: 'Promocionar anuncio',
    business: 'Negocios', partners: 'Socios', help: 'Ayuda', help_center: 'Centro de Ayuda',
    safety_center: 'Centro de Seguridad', privacy_policy: 'Aviso de Privacidad',
    active_listings: 'anuncios activos', users_online: 'usuarios en línea', sell_fast: 'Vender rápido',
    find_job: 'Buscar empleo', rent_apt: 'Rentar depa', hire_service: 'Contratar servicio',
    browse_category: 'Explorar por categoría', sort_popular: 'Ordenar: Popular', show_less: 'Ver menos',
    view_all_cat: 'Ver todas las categorías →', trending_now: 'Tendencias', save_search: 'Guardar búsqueda',
    filter: 'Filtros', see_all: 'Ver todo →', deal_of_day: 'Oferta del día', up_to_40: 'Hasta 40% OFF',
    elec_phones: 'Electrónica y Celulares', shop_now: 'Comprar ahora →', ends_in_8h: 'Termina en 8h',
    furniture: 'Muebles', living_room_sets: 'Salas de estar', from_price: 'Desde $4,999 MXN',
    see_deals: 'Ver ofertas →', automotive: 'Automotriz', certified_cars: 'Autos Certificados',
    zero_comm: '0% comisión esta semana', browse_cars: 'Explorar 124k →', for_sellers: 'Para vendedores',
    boost_ad: 'Destaca tu anuncio', boost_desc: '3x más vistas, mejor posición', promote_now: 'Promocionar ahora →',
    re_spotlight: 'Inmuebles Destacados', rent: 'Rentar', buy: 'Comprar', commercial: 'Comercial',
    view_props: 'Ver propiedades →', open_map: 'Abrir mapa', view_all_mexico: 'Ver todo México',
    jobs_board: 'Bolsa de trabajo', remote_only: 'Solo remoto', full_time: 'Tiempo completo',
    company: 'Empresa', salary_mxn: 'Salario MXN', showing_jobs: 'Mostrando empleos nuevos',
    upload_cv: 'Subir CV', create_job_alert: 'Crear alerta', services_marketplace: 'Directorio de servicios',
    browse_services: 'Ver todos →', from: 'Desde', book_now: 'Reservar', year: 'Año', price: 'Precio',
    recently_viewed: 'Vistos recientemente', clear_history: 'Borrar historial',
    starter_desc: 'Ideal para ventas ocasionales', basic_stats: 'Estadísticas básicas',
    contacto_qr: 'Contacto vía QR', pro_desc: 'Para vendedores recurrentes', unlimited_ads: 'Anuncios ilimitados',
    boost_credits: 'Créditos mensuales', advanced_stats: 'Estadísticas PRO', verified_badge: 'Insignia Verificada',
    enterprise: 'Enterprise', enterprise_desc: 'Inmobiliarias, agencias...', bulk_import: 'Importación masiva',
    account_manager: 'Soporte dedicado', storefront: 'Página de Tienda', contact_sales: 'Contactar ventas',
    how_it_works: 'Cómo funciona Mercasto', post_60s: 'Publica en 60s',
    post_60s_desc: 'Fotos, precio, ubicación. La IA hace el resto.',
    get_leads: 'Recibe contactos', get_leads_desc: 'Llamadas, WhatsApp o escaneo QR seguro.',
    meet_safely: 'Encuentros seguros', meet_safely_desc: 'Perfiles verificados (KYC) para tu paz mental.',
    sell_faster: 'Vende rápido', sell_faster_desc: 'Destaca tu anuncio y cierra el trato hoy.',
    avoid_scams: 'Evita fraudes', avoid_scams_desc: 'Nunca pagues por adelantado. Revisa las insignias.',
    learn_more: 'Saber más', safe_payments: 'Pagos seguros',
    safe_payments_desc: 'Reúnete en público. Cuenta el dinero antes de irte.',
    verified_sellers: 'Vendedores verificados',
    verified_sellers_desc: 'Busca la insignia azul de identidad confirmada (KYC).',
    popular_searches: 'Búsquedas populares', updated_hourly: 'Actualizado hace 1h',
    explore_city: 'Explorar por ciudad', app_title: 'Mercasto en tu teléfono. Compra y vende más rápido.',
    app_desc: 'Recibe alertas instantáneas, gestiona todo desde tu móvil y comunícate seguro.',
    cam_autofill: 'Publicación rápida con cámara IA',
    safe_qr: 'Contacto seguro con código QR', free_no_ads: 'Gratis • Sin anuncios en PRO',
    newsletter_title: 'Recibe las mejores ofertas de México',
    newsletter_desc: 'Resumen semanal de ofertas, caída de precios y nuevos empleos.',
    your_email: 'Tu correo electrónico', subscribe: 'Suscribirse'
  },
  en: {
    home: 'Home', search: 'Search', post: 'Post Ad', profile: 'Profile', categories: 'Categories', recent_ads: 'Recent Ads',
    search_placeholder: 'Search on mercasto.com', all_mexico: 'All Mexico',
    post_title: 'Post your ad', 
    ad_title: 'Ad Title', ad_desc: 'Detailed Description', ad_price: 'Price', publish_btn: 'Publish Now',
    destacado: 'Featured', urgente: 'Urgent', free_ad: 'Free',
    motor: 'Motors', inmobiliaria: 'Real Estate', empleo: 'Jobs', servicios: 'Services', informatica: 'Computers', telefonia: 'Phones', hogar: 'Home', moda: 'Fashion', bebes: 'Babies', mascotas: 'Pets', ocio: 'Hobbies', boletos: 'Tickets',
    dashboard: 'Dashboard', my_ads: 'My Ads', logout: 'Logout', admin_panel: 'Admin Panel',
    upgrade_pro: 'Upgrade to PRO', upgrade_pro_desc: 'Sell faster with professional tools.', settings: 'Settings', favorites: 'Favorites',
    tariffs: 'Pricing', pricing_title: 'Pricing Plans', tab_individuals: 'For Individuals', tab_businesses: 'For Businesses',
    plan_free: 'Free', plan_plus: 'Plus Pack', plan_pro_basic: 'PRO Standard', plan_pro_max: 'PRO Unlimited',
    buy_plan: 'Subscribe', current_plan: 'Current Plan', particular: 'Individual', company_profile: 'Company Profile', mass_upload: 'Mass Upload (XML/CSV)',
    delete_ad: 'Delete', confirm_delete: 'Are you sure you want to delete this ad?',
    views: 'views', leads: 'leads', active_ads: 'Active', total_views: 'Views', promote: 'Promote',
    login: "Login", register: "Register", email: "Email", password: "Password", name: "Name",
    forgot_password: 'Forgot Password?', send_link: 'Send Link', reset_password: 'Reset Password', new_password: 'New Password',
    noAds: "NO RESULTS FOUND", search_results: "SEARCH RESULTS",
    heroTitle: "BUY AND SELL ACROSS MEXICO",
    heroDesc: "Join Mercasto. Post your ad for free in seconds easily and securely.",
    heroTag: "LEADING MARKET", heroAction: "POST AN AD",
    card1: "SECURE BUYING", card2: "FAST SELLING", card3: "24/7 SUPPORT",
    cardDesc1: "Active moderation and fraud protection.",
    cardDesc2: "Thousands of buyers visit Mercasto daily.",
    cardDesc3: "We are here to help you every step of the way.",
    back_to_list: 'Back to list', back: 'Back', category_stats: 'Category Statistics', personal_info: 'Personal Information', 
    update_photo: 'Update your profile photo...', edit_profile: 'Edit Profile', security: 'Security', update_password: 'Update your password...', 
    curr_password: 'Current password', conf_password: 'Confirm new password', update_pass_btn: 'Update Password',
    email_settings: 'Email Settings', update_email: 'Update your email...', new_email: 'New email address', req_change: 'Request Change', 
    notifications: 'Notifications', choose_alerts: 'Choose what alerts to receive...', email_alerts: 'Email alerts', push_alerts: 'Push notifications', 
    marketing_alerts: 'Promotions and newsletter', save_prefs: 'Save Preferences', interface: 'Interface', customize_app: 'Customize appearance...', 
    autoplay: 'Carousel autoplay', danger_zone: 'Danger Zone', del_warning: 'Once you delete your account...', del_account: 'Delete Account', 
    export_json: 'Export JSON', cover_photo: 'Cover Photo', upload_cover: 'Upload cover', comp_name: 'Company Name', comp_desc: 'Business Description', 
    website: 'Website', phone: 'Contact Phone', address: 'Business Address', save_changes: 'Save Changes', cat_tab: 'Categories', 
    users_tab: 'Users', mod_tab: 'Moderation', coupons_tab: 'Coupons', reports_tab: 'Reports', add_cat: 'Add New Category', 
    edit_cat: 'Edit Category', slug: 'Slug (unique identifier)', icon: 'Icon', name_es: 'Spanish Name', name_en: 'English Name', 
    sort_order: 'Order', save_cat: 'Save Category', cancel: 'Cancel', existing_cats: 'Existing Categories', pending_ads: 'Pending Ads', 
    no_pending: 'No ads to moderate', approve: 'Approve', reject: 'Reject', coupon_gen: 'Coupon Generator', code: 'Code', 
    credits: 'Credits', max_uses: 'Max Uses', create: 'Create', no_coupons: 'No active coupons', report_center: 'Report Center', 
    reported_ad: 'Ad', reason: 'Reason', comments: 'Comments', reported_by: 'Reported by', action: 'Action', no_reports: 'No reports', 
    reported_user: 'Reported User', user_mgmt: 'User Management', search_users: 'Search name or email...', role: 'Role', hidden_ip: 'Hidden IP', 
    no_users: 'No users found', ad_photos: 'Ad Photos', drag_photos: 'Drag your photos here or', browse: 'browse', max_photos: 'Max 10 photos', 
    category: 'Category', select: 'Select...', condition: 'Condition', new: 'New', used: 'Used', location: 'Location', 
    loc_placeholder: 'Type your city...', video_opt: 'Video (Optional)', report_ad: 'Report this ad', verified_seller: 'Verified Seller', 
    id_confirmed: 'Identity confirmed', show_qr: 'Show Contact QR', similar_ads: 'Similar ads', client_reviews: 'Customer reviews', 
    leave_review: 'Leave your review', publish_review: 'Publish review', no_reviews: 'This seller has no reviews yet', scan_qr: 'Scan QR', 
    report_seller: 'Report this seller', verified_id: 'Verified identity', high_rep: 'High reputation', product_desc: 'Product Description', 
    no_desc: 'The seller did not provide a description.', download_pdf: 'Download PDF Brochure', contacts_qr: 'Contacts (QR)', conversion: 'Conversion',
    share_whatsapp: 'Share on WhatsApp', check_this_ad: 'Check this listing on Mercasto!',
    all: 'All', state: 'State', city: 'City / Municipality', all_cities: 'All cities', apply: 'Apply',
    search_btn: 'Search', search_placeholder_short: 'Search product...', guest: 'Guest', post_ad: 'Post',
    mark_all_read: 'Mark all read', no_notifications: 'You have no notifications',
    footer_desc: 'Mexico’s fast-growing local marketplace. Buy, sell, rent and find work safely.',
    buyers: 'Buyers', how_to_buy: 'How to buy', safety_tips: 'Safety tips',
    sellers: 'Sellers', pricing: 'Pricing', promote_ad: 'Promote listing',
    business: 'Business', partners: 'Partners', help: 'Help', help_center: 'Help Center',
    safety_center: 'Safety Center', privacy_policy: 'Privacy Notice',
    active_listings: 'active listings', users_online: 'users online', sell_fast: 'Sell fast',
    find_job: 'Find a job', rent_apt: 'Rent apartment', hire_service: 'Hire service',
    browse_category: 'Explore by category', sort_popular: 'Sort: Popular', show_less: 'Show less',
    view_all_cat: 'See all categories →', trending_now: 'Trending', save_search: 'Save search',
    filter: 'Filters', see_all: 'See all →', deal_of_day: 'Deal of the day', up_to_40: 'Up to 40% OFF',
    elec_phones: 'Electronics and Phones', shop_now: 'Shop now →', ends_in_8h: 'Ends in 8h',
    furniture: 'Furniture', living_room_sets: 'Living room sets', from_price: 'From $4,999 MXN',
    see_deals: 'See deals →', automotive: 'Automotive', certified_cars: 'Certified Cars',
    zero_comm: '0% commission this week', browse_cars: 'Explore 124k →', for_sellers: 'For sellers',
    boost_ad: 'Boost your listing', boost_desc: '3x more views, better placement', promote_now: 'Promote now →',
    re_spotlight: 'Featured Real Estate', rent: 'Rent', buy: 'Buy', commercial: 'Commercial',
    view_props: 'View properties →', open_map: 'Open map', view_all_mexico: 'View all Mexico',
    jobs_board: 'Jobs board', remote_only: 'Remote only', full_time: 'Full-time',
    company: 'Company', salary_mxn: 'Salary MXN', showing_jobs: 'Showing new jobs',
    upload_cv: 'Upload CV', create_job_alert: 'Create alert', services_marketplace: 'Services directory',
    browse_services: 'See all →', from: 'From', book_now: 'Book now', year: 'Year', price: 'Price',
    recently_viewed: 'Recently viewed', clear_history: 'Clear history',
    starter_desc: 'Ideal for occasional sales', basic_stats: 'Basic stats',
    contacto_qr: 'QR contact', pro_desc: 'For repeat sellers', unlimited_ads: 'Unlimited listings',
    boost_credits: 'Monthly credits', advanced_stats: 'PRO analytics', verified_badge: 'Verified badge',
    enterprise: 'Enterprise', enterprise_desc: 'Real estate firms, agencies...', bulk_import: 'Bulk import',
    account_manager: 'Dedicated support', storefront: 'Storefront page', contact_sales: 'Contact sales',
    how_it_works: 'How Mercasto works', post_60s: 'Post in 60s',
    post_60s_desc: 'Photos, price, location. AI helps with the rest.',
    get_leads: 'Get leads', get_leads_desc: 'Calls, WhatsApp or secure QR scan.',
    meet_safely: 'Meet safely', meet_safely_desc: 'Verified profiles (KYC) for peace of mind.',
    sell_faster: 'Sell faster', sell_faster_desc: 'Feature your listing and close the deal today.',
    avoid_scams: 'Avoid scams', avoid_scams_desc: 'Never pay in advance. Check the badges.',
    learn_more: 'Learn more', safe_payments: 'Safe payments',
    safe_payments_desc: 'Meet in public. Count the cash before leaving.',
    verified_sellers: 'Verified sellers',
    verified_sellers_desc: 'Look for the blue identity-confirmed badge (KYC).',
    popular_searches: 'Popular searches', updated_hourly: 'Updated 1h ago',
    explore_city: 'Explore by city', app_title: 'Mercasto on your phone. Buy and sell faster.',
    app_desc: 'Get instant alerts, manage everything from mobile and communicate safely.',
    cam_autofill: 'Fast posting with AI camera',
    safe_qr: 'Secure contact with QR code', free_no_ads: 'Free • No ads in PRO',
    newsletter_title: 'Get Mexico’s best deals',
    newsletter_desc: 'Weekly digest of deals, price drops and new jobs.',
    your_email: 'Your email address', subscribe: 'Subscribe'
  },
  pt: {
    home: 'Início', search: 'Pesquisar', post: 'Publicar Anúncio', profile: 'Perfil', categories: 'Categorias', recent_ads: 'Anúncios Recentes',
    search_placeholder: 'Pesquisar no mercasto.com', all_mexico: 'Todo o México',
    post_title: 'Publique seu anúncio', 
    ad_title: 'Título do anúncio', ad_desc: 'Descrição detalhada', ad_price: 'Preço', publish_btn: 'Publicar Agora',
    destacado: 'Destaque', urgente: 'Urgente', free_ad: 'Grátis',
    motor: 'Motores', inmobiliaria: 'Imóveis', empleo: 'Emprego', servicios: 'Serviços', informatica: 'Informática', telefonia: 'Celulares', hogar: 'Casa', moda: 'Moda', bebes: 'Bebês', mascotas: 'Pets', ocio: 'Lazer', boletos: 'Ingressos',
    dashboard: 'Painel', my_ads: 'Meus Anúncios', logout: 'Sair', admin_panel: 'Painel Admin',
    upgrade_pro: 'Seja PRO', upgrade_pro_desc: 'Venda mais rápido com ferramentas profissionais.', settings: 'Configurações', favorites: 'Favoritos',
    tariffs: 'Tarifas', pricing_title: 'Planos de Preços', tab_individuals: 'Para Pessoas', tab_businesses: 'Para Empresas',
    plan_free: 'Grátis', plan_plus: 'Pacote Plus', plan_pro_basic: 'PRO Padrão', plan_pro_max: 'PRO Ilimitado',
    buy_plan: 'Assinar', current_plan: 'Plano Atual', particular: 'Particular', company_profile: 'Perfil da Empresa', mass_upload: 'Upload em Massa (XML/CSV)',
    delete_ad: 'Excluir', confirm_delete: 'Tem certeza de que deseja excluir este anúncio?',
    views: 'visualizações', leads: 'contatos', active_ads: 'Ativos', total_views: 'Visualizações', promote: 'Promover',
    login: "Entrar", register: "Criar Conta", email: "E-mail", password: "Senha", name: "Nome",
    forgot_password: 'Esqueceu a senha?', send_link: 'Enviar Link', reset_password: 'Redefinir Senha', new_password: 'Nova Senha',
    noAds: "NENHUM RESULTADO ENCONTRADO", search_results: "RESULTADOS DA PESQUISA",
    heroTitle: "COMPRE E VENDA EM TODO O MÉXICO",
    heroDesc: "Junte-se ao Mercasto. Publique seu anúncio grátis em segundos, de forma fácil e segura.",
    heroTag: "MERCADO LÍDER", heroAction: "PUBLIQUE UM ANÚNCIO",
    card1: "COMPRA SEGURA", card2: "VENDA RÁPIDO", card3: "SUPORTE 24/7",
    cardDesc1: "Moderação ativa e proteção contra fraudes.",
    cardDesc2: "Milhares de compradores visitam o Mercasto diariamente.",
    cardDesc3: "Estamos aqui para ajudar em cada etapa.",
    back_to_list: 'Voltar à lista', back: 'Voltar', category_stats: 'Estatísticas de Categoria', personal_info: 'Informação Pessoal', 
    update_photo: 'Atualize sua foto de perfil...', edit_profile: 'Editar Perfil', security: 'Segurança', update_password: 'Atualize sua senha...', 
    curr_password: 'Senha atual', conf_password: 'Confirmar nova senha', update_pass_btn: 'Atualizar Senha',
    email_settings: 'Configurações de E-mail', update_email: 'Atualize seu e-mail...', new_email: 'Novo e-mail', req_change: 'Solicitar Mudança', 
    notifications: 'Notificações', choose_alerts: 'Escolha quais alertas receber...', email_alerts: 'Alertas por e-mail', push_alerts: 'Notificações Push', 
    marketing_alerts: 'Promoções e newsletter', save_prefs: 'Salvar Preferências', interface: 'Interface', customize_app: 'Personalizar aparência...', 
    autoplay: 'Autoplay do carrossel', danger_zone: 'Zona de Perigo', del_warning: 'Depois de excluir sua conta...', del_account: 'Excluir Conta', 
    export_json: 'Exportar JSON', cover_photo: 'Foto de Capa', upload_cover: 'Enviar capa', comp_name: 'Nome da Empresa', comp_desc: 'Descrição do Negócio', 
    website: 'Site', phone: 'Telefone de Contato', address: 'Endereço Comercial', save_changes: 'Salvar Alterações', cat_tab: 'Categorias', 
    users_tab: 'Usuários', mod_tab: 'Moderação', coupons_tab: 'Cupons', reports_tab: 'Denúncias', add_cat: 'Adicionar Categoria', 
    edit_cat: 'Editar Categoria', slug: 'Slug (identificador)', icon: 'Ícone', name_es: 'Nome em Espanhol', name_en: 'Nome em Inglês', 
    sort_order: 'Ordem', save_cat: 'Salvar Categoria', cancel: 'Cancelar', existing_cats: 'Categorias Existentes', pending_ads: 'Anúncios Pendentes', 
    no_pending: 'Sem anúncios para moderar', approve: 'Aprovar', reject: 'Rejeitar', coupon_gen: 'Gerador de Cupons', code: 'Código', 
    credits: 'Créditos', max_uses: 'Usos Máx.', create: 'Criar', no_coupons: 'Nenhum cupom ativo', report_center: 'Central de Denúncias', 
    reported_ad: 'Anúncio', reason: 'Motivo', comments: 'Comentários', reported_by: 'Denunciado por', action: 'Ação', no_reports: 'Nenhuma denúncia', 
    reported_user: 'Usuário Denunciado', user_mgmt: 'Gestão de Usuários', search_users: 'Buscar nome ou e-mail...', role: 'Cargo', hidden_ip: 'IP Oculto', 
    no_users: 'Nenhum usuário encontrado', ad_photos: 'Fotos do anúncio', drag_photos: 'Arraste suas fotos ou', browse: 'procurar', max_photos: 'Máx 10 fotos', 
    category: 'Categoria', select: 'Selecionar...', condition: 'Condição', new: 'Novo', used: 'Usado', location: 'Localização', 
    loc_placeholder: 'Digite sua cidade...', video_opt: 'Vídeo (Opcional)', report_ad: 'Denunciar este anúncio', verified_seller: 'Vendedor Verificado', 
    id_confirmed: 'Identidade confirmada', show_qr: 'Mostrar QR de Contato', similar_ads: 'Anúncios similares', client_reviews: 'Avaliações de clientes', 
    leave_review: 'Deixe sua opinião', publish_review: 'Publicar avaliação', no_reviews: 'Este vendedor não tem avaliações', scan_qr: 'Escanear QR', 
    report_seller: 'Denunciar vendedor', verified_id: 'Identidade verificada', high_rep: 'Alta reputação', product_desc: 'Descrição do produto', 
    no_desc: 'O vendedor não forneceu uma descrição.', download_pdf: 'Baixar Folheto PDF', contacts_qr: 'Contatos (QR)', conversion: 'Conversão',
    share_whatsapp: 'Compartilhar no WhatsApp', check_this_ad: 'Veja este anúncio no Mercasto!',
    all: 'Tudo', state: 'Estado', city: 'Cidade / Município', all_cities: 'Todas as cidades', apply: 'Aplicar',
    search_btn: 'Pesquisar', search_placeholder_short: 'Buscar produto...', guest: 'Convidado', post_ad: 'Publicar',
    mark_all_read: 'Marcar todas como lidas', no_notifications: 'Você não tem notificações',
    footer_desc: 'O marketplace local que mais cresce no México. Compre, venda, alugue e encontre trabalho com segurança.',
    buyers: 'Compradores', how_to_buy: 'Como comprar', safety_tips: 'Dicas de segurança',
    sellers: 'Vendedores', pricing: 'Preços', promote_ad: 'Promover anúncio',
    business: 'Negócios', partners: 'Parceiros', help: 'Ajuda', help_center: 'Central de Ajuda',
    safety_center: 'Central de Segurança', privacy_policy: 'Aviso de Privacidade',
    active_listings: 'anúncios ativos', users_online: 'usuários online', sell_fast: 'Vender rápido',
    find_job: 'Buscar emprego', rent_apt: 'Alugar apê', hire_service: 'Contratar serviço',
    browse_category: 'Explorar por categoria', sort_popular: 'Ordenar: Popular', show_less: 'Ver menos',
    view_all_cat: 'Ver todas as categorias →', trending_now: 'Tendências', save_search: 'Salvar busca',
    filter: 'Filtros', see_all: 'Ver tudo →', deal_of_day: 'Oferta do dia', up_to_40: 'Até 40% OFF',
    elec_phones: 'Eletrônicos e Celulares', shop_now: 'Comprar agora →', ends_in_8h: 'Termina em 8h',
    furniture: 'Móveis', living_room_sets: 'Salas de estar', from_price: 'Desde $4,999 MXN',
    see_deals: 'Ver ofertas →', automotive: 'Automotivo', certified_cars: 'Carros Certificados',
    zero_comm: '0% comissão esta semana', browse_cars: 'Explorar 124k →', for_sellers: 'Para vendedores',
    boost_ad: 'Destaque seu anúncio', boost_desc: '3x mais visualizações, melhor posição', promote_now: 'Promover agora →',
    re_spotlight: 'Imóveis em destaque', rent: 'Alugar', buy: 'Comprar', commercial: 'Comercial',
    view_props: 'Ver imóveis →', open_map: 'Abrir mapa', view_all_mexico: 'Ver todo o México',
    jobs_board: 'Vagas de emprego', remote_only: 'Somente remoto', full_time: 'Tempo integral',
    company: 'Empresa', salary_mxn: 'Salário MXN', showing_jobs: 'Mostrando novas vagas',
    upload_cv: 'Enviar CV', create_job_alert: 'Criar alerta', services_marketplace: 'Diretório de serviços',
    browse_services: 'Ver todos →', from: 'Desde', book_now: 'Reservar', year: 'Ano', price: 'Preço',
    recently_viewed: 'Vistos recentemente', clear_history: 'Limpar histórico',
    starter_desc: 'Ideal para vendas ocasionais', basic_stats: 'Estatísticas básicas',
    contacto_qr: 'Contato via QR', pro_desc: 'Para vendedores recorrentes', unlimited_ads: 'Anúncios ilimitados',
    boost_credits: 'Créditos mensais', advanced_stats: 'Estatísticas PRO', verified_badge: 'Selo verificado',
    enterprise: 'Enterprise', enterprise_desc: 'Imobiliárias, agências...', bulk_import: 'Importação em massa',
    account_manager: 'Suporte dedicado', storefront: 'Página da loja', contact_sales: 'Contatar vendas',
    how_it_works: 'Como o Mercasto funciona', post_60s: 'Publique em 60s',
    post_60s_desc: 'Fotos, preço, localização. A IA ajuda com o resto.',
    get_leads: 'Receba contatos', get_leads_desc: 'Chamadas, WhatsApp ou QR seguro.',
    meet_safely: 'Encontros seguros', meet_safely_desc: 'Perfis verificados (KYC) para sua tranquilidade.',
    sell_faster: 'Venda mais rápido', sell_faster_desc: 'Destaque seu anúncio e feche negócio hoje.',
    avoid_scams: 'Evite golpes', avoid_scams_desc: 'Nunca pague adiantado. Confira os selos.',
    learn_more: 'Saiba mais', safe_payments: 'Pagamentos seguros',
    safe_payments_desc: 'Encontre-se em público. Conte o dinheiro antes de sair.',
    verified_sellers: 'Vendedores verificados',
    verified_sellers_desc: 'Procure o selo azul de identidade confirmada (KYC).',
    popular_searches: 'Buscas populares', updated_hourly: 'Atualizado há 1h',
    explore_city: 'Explorar por cidade', app_title: 'Mercasto no seu telefone. Compre e venda mais rápido.',
    app_desc: 'Receba alertas instantâneos, gerencie tudo pelo celular e converse com segurança.',
    cam_autofill: 'Publicação rápida com câmera IA',
    safe_qr: 'Contato seguro com código QR', free_no_ads: 'Grátis • Sem anúncios no PRO',
    newsletter_title: 'Receba as melhores ofertas do México',
    newsletter_desc: 'Resumo semanal de ofertas, quedas de preço e novas vagas.',
    your_email: 'Seu e-mail', subscribe: 'Inscrever-se'
  }
};

export const spotlightRealEstate = [
  { type: 'BUY', color: 'bg-slate-900', price: '$3,250,000', specs: '3 bed • 2 bath • 145m² Condo Marina', location: 'PV • 1d ago', img: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } },
  { type: 'RENT', color: 'bg-[#84CC16]', price: '$28,000/mo', specs: '2 bed • 2 bath • 98m² Versalles', location: 'GDL • 5h ago', img: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600', badge: { label: 'Top seller', color: 'bg-blue-100 text-blue-700' } },
  { type: 'BUY', color: 'bg-slate-900', price: '$1,850,000', specs: 'Casa 3 rec • 180m² • Jardín', location: 'Tlaquepaque • 2d ago', img: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=600' },
  { type: 'RENT', color: 'bg-[#84CC16]', price: '$18,500/mo', specs: 'Loft 1 bed • Zona Romántica', location: 'PV • 3h ago', img: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600', badge: { label: 'Urgent', color: 'bg-red-500 text-white' } },
  { type: 'BUY', color: 'bg-slate-900', price: '$4,900,000', specs: 'Penthouse 4 bed • Vista mar', location: 'Marina • 6h ago', img: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } },
  { type: 'RENT', color: 'bg-[#84CC16]', price: '$12,000/mo', specs: 'Studio amueblado • Providencia', location: 'GDL • 1d ago', img: 'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=600' }
];

export const jobsBoard = [
  { role: 'Senior React Developer', company: 'Mercasto', salary: '$65k – $85k', loc: 'Remote', logo: 'bg-lime-50 border', initial: 'MD' },
  { role: 'Restaurant Manager', company: 'La Palapa', salary: '$25,000', loc: 'Querétaro', logo: 'bg-amber-100 text-amber-700', initial: 'LP' },
  { role: 'Real Estate Agent', company: 'Century 21', salary: '$20k + Commission', loc: 'Guadalajara', logo: 'bg-blue-100 text-blue-700', initial: 'C21' },
  { role: 'English Teacher', company: 'Harmon Hall', salary: '$18,000', loc: 'Zapopan', logo: 'bg-emerald-100 text-emerald-700', initial: 'HH' },
  { role: 'Delivery Driver', company: 'DiDi', salary: '$15k – $22k', loc: 'Guadalajara', logo: 'bg-purple-100 text-purple-700', initial: 'Di' },
  { role: 'Graphic Designer (Freelance)', company: 'Freelance', salary: '$30,000', loc: 'Remote', logo: 'bg-slate-200', initial: '🎨' },
  { role: 'Barista', company: 'Starbucks', salary: '$12,500', loc: 'Guadalajara', logo: 'bg-green-100 text-green-700', initial: 'SB' },
  { role: 'Plumber - Full Time', company: 'Servicios Pro', salary: '$22,000', loc: 'Zapopan', logo: 'bg-orange-100', initial: '🔧' }
];

export const servicesMarketplace = [
  { title: 'House Cleaning Pro', stars: '4.9 (342)', price: '$450', img: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=100', desc: 'Deep cleaning, apartments & houses. Same-day available in PV.', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } },
  { title: 'AC Repair 24/7', stars: '4.8 (189)', price: '$650', img: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=100', desc: 'Installation, maintenance, emergency repair. 1yr warranty.', badge: { label: 'Top', color: 'bg-blue-100 text-blue-700' } },
  { title: 'Personal Trainer', stars: '5.0 (97)', price: '$300/hr', img: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=100', desc: 'Home or gym sessions. Weight loss & strength programs.' },
  { title: 'Event Photographer', stars: '4.7 (156)', price: '$2,500', img: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=100', desc: 'Weddings, corporate, real estate. Drone included.', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } },
  { title: 'Plumber Expert', stars: '4.9 (423)', price: '$400', img: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=100', desc: 'Leaks, installations, 24h emergency service Vallarta.' },
  { title: 'Web Design Studio', stars: '5.0 (64)', price: '$8,900', img: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=100', desc: 'Landing pages, e-commerce, SEO. 7-day delivery.', badge: { label: 'Top', color: 'bg-blue-100 text-blue-700' } },
  { title: 'Dog Walker & Sitting', stars: '4.9 (201)', price: '$150', img: 'https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=100', desc: 'Daily walks, pet sitting, vet visits. Insured.' },
  { title: 'Electrician Certified', stars: '4.8 (178)', price: '$500', img: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=100', desc: 'Wiring, panels, smart home installation. Licensed.', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } }
];

export const automotiveDeals = [
  { price: '$235,000', title: 'Nissan Versa 2021 Advance', specs: '45,000 km • Auto • GDL', img: 'https://images.unsplash.com/photo-1550355291-bbee04a92027?w=600', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } },
  { price: '$289,000', title: 'VW Jetta 2019 Comfortline', specs: '62,300 km • Auto • PV', img: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600', badge: { label: 'Top seller', color: 'bg-blue-100 text-blue-700' } },
  { price: '$345,000', title: 'Toyota Corolla 2020 Hybrid', specs: '38,100 km • Hybrid • GDL', img: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=600', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } },
  { price: '$285,000', title: 'Honda Civic 2019 Touring', specs: '71,200 km • Auto • Zapopan', img: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600' },
  { price: '$195,000', title: 'Chevrolet Aveo 2022 LT', specs: '29,500 km • Manual • PV', img: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=600', badge: { label: 'New', color: 'bg-[#84CC16] text-white' } },
  { price: '$420,000', title: 'Mazda CX-5 2021 i Sport', specs: '41,000 km • SUV • GDL', img: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } }
];

export const recentlyViewed = [
  { name: 'iPhone 15 Pro', price: '$18,999', img: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=200' },
  { name: '2BR Marina', price: '$32k/mo', img: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=200' },
  { name: 'Yamaha MT-07', price: '$145k', img: 'https://images.unsplash.com/photo-1558981282-6f5f7d5a2b8f?w=200' },
  { name: 'MacBook Air M2', price: '$24,500', img: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=200' },
  { name: 'Condo 3 bed', price: '$3.25M', img: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=200' },
  { name: 'Nike Air Max', price: '$1,850', img: 'https://images.unsplash.com/photo-1542291026-797186bcca9e?w=200' }
];
