export const mexicoLocations = {
  'Aguascalientes': ['Aguascalientes', 'Jesús María', 'Calvillo'],
  'Baja California': ['Tijuana', 'Mexicali', 'Ensenada', 'Playas de Rosarito', 'Tecate'],
  'Baja California Sur': ['La Paz', 'Los Cabos', 'San José del Cabo', 'Loreto'],
  'Campeche': ['Campeche', 'Ciudad del Carmen', 'Champotón'],
  'Chiapas': ['Tuxtla Gutiérrez', 'Tapachula', 'San Cristóbal de las Casas', 'Comitán'],
  'Chihuahua': ['Chihuahua', 'Ciudad Juárez', 'Delicias', 'Hidalgo del Parral'],
  'Ciudad de México': ['Álvaro Obregón', 'Coyoacán', 'Cuauhtémoc', 'Miguel Hidalgo', 'Tlalpan', 'Benito Juárez'],
  'Coahuila': ['Saltillo', 'Torreón', 'Monclova', 'Piedras Negras'],
  'Colima': ['Colima', 'Manzanillo', 'Tecomán'],
  'Durango': ['Durango', 'Gómez Palacio', 'Lerdo'],
  'Estado de México': ['Toluca', 'Ecatepec', 'Nezahualcóyotl', 'Naucalpan', 'Tlalnepantla'],
  'Guanajuato': ['León', 'Irapuato', 'Celaya', 'Salamanca', 'Guanajuato'],
  'Guerrero': ['Acapulco', 'Chilpancingo', 'Iguala', 'Zihuatanejo'],
  'Hidalgo': ['Pachuca', 'Tulancingo', 'Tula'],
  'Jalisco': ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Tlajomulco', 'Lagos de Moreno'],
  'Michoacán': ['Morelia', 'Uruapan', 'Zamora', 'Lázaro Cárdenas'],
  'Morelos': ['Cuernavaca', 'Jiutepec', 'Cuautla'],
  'Nayarit': ['Tepic', 'Bahía de Banderas', 'Santiago Ixcuintla'],
  'Nuevo León': ['Monterrey', 'San Pedro Garza García', 'Guadalupe', 'Apodaca', 'San Nicolás'],
  'Oaxaca': ['Oaxaca', 'Salina Cruz', 'Puerto Escondido', 'Huatulco'],
  'Puebla': ['Puebla', 'Tehuacán', 'Atlixco', 'Cholula'],
  'Querétaro': ['Querétaro', 'San Juan del Río', 'Corregidora'],
  'Quintana Roo': ['Cancún', 'Playa del Carmen', 'Tulum', 'Chetumal', 'Cozumel'],
  'San Luis Potosí': ['San Luis Potosí', 'Ciudad Valles', 'Matehuala'],
  'Sinaloa': ['Culiacán', 'Mazatlán', 'Los Mochis', 'Guasave'],
  'Sonora': ['Hermosillo', 'Ciudad Obregón', 'Nogales', 'Guaymas'],
  'Tabasco': ['Villahermosa', 'Cárdenas', 'Comalcalco'],
  'Tamaulipas': ['Tampico', 'Reynosa', 'Matamoros', 'Ciudad Victoria', 'Nuevo Laredo'],
  'Tlaxcala': ['Tlaxcala', 'Apizaco', 'Huamantla'],
  'Veracruz': ['Veracruz', 'Xalapa', 'Coatzacoalcos', 'Poza Rica', 'Boca del Río'],
  'Yucatán': ['Mérida', 'Valladolid', 'Progreso'],
  'Zacatecas': ['Zacatecas', 'Fresnillo', 'Guadalupe']
};

export const subcategoriesMap = {
  'coches': ['Compactos', 'SUV', 'Pickup', 'Sedán', 'Hatchback', 'Coupé', 'Deportivos', 'Clásicos', 'Eléctricos', 'Accesorios'],
  'motor': ['Motos', 'Scooters', 'Cuatrimotos', 'UTV', 'Motos de agua', 'Refacciones', 'Cascos', 'Equipamiento'],
  'inmobiliaria': ['Casas en venta', 'Casas en renta', 'Departamentos', 'Terrenos', 'Locales comerciales', 'Oficinas', 'Bodegas', 'Renta vacacional'],
  'empleo': ['Ventas', 'Chofer', 'Construcción', 'Administración', 'Atención al cliente', 'Tecnología', 'Hotelería', 'Medio tiempo'],
  'servicios': ['Mudanzas', 'Limpieza', 'Plomería', 'Electricidad', 'Cerrajería', 'Clases', 'Diseño', 'Eventos'],
  'moda': ['Ropa mujer', 'Ropa hombre', 'Calzado', 'Bolsos', 'Accesorios', 'Joyería', 'Cosmética'],
  'hogar': ['Muebles', 'Decoración', 'Electrodomésticos', 'Cocina', 'Jardín', 'Herramientas', 'Organización'],
  'electronica': ['Laptops', 'Tablets', 'TV y video', 'Audio', 'Cámaras', 'Drones', 'Accesorios'],
  'telefonos': ['Smartphones', 'Fundas y Carcasas', 'Smartwatches', 'Cargadores y Cables', 'Repuestos'],
  'deportes': ['Bicicletas', 'Gym', 'Running', 'Camping', 'Pesca', 'Surf', 'Kayak'],
  'infantil': ['Juguetes', 'Ropa infantil', 'Escolar', 'Muebles infantiles', 'Seguridad'],
  'bebes': ['Carriolas', 'Autoasientos', 'Ropa bebé', 'Baño y cuidado', 'Cunas', 'Juguetes bebé'],
  'mascotas': ['Perros', 'Gatos', 'Aves', 'Peces', 'Accesorios', 'Alimento', 'Veterinaria'],
  'negocios': ['Traspasos', 'Franquicias', 'Equipamiento', 'Maquinaria', 'Industria', 'Inversión'],
  'formacion': ['Libros', 'Cursos', 'Idiomas', 'Universidad', 'Infantil', 'Programación'],
  'informatica': ['PCs', 'Componentes', 'Monitores', 'Impresoras', 'Redes'],
  'coleccionismo': ['Arte', 'Antigüedades', 'Cómics', 'Monedas y Billetes', 'Música y Vinilos', 'Instrumentos musicales', 'Entradas']
};

export const mockAds = [
  { id: 1, title: 'MacBook Pro M2 2023 512GB', price: 25000, currency: 'MXN', location: 'Polanco, CDMX', category: 'informatica', image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=400&h=300', description: 'Computadora en perfecto estado, batería al 100%. Entrego con caja y accesorios originales.', type: 'particular', promoted: false },
  { id: 2, title: 'Hermoso Departamento con vista panorámica', price: 280000, currency: 'MXN', location: 'Querétaro, Querétaro', category: 'inmobiliaria', image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=400&h=300', description: 'Totalmente amueblado. Amenidades incluyen piscina, gimnasio y seguridad 24/7.', type: 'pro', promoted: 'destacado' },
  { id: 3, title: 'Honda Civic 2020 EX - Único dueño', price: 320000, currency: 'MXN', location: 'Monterrey, Nuevo León', category: 'motor', image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=400&h=300', description: 'Todos los mantenimientos en agencia. Listo para carretera.', type: 'particular', promoted: 'urgente' },
];

export const translations = {
  es: {
    home: 'Inicio', search: 'Buscar', post: 'Publicar', profile: 'Perfil', categories: 'Categorías', recent_ads: 'Nuevos Anuncios',
    search_placeholder: 'Buscar en mercasto.com', all_mexico: 'Todo México',
    post_title: 'Pon tu anuncio', 
    ad_title: 'Título del anuncio', ad_desc: 'Descripción detallada', ad_price: 'Precio', publish_btn: 'Publicar Ahora',
    destacado: 'Destacado', urgente: 'Urgente', free_ad: 'Gratis',
    motor: 'Motor', inmobiliaria: 'Inmuebles', empleo: 'Empleo', servicios: 'Servicios', informatica: 'Informática', telefonia: 'Telefonía', hogar: 'Hogar', moda: 'Moda', bebes: 'Bebés', mascotas: 'Mascotas', ocio: 'Ocio', boletos: 'Boletos',
    dashboard: 'Panel de Usuario', my_ads: 'Mis Anuncios', logout: 'Cerrar sesión', admin_panel: 'Panel de Admin',
    upgrade_pro: 'Conviértete en PRO', upgrade_pro_desc: 'Vende más rápido con herramientas para profesionales.', settings: 'Ajustes', favorites: 'Favoritos',
    tariffs: 'Tarifas', pricing_title: 'Planes de Tarifas', tab_individuals: 'Para Particulares', tab_businesses: 'Para Negocios',
    plan_free: 'Gratuito', plan_plus: 'Pack Plus', plan_pro_basic: 'PRO Estándar', plan_pro_max: 'PRO Ilimitado',
    buy_plan: 'Contratar', current_plan: 'Plan Actual', particular: 'Particular', company_profile: 'Perfil de Empresa', mass_upload: 'Subida masiva (XML/CSV)',
    delete_ad: 'Eliminar', confirm_delete: '¿Estás seguro de que deseas eliminar este anuncio?',
    views: 'vistas', leads: 'contactos', active_ads: 'Activos', total_views: 'Vistas', promote: 'Promocionar',
    login: "Iniciar Sesión", register: "Crear Cuenta", email: "Correo", password: "Contraseña", name: "Nombre",
    forgot_password: '¿Olvidaste tu contraseña?', send_link: 'Enviar Enlace', reset_password: 'Restablecer Contraseña', new_password: 'Nueva Contraseña',
    noAds: "NO HAY RESULTADOS", search_results: "RESULTADOS DE BÚSQUEDA",
    heroTitle: "COMPRA Y VENDE EN TODO MÉXICO",
    heroDesc: "Únete a Mercasto. Publica tu anuncio gratis en segundos de forma fácil y segura.",
    heroTag: "MERCADO LÍDER", heroAction: "PON TU ANUNCIO",
    card1: "COMPRA SEGURA", card2: "VENDE RÁPIDO", card3: "SOPORTE 24/7",
    cardDesc1: "Moderación activa y protección contra fraudes.",
    cardDesc2: "Miles de compradores visitan Mercasto buscando ofertas.",
    cardDesc3: "Estamos aquí para ayudarte en cada paso de tu venta.",
    back_to_list: 'Volver al listado', back: 'Volver',
    category_stats: 'Estadísticas de Categorías', personal_info: 'Información Personal', 
    update_photo: 'Actualiza tu foto de perfil...', edit_profile: 'Editar Perfil', security: 'Seguridad', 
    update_password: 'Actualiza tu contraseña...', curr_password: 'Contraseña actual',
    conf_password: 'Confirmar nueva contraseña', update_pass_btn: 'Actualizar Contraseña', email_settings: 'Correo Electrónico', 
    update_email: 'Actualiza la dirección...', new_email: 'Nuevo correo electrónico', req_change: 'Solicitar Cambio', 
    notifications: 'Notificaciones', choose_alerts: 'Elige qué tipo de alertas quieres...', email_alerts: 'Alertas por correo', 
    push_alerts: 'Notificaciones Push', marketing_alerts: 'Promociones y boletín', save_prefs: 'Guardar Preferencias', 
    interface: 'Interfaz', customize_app: 'Personaliza la apariencia...', autoplay: 'Autoplay en carrusel', danger_zone: 'Zona de Peligro',
    del_warning: 'Una vez que elimines tu cuenta perderás todo...', del_account: 'Eliminar Cuenta', export_json: 'Exportar JSON', 
    cover_photo: 'Foto de Portada', upload_cover: 'Subir portada', comp_name: 'Nombre de la Empresa', comp_desc: 'Descripción del Negocio',
    website: 'Sitio Web', phone: 'Teléfono de Contacto', address: 'Dirección Comercial', save_changes: 'Guardar Cambios',
    cat_tab: 'Categorías', users_tab: 'Usuarios', mod_tab: 'Moderación', coupons_tab: 'Cupones', reports_tab: 'Reportes', 
    add_cat: 'Añadir Nueva Categoría', edit_cat: 'Editar Categoría', slug: 'Slug (identificador único)', icon: 'Icono', 
    name_es: 'Nombre en Español', name_en: 'Nombre en Inglés', sort_order: 'Orden', save_cat: 'Guardar Categoría', cancel: 'Cancelar', 
    existing_cats: 'Categorías Existentes', pending_ads: 'Anuncios Pendientes', no_pending: 'No hay anuncios para moderar', 
    approve: 'Aprobar', reject: 'Rechazar', coupon_gen: 'Generador de Cupones', code: 'Código', credits: 'Créditos', 
    max_uses: 'Usos Máx.', create: 'Crear', no_coupons: 'No hay cupones activos', report_center: 'Centro de Reportes', 
    reported_ad: 'Anuncio', reason: 'Motivo', comments: 'Comentarios', reported_by: 'Reportado por', action: 'Acción', 
    no_reports: 'No hay reportes', reported_user: 'Usuario Reportado', user_mgmt: 'Gestión de Usuarios', search_users: 'Buscar nombre o email...',
    role: 'Rol', hidden_ip: 'IP oculta', no_users: 'No se encontraron usuarios', ad_photos: 'Fotos del anuncio', 
    drag_photos: 'Arrastra tus fotos aquí o', browse: 'explora', max_photos: 'Máximo 10 fotos', category: 'Categoría', 
    select: 'Seleccionar...', condition: 'Estado', new: 'Nuevo', used: 'Usado', location: 'Ubicación', loc_placeholder: 'Escribe tu ciudad...', 
    video_opt: 'Video (Opcional)', report_ad: 'Reportar este anuncio', verified_seller: 'Vendedor Verificado', id_confirmed: 'Identidad confirmada',
    show_qr: 'Mostrar QR de Contacto', similar_ads: 'Anuncios similares', client_reviews: 'Reseñas de clientes', leave_review: 'Deja tu opinión', 
    publish_review: 'Publicar reseña', no_reviews: 'Este vendedor aún no tiene reseñas', scan_qr: 'Escanear QR', report_seller: 'Reportar a este vendedor', 
    verified_id: 'Identidad verificada', high_rep: 'Alta reputación', product_desc: 'Descripción del producto', no_desc: 'El vendedor no ha proporcionado una descripción.',
    download_pdf: 'Descargar Ficha PDF', contacts_qr: 'Contactos (QR)', conversion: 'Conversión',
    share_whatsapp: 'Compartir por WhatsApp', check_this_ad: '¡Mira este anuncio en Mercasto!',
    all: 'Todo', language: 'Idioma', state: 'Estado', city: 'Ciudad / Municipio', all_cities: 'Todas las ciudades', apply: 'Aplicar',
    search_btn: 'Buscar', search_placeholder_short: 'Buscar producto...', guest: 'Invitado', post_ad: 'Publicar',
    mark_all_read: 'Marcar todas leídas', no_notifications: 'No tienes notificaciones',
    footer_desc: 'El marketplace local de más rápido crecimiento en México. Compra, vende, renta y encuentra empleo de forma segura.',
    buyers: 'Compradores', how_to_buy: 'Cómo comprar', safety_tips: 'Consejos de seguridad',
    sellers: 'Vendedores', pricing: 'Precios', promote_ad: 'Promocionar anuncio',
    business: 'Negocios', partners: 'Socios', help: 'Ayuda', help_center: 'Centro de Ayuda',
    safety_center: 'Centro de Seguridad', privacy_policy: 'Aviso de Privacidad',
    active_listings: 'anuncios activos', users_online: 'usuarios en línea', sell_fast: 'Vender rápido',
    find_job: 'Buscar empleo', rent_apt: 'Rentar depa', hire_service: 'Contratar servicio',
    browse_category: 'Explorar por categoría', sort_popular: 'Ordenar: Popular', show_less: 'Ver menos',
    view_all_cat: 'Ver todas las categorías →', trending_now: 'Tendencias', save_search: 'Guardar búsqueda',
    filter: 'Filtros', see_all: 'Ver todo →', deal_of_day: 'Oferta del día', up_to_40: 'Hasta 40% OFF',
    elec_phones: 'Electrónica y Celulares', shop_now: 'Comprar ahora →', ends_in_8h: 'Termina en 8h',
    furniture: 'Muebles', living_room_sets: 'Salas de estar', from_price: 'Desde $4,999 MXN',
    see_deals: 'Ver ofertas →', automotive: 'Automotriz', certified_cars: 'Autos Certificados',
    zero_comm: '0% comisión esta semana', browse_cars: 'Explorar 124k →', for_sellers: 'Para vendedores',
    boost_ad: 'Destaca tu anuncio', boost_desc: '3x más vistas, mejor posición', promote_now: 'Promocionar ahora →',
    re_spotlight: 'Inmuebles Destacados', rent: 'Rentar', buy: 'Comprar', commercial: 'Comercial',
    view_props: 'Ver propiedades →', open_map: 'Abrir mapa', view_all_mexico: 'Ver todo México',
    jobs_board: 'Bolsa de trabajo', remote_only: 'Solo remoto', full_time: 'Tiempo completo',
    company: 'Empresa', salary_mxn: 'Salario MXN', showing_jobs: 'Mostrando empleos nuevos',
    upload_cv: 'Subir CV', create_job_alert: 'Crear alerta', services_marketplace: 'Directorio de servicios',
    browse_services: 'Ver todos →', from: 'Desde', book_now: 'Reservar', year: 'Año', price: 'Precio',
    recently_viewed: 'Vistos recientemente', clear_history: 'Borrar historial',
    starter_desc: 'Ideal para ventas ocasionales', basic_stats: 'Estadísticas básicas',
    contacto_qr: 'Contacto vía QR', pro_desc: 'Para vendedores recurrentes', unlimited_ads: 'Anuncios ilimitados',
    boost_credits: 'Créditos mensuales', advanced_stats: 'Estadísticas PRO', verified_badge: 'Insignia Verificada',
    enterprise: 'Enterprise', enterprise_desc: 'Inmobiliarias, agencias...', bulk_import: 'Importación masiva',
    account_manager: 'Soporte dedicado', storefront: 'Página de Tienda', contact_sales: 'Contactar ventas',
    how_it_works: 'Cómo funciona Mercasto', post_60s: 'Publica en 60s',
    post_60s_desc: 'Fotos, precio, ubicación. La IA hace el resto.',
    get_leads: 'Recibe contactos', get_leads_desc: 'Llamadas, WhatsApp o escaneo QR seguro.',
    meet_safely: 'Encuentros seguros', meet_safely_desc: 'Perfiles verificados (KYC) para tu paz mental.',
    sell_faster: 'Vende rápido', sell_faster_desc: 'Destaca tu anuncio y cierra el trato hoy.',
    avoid_scams: 'Evita fraudes', avoid_scams_desc: 'Nunca pagues por adelantado. Revisa las insignias.',
    learn_more: 'Saber más', safe_payments: 'Pagos seguros',
    safe_payments_desc: 'Reúnete en público. Cuenta el dinero antes de irte.',
    verified_sellers: 'Vendedores verificados',
    verified_sellers_desc: 'Busca la insignia azul de identidad confirmada (KYC).',
    popular_searches: 'Búsquedas populares', updated_hourly: 'Actualizado hace 1h',
    explore_city: 'Explorar por ciudad', app_title: 'Mercasto en tu teléfono. Compra y vende más rápido.',
    app_desc: 'Recibe alertas instantáneas, gestiona todo desde tu móvil y comunícate seguro.',
    cam_autofill: 'Publicación rápida con cámara IA',
    safe_qr: 'Contacto seguro con código QR', free_no_ads: 'Gratis • Sin anuncios en PRO',
    newsletter_title: 'Recibe las mejores ofertas de México',
    newsletter_desc: 'Resumen semanal de ofertas, caída de precios y nuevos empleos.',
    your_email: 'Tu correo electrónico', subscribe: 'Suscribirse',
    transactions_tab: 'Transacciones',
    credits_btn_title: 'Comprar créditos',
    credits_unit: 'Créditos',
    redeem_coupon: 'Canjear cupón',
    transactions_title: 'Historial de Transacciones',
    transactions_desc: 'Consulta el registro de tus compras de créditos, promociones y recargas en Mercasto.',
    refresh_btn: 'Actualizar',
    no_transactions: 'Sin transacciones registradas',
    no_transactions_desc: 'Aún no has realizado ninguna compra de créditos. Puedes recargar saldo para destacar tus anuncios o acceder a funciones PRO.',
    buy_credits_offer: 'Comprar 100 Créditos ($100 MXN)',
    concept: 'Concepto',
    clip_ref: 'Referencia de pago',
    date: 'Fecha',
    amount: 'Monto',
    status: 'Estado',
    payment_service_fallback: 'Compra de Servicios',
    click_to_select: 'Click para seleccionar',
    payment_status_approved: 'Aprobado',
    payment_status_pending: 'Pendiente',
    payment_status_failed: 'Fallido',
    page_word: 'Página',
    of_word: 'de',
    total_word: 'total',
    prev_btn: 'Anterior',
    next_btn: 'Siguiente',
    uploading_word: 'Subiendo...',
    referrals_tab: 'Referidos',
    payment_error_generating: 'Error al generar el pago',
    payment_failed_or_canceled: 'El pago no se pudo completar o fue cancelado.',
    connection_error: 'Error de conexión',
    ad_promotion_description: 'Promoción de anuncio',
    plus_subscription_description: 'Suscripción Paquete Plus',
    pro_basic_subscription_description: 'Suscripción PRO Estándar',
    pro_max_subscription_description: 'Suscripción PRO Ilimitado',
    admin_payments_tab: 'Pagos',
    admin_transactions_registered: 'Transacciones Registradas',
    admin_volume_desc: 'Volumen total de transacciones de pago',
    admin_approved_revenue: 'Ingresos Aprobados (Pág. Actual)',
    admin_approved_revenue_desc: 'Monto de pagos exitosos mostrados',
    admin_payments_audit: 'Auditoría de Pagos',
    admin_payments_audit_desc: 'Monitorea y valida las transacciones procesadas a través de la pasarela de pagos.',
    admin_no_payments: 'Sin pagos registrados',
    admin_no_payments_desc: 'No se encontraron transacciones en el historial del sistema. Todos los pagos iniciados aparecerán aquí.',
    admin_user: 'Usuario',
    admin_user_id: 'Usuario ID:',
    admin_email_not_available: 'Email no disponible',
    admin_services_fallback: 'Servicios Mercasto',
    admin_click_to_select_all: 'Click para seleccionar todo',

    // General UI
    close_btn: 'Cerrar',
    edit: 'Editar',
    delete: 'Eliminar',
    view: 'Ver',
    pause: 'Pausar',
    reactivate: 'Reactivar',
    republish: 'Republicar',
    selected: 'seleccionados',
    generating: 'Generando...',
    generate_ai: '✨ Generar con IA',

    // Cookie Banner
    cookies_aria_label: 'Aviso de cookies',
    cookies_title: 'Usamos cookies para mejorar tu experiencia.',
    cookies_desc: 'Algunas son esenciales; otras nos ayudan a entender cómo usas Mercasto.',
    cookies_essential: 'Solo esenciales',
    cookies_accept_all: 'Aceptar todas',

    // Onboarding Modal
    onboarding_welcome_title: '¡Bienvenido a Mercasto!',
    onboarding_welcome_subtitle: 'El marketplace de confianza para México',
    onboarding_welcome_desc: 'Compra, vende y renta en todo México. Miles de productos y servicios cerca de ti.',
    onboarding_how_title: '¿Cómo funciona?',
    onboarding_how_subtitle: 'En 3 simples pasos',
    onboarding_step1_label: 'Publica gratis',
    onboarding_step1_desc: 'Sube fotos y describe lo que vendes en minutos',
    onboarding_step2_label: 'Chatea con compradores',
    onboarding_step2_desc: 'Recibe mensajes y negocia de forma segura',
    onboarding_step3_label: 'Vende seguro',
    onboarding_step3_desc: 'Coordina la entrega y recibe tu pago',
    onboarding_profile_title: 'Completa tu perfil',
    onboarding_profile_subtitle: 'Los vendedores verificados venden 3× más rápido',
    onboarding_checklist_desc: 'Completa estos pasos para generar más confianza con los compradores:',
    onboarding_checklist_photo: 'Agrega una foto de perfil',
    onboarding_checklist_phone: 'Verifica tu teléfono',
    onboarding_checklist_bio: 'Escribe una descripción',
    onboarding_complete_btn: 'Completar perfil',
    onboarding_skip_btn: 'Omitir por ahora',

    // Referral Program
    referral_title: 'Programa de Referidos',
    referral_desc: 'Invita a tus amigos a Mercasto y ambos ganarán créditos cuando publiquen su primer anuncio.',
    referral_link: 'Tu enlace de referido',
    copied: '¡Copiado!',
    copy: 'Copiar',
    referral_friends: 'Amigos invitados',
    referral_credits: 'Créditos ganados',
    referral_history: 'Historial de referidos',
    referral_empty: 'Aún no has invitado a ningún amigo. ¡Comparte tu enlace para comenzar a ganar!',
    credit: 'Crédito',

    // Ad Management (Post & Edit Screens)
    edit_ad: 'Editar anuncio',
    add_more_photos: 'Agregar más fotos',
    drag_photos_hint: 'Arrastra tus fotos aquí o',
    browse_label: 'explora',
    max_photos_hint: 'Máximo 10 fotos (JPG, PNG)',
    select_state: 'Seleccionar estado',
    video_hint: 'Video (Opcional, MP4, max 50MB)',
    ad_attributes: 'Características del anuncio',

    // Storefront Screen
    rfc_verified: 'RFC verificado',
    business_profile_tag: 'Perfil de negocio',
    closed_hours: 'Cerrado',
    check_hours: 'Consultar horario',
    seller_role: 'Vendedor',
    review_placeholder: '¿Cómo fue tu experiencia con este vendedor?',

    // MyAdsScreen & extra keys
    all_filter: 'Todos',
    active_status: 'Activos',
    paused_status: 'Pausados',
    expired_status: 'Expirados',
    featured_status: 'Destacados',
    select_all: 'Seleccionar todo',
    ads_updated: 'anuncios actualizados',
    reviews_count: 'reseñas',
    ad_rejected: 'Este anuncio fue rechazado',
    ad_rejected_edit_desc: 'Edítalo y se enviará a revisión nuevamente.',
    add_photo: 'Agregar foto',
    back_to_ad: 'Volver al anuncio',
    complete_business_profile: 'Completa tu perfil de empresa',
    complete_business_profile_hint: 'Agrega los datos de tu negocio para vender como PRO',
    drag_reorder: 'arrastra para reordenar',
    edit_ad_review_desc: 'Los cambios importantes se enviarán a revisión',
    error_loading_ad: 'No se pudo cargar el anuncio',
    first_img_main_hint: 'La primera imagen será la foto principal del anuncio',
    max_images_alert: 'Máximo 10 imágenes por anuncio',
    referral_error: 'No pudimos cargar tu enlace de referido. Inténtalo de nuevo.',
    referral_load_error: 'No se pudo cargar el programa de referidos',
    save_changes_error: 'Error al guardar los cambios',
    saving_word: 'Guardando',
    select_category: 'Seleccionar categoría'
  },
  en: {
    home: 'Home', search: 'Search', post: 'Post Ad', profile: 'Profile', categories: 'Categories', recent_ads: 'Recent Ads',
    search_placeholder: 'Search on mercasto.com', all_mexico: 'All Mexico',
    post_title: 'Post your ad', 
    ad_title: 'Ad Title', ad_desc: 'Detailed Description', ad_price: 'Price', publish_btn: 'Publish Now',
    destacado: 'Featured', urgente: 'Urgent', free_ad: 'Free',
    motor: 'Motors', inmobiliaria: 'Real Estate', empleo: 'Jobs', servicios: 'Services', informatica: 'Computers', telefonia: 'Phones', hogar: 'Home', moda: 'Fashion', bebes: 'Babies', mascotas: 'Pets', ocio: 'Hobbies', boletos: 'Tickets',
    dashboard: 'Dashboard', my_ads: 'My Ads', logout: 'Logout', admin_panel: 'Admin Panel',
    upgrade_pro: 'Upgrade to PRO', upgrade_pro_desc: 'Sell faster with professional tools.', settings: 'Settings', favorites: 'Favorites',
    tariffs: 'Pricing', pricing_title: 'Pricing Plans', tab_individuals: 'For Individuals', tab_businesses: 'For Businesses',
    plan_free: 'Free', plan_plus: 'Plus Pack', plan_pro_basic: 'PRO Standard', plan_pro_max: 'PRO Unlimited',
    buy_plan: 'Subscribe', current_plan: 'Current Plan', particular: 'Individual', company_profile: 'Company Profile', mass_upload: 'Mass Upload (XML/CSV)',
    delete_ad: 'Delete', confirm_delete: 'Are you sure you want to delete this ad?',
    views: 'views', leads: 'leads', active_ads: 'Active', total_views: 'Views', promote: 'Promote',
    login: "Login", register: "Register", email: "Email", password: "Password", name: "Name",
    forgot_password: 'Forgot Password?', send_link: 'Send Link', reset_password: 'Reset Password', new_password: 'New Password',
    noAds: "NO RESULTS FOUND", search_results: "SEARCH RESULTS",
    heroTitle: "BUY AND SELL ACROSS MEXICO",
    heroDesc: "Join Mercasto. Post your ad for free in seconds easily and securely.",
    heroTag: "LEADING MARKET", heroAction: "POST AN AD",
    card1: "SECURE BUYING", card2: "FAST SELLING", card3: "24/7 SUPPORT",
    cardDesc1: "Active moderation and fraud protection.",
    cardDesc2: "Thousands of buyers visit Mercasto daily.",
    cardDesc3: "We are here to help you every step of the way.",
    back_to_list: 'Back to list', back: 'Back', category_stats: 'Category Statistics', personal_info: 'Personal Information', 
    update_photo: 'Update your profile photo...', edit_profile: 'Edit Profile', security: 'Security', update_password: 'Update your password...', 
    curr_password: 'Current password', conf_password: 'Confirm new password', update_pass_btn: 'Update Password',
    email_settings: 'Email Settings', update_email: 'Update your email...', new_email: 'New email address', req_change: 'Request Change', 
    notifications: 'Notifications', choose_alerts: 'Choose what alerts to receive...', email_alerts: 'Email alerts', push_alerts: 'Push notifications', 
    marketing_alerts: 'Promotions and newsletter', save_prefs: 'Save Preferences', interface: 'Interface', customize_app: 'Customize appearance...', 
    autoplay: 'Carousel autoplay', danger_zone: 'Danger Zone', del_warning: 'Once you delete your account...', del_account: 'Delete Account', 
    export_json: 'Export JSON', cover_photo: 'Cover Photo', upload_cover: 'Upload cover', comp_name: 'Company Name', comp_desc: 'Business Description', 
    website: 'Website', phone: 'Contact Phone', address: 'Business Address', save_changes: 'Save Changes', cat_tab: 'Categories', 
    users_tab: 'Users', mod_tab: 'Moderation', coupons_tab: 'Coupons', reports_tab: 'Reports', add_cat: 'Add New Category', 
    edit_cat: 'Edit Category', slug: 'Slug (unique identifier)', icon: 'Icon', name_es: 'Spanish Name', name_en: 'English Name', 
    sort_order: 'Order', save_cat: 'Save Category', cancel: 'Cancel', existing_cats: 'Existing Categories', pending_ads: 'Pending Ads', 
    no_pending: 'No ads to moderate', approve: 'Approve', reject: 'Reject', coupon_gen: 'Coupon Generator', code: 'Code', 
    credits: 'Credits', max_uses: 'Max Uses', create: 'Create', no_coupons: 'No active coupons', report_center: 'Report Center', 
    reported_ad: 'Ad', reason: 'Reason', comments: 'Comments', reported_by: 'Reported by', action: 'Action', no_reports: 'No reports', 
    reported_user: 'Reported User', user_mgmt: 'User Management', search_users: 'Search name or email...', role: 'Role', hidden_ip: 'Hidden IP', 
    no_users: 'No users found', ad_photos: 'Ad Photos', drag_photos: 'Drag your photos here or', browse: 'browse', max_photos: 'Max 10 photos', 
    category: 'Category', select: 'Select...', condition: 'Condition', new: 'New', used: 'Used', location: 'Location', 
    loc_placeholder: 'Type your city...', video_opt: 'Video (Optional)', report_ad: 'Report this ad', verified_seller: 'Verified Seller', 
    id_confirmed: 'Identity confirmed', show_qr: 'Show Contact QR', similar_ads: 'Similar ads', client_reviews: 'Customer reviews', 
    leave_review: 'Leave your review', publish_review: 'Publish review', no_reviews: 'This seller has no reviews yet', scan_qr: 'Scan QR', 
    report_seller: 'Report this seller', verified_id: 'Verified identity', high_rep: 'High reputation', product_desc: 'Product Description', 
    no_desc: 'The seller did not provide a description.', download_pdf: 'Download PDF Brochure', contacts_qr: 'Contacts (QR)', conversion: 'Conversion',
    share_whatsapp: 'Share on WhatsApp', check_this_ad: 'Check this listing on Mercasto!',
    all: 'All', language: 'Language', state: 'State', city: 'City / Municipality', all_cities: 'All cities', apply: 'Apply',
    search_btn: 'Search', search_placeholder_short: 'Search product...', guest: 'Guest', post_ad: 'Post',
    mark_all_read: 'Mark all read', no_notifications: 'You have no notifications',
    footer_desc: 'Mexico’s fast-growing local marketplace. Buy, sell, rent and find work safely.',
    buyers: 'Buyers', how_to_buy: 'How to buy', safety_tips: 'Safety tips',
    sellers: 'Sellers', pricing: 'Pricing', promote_ad: 'Promote listing',
    business: 'Business', partners: 'Partners', help: 'Help', help_center: 'Help Center',
    safety_center: 'Safety Center', privacy_policy: 'Privacy Notice',
    active_listings: 'active listings', users_online: 'users online', sell_fast: 'Sell fast',
    find_job: 'Find a job', rent_apt: 'Rent apartment', hire_service: 'Hire service',
    browse_category: 'Explore by category', sort_popular: 'Sort: Popular', show_less: 'Show less',
    view_all_cat: 'See all categories →', trending_now: 'Trending', save_search: 'Save search',
    filter: 'Filters', see_all: 'See all →', deal_of_day: 'Deal of the day', up_to_40: 'Up to 40% OFF',
    elec_phones: 'Electronics and Phones', shop_now: 'Shop now →', ends_in_8h: 'Ends in 8h',
    furniture: 'Furniture', living_room_sets: 'Living room sets', from_price: 'From $4,999 MXN',
    see_deals: 'See deals →', automotive: 'Automotive', certified_cars: 'Certified Cars',
    zero_comm: '0% commission this week', browse_cars: 'Explore 124k →', for_sellers: 'For sellers',
    boost_ad: 'Boost your listing', boost_desc: '3x more views, better placement', promote_now: 'Promote now →',
    re_spotlight: 'Featured Real Estate', rent: 'Rent', buy: 'Buy', commercial: 'Commercial',
    view_props: 'View properties →', open_map: 'Open map', view_all_mexico: 'View all Mexico',
    jobs_board: 'Jobs board', remote_only: 'Remote only', full_time: 'Full-time',
    company: 'Company', salary_mxn: 'Salary MXN', showing_jobs: 'Showing new jobs',
    upload_cv: 'Upload CV', create_job_alert: 'Create alert', services_marketplace: 'Services directory',
    browse_services: 'See all →', from: 'From', book_now: 'Book now', year: 'Year', price: 'Price',
    recently_viewed: 'Recently viewed', clear_history: 'Clear history',
    starter_desc: 'Ideal for occasional sales', basic_stats: 'Basic stats',
    contacto_qr: 'QR contact', pro_desc: 'For repeat sellers', unlimited_ads: 'Unlimited listings',
    boost_credits: 'Monthly credits', advanced_stats: 'PRO analytics', verified_badge: 'Verified badge',
    enterprise: 'Enterprise', enterprise_desc: 'Real estate firms, agencies...', bulk_import: 'Bulk import',
    account_manager: 'Dedicated support', storefront: 'Storefront page', contact_sales: 'Contact sales',
    how_it_works: 'How Mercasto works', post_60s: 'Post in 60s',
    post_60s_desc: 'Photos, price, location. AI helps with the rest.',
    get_leads: 'Get leads', get_leads_desc: 'Calls, WhatsApp or secure QR scan.',
    meet_safely: 'Meet safely', meet_safely_desc: 'Verified profiles (KYC) for peace of mind.',
    sell_faster: 'Sell faster', sell_faster_desc: 'Feature your listing and close the deal today.',
    avoid_scams: 'Avoid scams', avoid_scams_desc: 'Never pay in advance. Check the badges.',
    learn_more: 'Learn more', safe_payments: 'Safe payments',
    safe_payments_desc: 'Meet in public. Count the cash before leaving.',
    verified_sellers: 'Verified sellers',
    verified_sellers_desc: 'Look for the blue identity-confirmed badge (KYC).',
    popular_searches: 'Popular searches', updated_hourly: 'Updated 1h ago',
    explore_city: 'Explore by city', app_title: 'Mercasto on your phone. Buy and sell faster.',
    app_desc: 'Get instant alerts, manage everything from mobile and communicate safely.',
    cam_autofill: 'Fast posting with AI camera',
    safe_qr: 'Secure contact with QR code', free_no_ads: 'Free • No ads in PRO',
    newsletter_title: 'Get Mexico’s best deals',
    newsletter_desc: 'Weekly digest of deals, price drops and new jobs.',
    your_email: 'Your email address', subscribe: 'Subscribe',
    transactions_tab: 'Transactions',
    credits_btn_title: 'Buy credits',
    credits_unit: 'Credits',
    redeem_coupon: 'Redeem coupon',
    transactions_title: 'Transaction History',
    transactions_desc: 'View the log of your credit purchases, promotions and top-ups on Mercasto.',
    refresh_btn: 'Refresh',
    no_transactions: 'No transactions recorded',
    no_transactions_desc: 'You haven\'t made any credit purchases yet. You can top up your balance to feature your ads or access PRO features.',
    buy_credits_offer: 'Buy 100 Credits ($100 MXN)',
    concept: 'Concept',
    clip_ref: 'Payment reference',
    date: 'Date',
    amount: 'Amount',
    status: 'Status',
    payment_service_fallback: 'Service Purchase',
    click_to_select: 'Click to select',
    payment_status_approved: 'Approved',
    payment_status_pending: 'Pending',
    payment_status_failed: 'Failed',
    page_word: 'Page',
    of_word: 'of',
    total_word: 'total',
    prev_btn: 'Previous',
    next_btn: 'Next',
    uploading_word: 'Uploading...',
    referrals_tab: 'Referrals',
    payment_error_generating: 'Error generating payment',
    payment_failed_or_canceled: 'The payment could not be completed or was canceled.',
    connection_error: 'Connection error',
    ad_promotion_description: 'Ad promotion',
    plus_subscription_description: 'Plus Pack Subscription',
    pro_basic_subscription_description: 'PRO Standard Subscription',
    pro_max_subscription_description: 'PRO Unlimited Subscription',
    admin_payments_tab: 'Payments',
    admin_transactions_registered: 'Registered Transactions',
    admin_volume_desc: 'Total payment transaction volume',
    admin_approved_revenue: 'Approved Revenue (Current Page)',
    admin_approved_revenue_desc: 'Amount of successful payments shown',
    admin_payments_audit: 'Payments Audit',
    admin_payments_audit_desc: 'Monitor and validate transactions processed through the payment gateway.',
    admin_no_payments: 'No payments registered',
    admin_no_payments_desc: 'No transactions were found in the system history. All initiated payments will appear here.',
    admin_user: 'User',
    admin_user_id: 'User ID:',
    admin_email_not_available: 'Email not available',
    admin_services_fallback: 'Mercasto Services',
    admin_click_to_select_all: 'Click to select all',

    // General UI
    close_btn: 'Close',
    edit: 'Edit',
    delete: 'Delete',
    view: 'View',
    pause: 'Pause',
    reactivate: 'Reactivate',
    republish: 'Republish',
    selected: 'selected',
    generating: 'Generating...',
    generate_ai: '✨ Generate with AI',

    // Cookie Banner
    cookies_aria_label: 'Cookie Notice',
    cookies_title: 'We use cookies to improve your experience.',
    cookies_desc: 'Some are essential; others help us understand how you use Mercasto.',
    cookies_essential: 'Only essential',
    cookies_accept_all: 'Accept all',

    // Onboarding Modal
    onboarding_welcome_title: 'Welcome to Mercasto!',
    onboarding_welcome_subtitle: 'Mexico’s trusted marketplace',
    onboarding_welcome_desc: 'Buy, sell, and rent across Mexico. Thousands of products and services near you.',
    onboarding_how_title: 'How it works?',
    onboarding_how_subtitle: 'In 3 simple steps',
    onboarding_step1_label: 'Post for free',
    onboarding_step1_desc: 'Upload photos and describe what you sell in minutes',
    onboarding_step2_label: 'Chat with buyers',
    onboarding_step2_desc: 'Receive messages and negotiate securely',
    onboarding_step3_label: 'Sell safely',
    onboarding_step3_desc: 'Coordinate delivery and receive your payment',
    onboarding_profile_title: 'Complete your profile',
    onboarding_profile_subtitle: 'Verified sellers sell 3× faster',
    onboarding_checklist_desc: 'Complete these steps to build more trust with buyers:',
    onboarding_checklist_photo: 'Add a profile photo',
    onboarding_checklist_phone: 'Verify your phone number',
    onboarding_checklist_bio: 'Write a bio description',
    onboarding_complete_btn: 'Complete profile',
    onboarding_skip_btn: 'Skip for now',

    // Referral Program
    referral_title: 'Referral Program',
    referral_desc: 'Invite your friends to Mercasto and you will both earn credits when they post their first ad.',
    referral_link: 'Your referral link',
    copied: 'Copied!',
    copy: 'Copy',
    referral_friends: 'Invited friends',
    referral_credits: 'Credits earned',
    referral_history: 'Referral history',
    referral_empty: 'You haven\'t invited any friends yet. Share your link to start earning!',
    credit: 'Credit',

    // Ad Management (Post & Edit Screens)
    edit_ad: 'Edit ad',
    add_more_photos: 'Add more photos',
    drag_photos_hint: 'Drag your photos here or',
    browse_label: 'browse',
    max_photos_hint: 'Maximum 10 photos (JPG, PNG)',
    select_state: 'Select state',
    video_hint: 'Video (Optional, MP4, max 50MB)',
    ad_attributes: 'Ad attributes',

    // Storefront Screen
    rfc_verified: 'RFC verified',
    business_profile_tag: 'Business Profile',
    closed_hours: 'Closed',
    check_hours: 'Check hours',
    seller_role: 'Seller',
    review_placeholder: 'How was your experience with this seller?',

    // MyAdsScreen & extra keys
    all_filter: 'All',
    active_status: 'Active',
    paused_status: 'Paused',
    expired_status: 'Expired',
    featured_status: 'Featured',
    select_all: 'Select all',
    ads_updated: 'ads updated',
    reviews_count: 'reviews',
    ad_rejected: 'This ad was rejected',
    ad_rejected_edit_desc: 'Edit it and it will be sent for review again.',
    add_photo: 'Add photo',
    back_to_ad: 'Back to ad',
    complete_business_profile: 'Complete your company profile',
    complete_business_profile_hint: 'Add your business details to sell like a PRO',
    drag_reorder: 'drag to reorder',
    edit_ad_review_desc: 'Important changes will be sent for review',
    error_loading_ad: 'Could not load the listing',
    first_img_main_hint: "The first image will be the listing's main photo",
    max_images_alert: 'Maximum 10 images per listing',
    referral_error: "We couldn't load your referral link. Please try again.",
    referral_load_error: 'Could not load the referral program',
    save_changes_error: 'Error saving changes',
    saving_word: 'Saving',
    select_category: 'Select category'
  },
  pt: {
    home: 'Início', search: 'Pesquisar', post: 'Publicar Anúncio', profile: 'Perfil', categories: 'Categorias', recent_ads: 'Anúncios Recentes',
    search_placeholder: 'Pesquisar no mercasto.com', all_mexico: 'Todo o México',
    post_title: 'Publique seu anúncio', 
    ad_title: 'Título do anúncio', ad_desc: 'Descrição detalhada', ad_price: 'Preço', publish_btn: 'Publicar Agora',
    destacado: 'Destaque', urgente: 'Urgente', free_ad: 'Grátis',
    motor: 'Motores', inmobiliaria: 'Imóveis', empleo: 'Emprego', servicios: 'Serviços', informatica: 'Informática', telefonia: 'Celulares', hogar: 'Casa', moda: 'Moda', bebes: 'Bebês', mascotas: 'Pets', ocio: 'Lazer', boletos: 'Ingressos',
    dashboard: 'Painel', my_ads: 'Meus Anúncios', logout: 'Sair', admin_panel: 'Painel Admin',
    upgrade_pro: 'Seja PRO', upgrade_pro_desc: 'Venda mais rápido com ferramentas profissionais.', settings: 'Configurações', favorites: 'Favoritos',
    tariffs: 'Tarifas', pricing_title: 'Planos de Preços', tab_individuals: 'Para Pessoas', tab_businesses: 'Para Empresas',
    plan_free: 'Grátis', plan_plus: 'Pacote Plus', plan_pro_basic: 'PRO Padrão', plan_pro_max: 'PRO Ilimitado',
    buy_plan: 'Assinar', current_plan: 'Plano Atual', particular: 'Particular', company_profile: 'Perfil da Empresa', mass_upload: 'Upload em Massa (XML/CSV)',
    delete_ad: 'Excluir', confirm_delete: 'Tem certeza de que deseja excluir este anúncio?',
    views: 'visualizações', leads: 'contatos', active_ads: 'Ativos', total_views: 'Visualizações', promote: 'Promover',
    login: "Entrar", register: "Criar Conta", email: "E-mail", password: "Senha", name: "Nome",
    forgot_password: 'Esqueceu a senha?', send_link: 'Enviar Link', reset_password: 'Redefinir Senha', new_password: 'Nova Senha',
    noAds: "NENHUM RESULTADO ENCONTRADO", search_results: "RESULTADOS DA PESQUISA",
    heroTitle: "COMPRE E VENDA EM TODO O MÉXICO",
    heroDesc: "Junte-se ao Mercasto. Publique seu anúncio grátis em segundos, de forma fácil e segura.",
    heroTag: "MERCADO LÍDER", heroAction: "PUBLIQUE UM ANÚNCIO",
    card1: "COMPRA SEGURA", card2: "VENDA RÁPIDO", card3: "SUPORTE 24/7",
    cardDesc1: "Moderação ativa e proteção contra fraudes.",
    cardDesc2: "Milhares de compradores visitam o Mercasto diariamente.",
    cardDesc3: "Estamos aqui para ajudar em cada etapa.",
    back_to_list: 'Voltar à lista', back: 'Voltar', category_stats: 'Estatísticas de Categoria', personal_info: 'Informação Pessoal', 
    update_photo: 'Atualize sua foto de perfil...', edit_profile: 'Editar Perfil', security: 'Segurança', update_password: 'Atualize sua senha...', 
    curr_password: 'Senha atual', conf_password: 'Confirmar nova senha', update_pass_btn: 'Atualizar Senha',
    email_settings: 'Configurações de E-mail', update_email: 'Atualize seu e-mail...', new_email: 'Novo e-mail', req_change: 'Solicitar Mudança', 
    notifications: 'Notificações', choose_alerts: 'Escolha quais alertas receber...', email_alerts: 'Alertas por e-mail', push_alerts: 'Notificações Push', 
    marketing_alerts: 'Promoções e newsletter', save_prefs: 'Salvar Preferências', interface: 'Interface', customize_app: 'Personalizar aparência...', 
    autoplay: 'Autoplay do carrossel', danger_zone: 'Zona de Perigo', del_warning: 'Depois de excluir sua conta...', del_account: 'Excluir Conta', 
    export_json: 'Exportar JSON', cover_photo: 'Foto de Capa', upload_cover: 'Enviar capa', comp_name: 'Nome da Empresa', comp_desc: 'Descrição do Negócio', 
    website: 'Site', phone: 'Telefone de Contato', address: 'Endereço Comercial', save_changes: 'Salvar Alterações', cat_tab: 'Categorias', 
    users_tab: 'Usuários', mod_tab: 'Moderação', coupons_tab: 'Cupons', reports_tab: 'Denúncias', add_cat: 'Adicionar Categoria', 
    edit_cat: 'Editar Categoria', slug: 'Slug (identificador)', icon: 'Ícone', name_es: 'Nome em Espanhol', name_en: 'Nome em Inglês', 
    sort_order: 'Ordem', save_cat: 'Salvar Categoria', cancel: 'Cancelar', existing_cats: 'Categorias Existentes', pending_ads: 'Anúncios Pendentes', 
    no_pending: 'Sem anúncios para moderar', approve: 'Aprovar', reject: 'Rejeitar', coupon_gen: 'Gerador de Cupons', code: 'Código', 
    credits: 'Créditos', max_uses: 'Usos Máx.', create: 'Criar', no_coupons: 'Nenhum cupom ativo', report_center: 'Central de Denúncias', 
    reported_ad: 'Anúncio', reason: 'Motivo', comments: 'Comentários', reported_by: 'Denunciado por', action: 'Ação', no_reports: 'Nenhuma denúncia', 
    reported_user: 'Usuário Denunciado', user_mgmt: 'Gestão de Usuários', search_users: 'Buscar nome ou e-mail...', role: 'Cargo', hidden_ip: 'IP Oculto', 
    no_users: 'Nenhum usuário encontrado', ad_photos: 'Fotos do anúncio', drag_photos: 'Arraste suas fotos ou', browse: 'procurar', max_photos: 'Máx 10 fotos', 
    category: 'Categoria', select: 'Selecionar...', condition: 'Condição', new: 'Novo', used: 'Usado', location: 'Localização', 
    loc_placeholder: 'Digite sua cidade...', video_opt: 'Vídeo (Opcional)', report_ad: 'Denunciar este anúncio', verified_seller: 'Vendedor Verificado', 
    id_confirmed: 'Identidade confirmada', show_qr: 'Mostrar QR de Contato', similar_ads: 'Anúncios similares', client_reviews: 'Avaliações de clientes', 
    leave_review: 'Deixe sua opinião', publish_review: 'Publicar avaliação', no_reviews: 'Este vendedor não tem avaliações', scan_qr: 'Escanear QR', 
    report_seller: 'Denunciar vendedor', verified_id: 'Identidade verificada', high_rep: 'Alta reputação', product_desc: 'Descrição do produto', 
    no_desc: 'O vendedor não forneceu uma descrição.', download_pdf: 'Baixar Folheto PDF', contacts_qr: 'Contatos (QR)', conversion: 'Conversão',
    share_whatsapp: 'Compartilhar no WhatsApp', check_this_ad: 'Veja este anúncio no Mercasto!',
    all: 'Tudo', language: 'Idioma', state: 'Estado', city: 'Cidade / Município', all_cities: 'Todas as cidades', apply: 'Aplicar',
    search_btn: 'Pesquisar', search_placeholder_short: 'Buscar produto...', guest: 'Convidado', post_ad: 'Publicar',
    mark_all_read: 'Marcar todas como lidas', no_notifications: 'Você não tem notificações',
    footer_desc: 'O marketplace local que mais cresce no México. Compre, venda, alugue e encontre trabalho com segurança.',
    buyers: 'Compradores', how_to_buy: 'Como comprar', safety_tips: 'Dicas de segurança',
    sellers: 'Vendedores', pricing: 'Preços', promote_ad: 'Promover anúncio',
    business: 'Negócios', partners: 'Parceiros', help: 'Ajuda', help_center: 'Central de Ajuda',
    safety_center: 'Central de Segurança', privacy_policy: 'Aviso de Privacidade',
    active_listings: 'anúncios ativos', users_online: 'usuários online', sell_fast: 'Vender rápido',
    find_job: 'Buscar emprego', rent_apt: 'Alugar apê', hire_service: 'Contratar serviço',
    browse_category: 'Explorar por categoria', sort_popular: 'Ordenar: Popular', show_less: 'Ver menos',
    view_all_cat: 'Ver todas as categorias →', trending_now: 'Tendências', save_search: 'Salvar busca',
    filter: 'Filtros', see_all: 'Ver tudo →', deal_of_day: 'Oferta do dia', up_to_40: 'Até 40% OFF',
    elec_phones: 'Eletrônicos e Celulares', shop_now: 'Comprar agora →', ends_in_8h: 'Termina em 8h',
    furniture: 'Móveis', living_room_sets: 'Salas de estar', from_price: 'Desde $4,999 MXN',
    see_deals: 'Ver ofertas →', automotive: 'Automotivo', certified_cars: 'Carros Certificados',
    zero_comm: '0% comissão esta semana', browse_cars: 'Explorar 124k →', for_sellers: 'Para vendedores',
    boost_ad: 'Destaque seu anúncio', boost_desc: '3x mais visualizações, melhor posição', promote_now: 'Promover agora →',
    re_spotlight: 'Imóveis em destaque', rent: 'Alugar', buy: 'Comprar', commercial: 'Comercial',
    view_props: 'Ver imóveis →', open_map: 'Abrir mapa', view_all_mexico: 'Ver todo o México',
    jobs_board: 'Vagas de emprego', remote_only: 'Somente remoto', full_time: 'Tempo integral',
    company: 'Empresa', salary_mxn: 'Salário MXN', showing_jobs: 'Mostrando novas vagas',
    upload_cv: 'Enviar CV', create_job_alert: 'Criar alerta', services_marketplace: 'Diretório de serviços',
    browse_services: 'Ver todos →', from: 'Desde', book_now: 'Reservar', year: 'Ano', price: 'Preço',
    recently_viewed: 'Vistos recentemente', clear_history: 'Limpar histórico',
    starter_desc: 'Ideal para vendas ocasionais', basic_stats: 'Estatísticas básicas',
    contacto_qr: 'Contato via QR', pro_desc: 'Para vendedores recorrentes', unlimited_ads: 'Anúncios ilimitados',
    boost_credits: 'Créditos mensais', advanced_stats: 'Estatísticas PRO', verified_badge: 'Selo verificado',
    enterprise: 'Enterprise', enterprise_desc: 'Imobiliárias, agências...', bulk_import: 'Importação em massa',
    account_manager: 'Suporte dedicado', storefront: 'Página da loja', contact_sales: 'Contatar vendas',
    how_it_works: 'Como o Mercasto funciona', post_60s: 'Publique em 60s',
    post_60s_desc: 'Fotos, preço, localização. A IA ajuda com o resto.',
    get_leads: 'Receba contatos', get_leads_desc: 'Chamadas, WhatsApp ou QR seguro.',
    meet_safely: 'Encontros seguros', meet_safely_desc: 'Perfis verificados (KYC) para sua tranquilidade.',
    sell_faster: 'Venda mais rápido', sell_faster_desc: 'Destaque seu anúncio e feche negócio hoje.',
    avoid_scams: 'Evite golpes', avoid_scams_desc: 'Nunca pague adiantado. Confira os selos.',
    learn_more: 'Saiba mais', safe_payments: 'Pagamentos seguros',
    safe_payments_desc: 'Encontre-se em público. Conte o dinheiro antes de sair.',
    verified_sellers: 'Vendedores verificados',
    verified_sellers_desc: 'Procure o selo azul de identidade confirmada (KYC).',
    popular_searches: 'Buscas populares', updated_hourly: 'Atualizado há 1h',
    explore_city: 'Explorar por cidade', app_title: 'Mercasto no seu telefone. Compre e venda mais rápido.',
    app_desc: 'Receba alertas instantâneos, gerencie tudo pelo celular e converse com segurança.',
    cam_autofill: 'Publicação rápida com câmera IA',
    safe_qr: 'Contato seguro com código QR', free_no_ads: 'Grátis • Sem anúncios no PRO',
    newsletter_title: 'Receba as melhores ofertas do México',
    newsletter_desc: 'Resumo semanal de ofertas, quedas de preço e novas vagas.',
    your_email: 'Seu e-mail', subscribe: 'Inscrever-se',
    transactions_tab: 'Transações',
    credits_btn_title: 'Comprar créditos',
    credits_unit: 'Créditos',
    redeem_coupon: 'Resgatar cupom',
    transactions_title: 'Histórico de Transações',
    transactions_desc: 'Consulte o registro das suas compras de créditos, promoções e recargas no Mercasto.',
    refresh_btn: 'Atualizar',
    no_transactions: 'Nenhuma transação registrada',
    no_transactions_desc: 'Você ainda não realizou nenhuma compra de créditos. Você pode recarregar seu saldo para destacar seus anúncios ou acessar recursos PRO.',
    buy_credits_offer: 'Comprar 100 Créditos ($100 MXN)',
    concept: 'Conceito',
    clip_ref: 'Referência de pagamento',
    date: 'Data',
    amount: 'Valor',
    status: 'Status',
    payment_service_fallback: 'Compra de Serviços',
    click_to_select: 'Clique para selecionar',
    payment_status_approved: 'Aprovado',
    payment_status_pending: 'Pendente',
    payment_status_failed: 'Falhou',
    page_word: 'Página',
    of_word: 'de',
    total_word: 'total',
    prev_btn: 'Anterior',
    next_btn: 'Seguinte',
    uploading_word: 'Enviando...',
    referrals_tab: 'Indicações',
    payment_error_generating: 'Erro ao gerar pagamento',
    payment_failed_or_canceled: 'O pagamento não pôde ser concluído ou foi cancelado.',
    connection_error: 'Erro de conexão',
    ad_promotion_description: 'Promoção de anúncio',
    plus_subscription_description: 'Assinatura Pacote Plus',
    pro_basic_subscription_description: 'Assinatura PRO Padrão',
    pro_max_subscription_description: 'Assinatura PRO Ilimitado',
    admin_payments_tab: 'Pagamentos',
    admin_transactions_registered: 'Transações Registradas',
    admin_volume_desc: 'Volume total de transações de pagamento',
    admin_approved_revenue: 'Receitas Aprovadas (Pág. Atual)',
    admin_approved_revenue_desc: 'Valor dos pagamentos bem-sucedidos exibidos',
    admin_payments_audit: 'Auditoria de Pagamentos',
    admin_payments_audit_desc: 'Monitore e valide as transações processadas através do gateway de pagamento.',
    admin_no_payments: 'Nenhum pagamento registrado',
    admin_no_payments_desc: 'Nenhuma transação foi encontrada no histórico do sistema. Todos os pagamentos iniciados aparecerão aqui.',
    admin_user: 'Usuário',
    admin_user_id: 'ID do Usuário:',
    admin_email_not_available: 'E-mail não disponível',
    admin_services_fallback: 'Serviços Mercasto',
    admin_click_to_select_all: 'Clique para selecionar tudo',

    // General UI
    close_btn: 'Fechar',
    edit: 'Editar',
    delete: 'Excluir',
    view: 'Ver',
    pause: 'Pausar',
    reactivate: 'Reativar',
    republish: 'Republicar',
    selected: 'selecionados',
    generating: 'Gerando...',
    generate_ai: '✨ Gerar com IA',

    // Cookie Banner
    cookies_aria_label: 'Aviso de cookies',
    cookies_title: 'Usamos cookies para melhorar sua experiência.',
    cookies_desc: 'Algumas são essenciais; outras nos ajudam a entender como você usa o Mercasto.',
    cookies_essential: 'Apenas essenciais',
    cookies_accept_all: 'Aceitar todas',

    // Onboarding Modal
    onboarding_welcome_title: 'Bem-vindo ao Mercasto!',
    onboarding_welcome_subtitle: 'O marketplace de confiança do México',
    onboarding_welcome_desc: 'Compre, venda e alugue em todo o México. Milhares de produtos e serviços perto de você.',
    onboarding_how_title: 'Como funciona?',
    onboarding_how_subtitle: 'Em 3 passos simples',
    onboarding_step1_label: 'Publique grátis',
    onboarding_step1_desc: 'Envie fotos e descreva o que vende em minutos',
    onboarding_step2_label: 'Converse com compradores',
    onboarding_step2_desc: 'Receba mensagens e negocie com segurança',
    onboarding_step3_label: 'Venda com segurança',
    onboarding_step3_desc: 'Combine a entrega e receba o pagamento',
    onboarding_profile_title: 'Complete seu perfil',
    onboarding_profile_subtitle: 'Vendedores verificados vendem 3× mais rápido',
    onboarding_checklist_desc: 'Complete estes passos para gerar mais confiança com os compradores:',
    onboarding_checklist_photo: 'Adicione uma foto de perfil',
    onboarding_checklist_phone: 'Verifique seu telefone',
    onboarding_checklist_bio: 'Escreva uma descrição',
    onboarding_complete_btn: 'Completar perfil',
    onboarding_skip_btn: 'Ignorar por enquanto',

    // Referral Program
    referral_title: 'Programa de Indicações',
    referral_desc: 'Convide seus amigos para o Mercasto e ambos ganharão créditos quando publicarem o primeiro anúncio.',
    referral_link: 'Seu link de indicação',
    copied: 'Copiado!',
    copy: 'Copiar',
    referral_friends: 'Amigos indicados',
    referral_credits: 'Créditos ganhos',
    referral_history: 'Histórico de indicações',
    referral_empty: 'Você ainda não convidou nenhum amigo. Compartilhe seu link para começar a ganhar!',
    credit: 'Crédito',

    // Ad Management (Post & Edit Screens)
    edit_ad: 'Editar anúncio',
    add_more_photos: 'Adicionar mais fotos',
    drag_photos_hint: 'Arraste suas fotos aqui ou',
    browse_label: 'procure',
    max_photos_hint: 'Máximo de 10 fotos (JPG, PNG)',
    select_state: 'Selecionar estado',
    video_hint: 'Vídeo (Opcional, MP4, máx 50MB)',
    ad_attributes: 'Características do anúncio',

    // Storefront Screen
    rfc_verified: 'RFC verificado',
    business_profile_tag: 'Perfil comercial',
    closed_hours: 'Fechado',
    check_hours: 'Consultar horário',
    seller_role: 'Vendedor',
    review_placeholder: 'Como foi sua experiência com este vendedor?',

    // MyAdsScreen & extra keys
    all_filter: 'Todos',
    active_status: 'Ativos',
    paused_status: 'Pausados',
    expired_status: 'Expirados',
    featured_status: 'Destaques',
    select_all: 'Selecionar tudo',
    ads_updated: 'anúncios atualizados',
    reviews_count: 'avaliações',
    ad_rejected: 'Este anúncio foi rejeitado',
    ad_rejected_edit_desc: 'Edite-o e ele será enviado para revisão novamente.',
    add_photo: 'Adicionar foto',
    back_to_ad: 'Voltar ao anúncio',
    complete_business_profile: 'Complete o perfil da sua empresa',
    complete_business_profile_hint: 'Adicione os dados do seu negócio para vender como PRO',
    drag_reorder: 'arrastar para reordenar',
    edit_ad_review_desc: 'Alterações importantes serão enviadas para revisão',
    error_loading_ad: 'Não foi possível carregar o anúncio',
    first_img_main_hint: 'A primeira imagem será a foto principal do anúncio',
    max_images_alert: 'Máximo de 10 imagens por anúncio',
    referral_error: 'Não conseguimos carregar seu link de indicação. Tente novamente.',
    referral_load_error: 'Não foi possível carregar o programa de indicações',
    save_changes_error: 'Erro ao salvar as alterações',
    saving_word: 'Salvando',
    select_category: 'Selecionar categoria'
  }
};

export const spotlightRealEstate = [
  { type: 'BUY', color: 'bg-slate-900', price: '$3,250,000', specs: '3 bed • 2 bath • 145m² Condo Centro', location: 'CDMX • 1d ago', img: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } },
  { type: 'RENT', color: 'bg-[#84CC16]', price: '$28,000/mo', specs: '2 bed • 2 bath • 98m² Providencia', location: 'GDL • 5h ago', img: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=600', badge: { label: 'Top seller', color: 'bg-blue-100 text-blue-700' } },
  { type: 'BUY', color: 'bg-slate-900', price: '$1,850,000', specs: 'Casa 3 rec • 180m² • Jardín', location: 'Tlaquepaque • 2d ago', img: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=600' },
  { type: 'RENT', color: 'bg-[#84CC16]', price: '$18,500/mo', specs: 'Loft 1 bed • Colonia Roma', location: 'CDMX • 3h ago', img: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600', badge: { label: 'Urgent', color: 'bg-red-500 text-white' } },
  { type: 'BUY', color: 'bg-slate-900', price: '$4,900,000', specs: 'Penthouse 4 bed • Vista ciudad', location: 'Monterrey • 6h ago', img: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } },
  { type: 'RENT', color: 'bg-[#84CC16]', price: '$12,000/mo', specs: 'Studio amueblado • Providencia', location: 'GDL • 1d ago', img: 'https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?w=600' }
];

export const jobsBoard = [
  { role: 'Senior React Developer', company: 'Mercasto', salary: '$65k – $85k', loc: 'Remote', logo: 'bg-lime-50 border', initial: 'MD' },
  { role: 'Restaurant Manager', company: 'La Palapa', salary: '$25,000', loc: 'Querétaro', logo: 'bg-amber-100 text-amber-700', initial: 'LP' },
  { role: 'Real Estate Agent', company: 'Century 21', salary: '$20k + Commission', loc: 'Guadalajara', logo: 'bg-blue-100 text-blue-700', initial: 'C21' },
  { role: 'English Teacher', company: 'Harmon Hall', salary: '$18,000', loc: 'Zapopan', logo: 'bg-emerald-100 text-emerald-700', initial: 'HH' },
  { role: 'Delivery Driver', company: 'DiDi', salary: '$15k – $22k', loc: 'Guadalajara', logo: 'bg-purple-100 text-purple-700', initial: 'Di' },
  { role: 'Graphic Designer (Freelance)', company: 'Freelance', salary: '$30,000', loc: 'Remote', logo: 'bg-slate-200', initial: '🎨' },
  { role: 'Barista', company: 'Starbucks', salary: '$12,500', loc: 'Guadalajara', logo: 'bg-green-100 text-green-700', initial: 'SB' },
  { role: 'Plumber - Full Time', company: 'Servicios Pro', salary: '$22,000', loc: 'Zapopan', logo: 'bg-orange-100', initial: '🔧' }
];

export const servicesMarketplace = [
  { title: 'House Cleaning Pro', stars: '4.9 (342)', price: '$450', img: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=100', desc: 'Deep cleaning, apartments & houses. Same-day availability in major cities.', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } },
  { title: 'AC Repair 24/7', stars: '4.8 (189)', price: '$650', img: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=100', desc: 'Installation, maintenance, emergency repair. 1yr warranty.', badge: { label: 'Top', color: 'bg-blue-100 text-blue-700' } },
  { title: 'Personal Trainer', stars: '5.0 (97)', price: '$300/hr', img: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=100', desc: 'Home or gym sessions. Weight loss & strength programs.' },
  { title: 'Event Photographer', stars: '4.7 (156)', price: '$2,500', img: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=100', desc: 'Weddings, corporate, real estate. Drone included.', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } },
  { title: 'Plumber Expert', stars: '4.9 (423)', price: '$400', img: 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=100', desc: 'Leaks, installations, 24h emergency service across Mexico.' },
  { title: 'Web Design Studio', stars: '5.0 (64)', price: '$8,900', img: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=100', desc: 'Landing pages, e-commerce, SEO. 7-day delivery.', badge: { label: 'Top', color: 'bg-blue-100 text-blue-700' } },
  { title: 'Dog Walker & Sitting', stars: '4.9 (201)', price: '$150', img: 'https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=100', desc: 'Daily walks, pet sitting, vet visits. Insured.' },
  { title: 'Electrician Certified', stars: '4.8 (178)', price: '$500', img: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=100', desc: 'Wiring, panels, smart home installation. Licensed.', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } }
];

export const automotiveDeals = [
  { price: '$235,000', title: 'Nissan Versa 2021 Advance', specs: '45,000 km • Auto • GDL', img: 'https://images.unsplash.com/photo-1550355291-bbee04a92027?w=600', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } },
  { price: '$289,000', title: 'VW Jetta 2019 Comfortline', specs: '62,300 km • Auto • QRO', img: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600', badge: { label: 'Top seller', color: 'bg-blue-100 text-blue-700' } },
  { price: '$345,000', title: 'Toyota Corolla 2020 Hybrid', specs: '38,100 km • Hybrid • GDL', img: 'https://images.unsplash.com/photo-1542362567-b07e54358753?w=600', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } },
  { price: '$285,000', title: 'Honda Civic 2019 Touring', specs: '71,200 km • Auto • Zapopan', img: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600' },
  { price: '$195,000', title: 'Chevrolet Aveo 2022 LT', specs: '29,500 km • Manual • Puebla', img: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=600', badge: { label: 'New', color: 'bg-[#84CC16] text-white' } },
  { price: '$420,000', title: 'Mazda CX-5 2021 i Sport', specs: '41,000 km • SUV • GDL', img: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=600', badge: { label: 'Verified', color: 'bg-emerald-100 text-emerald-700' } }
];

export const recentlyViewed = [
  { name: 'iPhone 15 Pro', price: '$18,999', img: 'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=200' },
  { name: '2BR Centro', price: '$32k/mo', img: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=200' },
  { name: 'Yamaha MT-07', price: '$145k', img: 'https://images.unsplash.com/photo-1558981282-6f5f7d5a2b8f?w=200' },
  { name: 'MacBook Air M2', price: '$24,500', img: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=200' },
  { name: 'Condo 3 bed', price: '$3.25M', img: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=200' },
  { name: 'Nike Air Max', price: '$1,850', img: 'https://images.unsplash.com/photo-1542291026-797186bcca9e?w=200' }
];
