import i18n from '../../i18n';

export const ADMIN_MODERATION_NAMESPACE = 'adminModeration';

const resources = {
  es: {
    noDate: 'Sin fecha',
    statuses: { approved: 'Aprobado', rejected: 'Rechazado', processing: 'IA revisando', queued: 'En cola IA', failed: 'Error de IA', manualReview: 'Revisión manual' },
    errors: {
      loadQueue: 'No se pudo cargar la cola ({{status}})', loadModeration: 'No se pudo cargar la moderación.', openFullAd: 'No se pudo abrir el anuncio completo.', openAd: 'No se pudo abrir el anuncio.', rejectionReason: 'Escribe el motivo del rechazo para que el vendedor pueda corregirlo.', changesReason: 'Escribe los cambios concretos que debe realizar el vendedor.', saveDecision: 'No se pudo guardar la decisión.', retryAi: 'No se pudo repetir la revisión automática.', startQueue: 'No se pudo iniciar la cola de IA.'
    },
    openAria: 'Abrir moderación inteligente', smartModeration: 'Moderación inteligente', summary: 'Pendientes: {{count}}', oldest: 'más antiguo {{wait}}',
    title: 'Moderación de anuncios', subtitle: 'Ordenados del más antiguo al más reciente · horario de Ciudad de México', sending: 'Enviando…', processWithAi: 'Procesar pendientes con IA', close: 'Cerrar', pending: 'Pendientes: {{count}}', refresh: 'Actualizar', loadingQueue: 'Cargando cola…', noPending: 'No hay anuncios pendientes.', illustrative: 'Ilustrativa', submitted: 'Enviado', waiting: 'Esperando', review: 'Revisar', openingAd: 'Abriendo anuncio completo…', selectHelp: 'Selecciona un anuncio y revisa fotos, descripción, vendedor, atributos e historial antes de decidir.',
    adNumber: 'Anuncio #{{id}}', submissionDate: 'Fecha de envío', imageAlt: 'Imagen {{number}}', illustrativeNotice: 'Imagen ilustrativa, no foto del vendedor', noImages: 'Sin imágenes', fullDescription: 'Descripción completa', noDescription: 'Sin descripción', adData: 'Datos del anuncio', category: 'Categoría', subcategory: 'Subcategoría', condition: 'Condición', location: 'Ubicación', seller: 'Vendedor', noName: 'Sin nombre', noEmail: 'Sin email', verifiedAccount: 'Cuenta verificada', originalPhotos: 'Fotos originales', yes: 'Sí', no: 'No', noOriginalPhotos: 'No; se usa portada ilustrativa', declaredFeatures: 'Características declaradas', analysisHistory: 'Análisis e historial', retryAnalysis: 'Repetir análisis de IA', lastResult: 'Último resultado:', noDecisions: 'Todavía no hay decisiones registradas.', administrator: 'Administrador', ai: 'IA', commentLabel: 'Comentario o motivo del rechazo', commentPlaceholder: 'Es obligatorio al rechazar y se guardará en el historial…', approvePublish: 'Aprobar y publicar', requestChanges: 'Solicitar cambios', leavePending: 'Dejar pendiente', reject: 'Rechazar', sourceDecision: '{{source}} · {{decision}}',
    decisions: { approved: 'Aprobado', rejected: 'Rechazado', manual_review: 'Revisión manual', changes_requested: 'Cambios solicitados' },
    wait: { daysHours: '{{days}} d {{hours}} h', hoursMinutes: '{{hours}} h {{minutes}} min', minutes: '{{minutes}} min' }
  },
  en: {
    noDate: 'No date',
    statuses: { approved: 'Approved', rejected: 'Rejected', processing: 'AI reviewing', queued: 'Queued for AI', failed: 'AI error', manualReview: 'Manual review' },
    errors: {
      loadQueue: 'Could not load the queue ({{status}})', loadModeration: 'Could not load moderation.', openFullAd: 'Could not open the full listing.', openAd: 'Could not open the listing.', rejectionReason: 'Enter a rejection reason so the seller can correct the listing.', changesReason: 'Enter the concrete changes the seller must make.', saveDecision: 'Could not save the decision.', retryAi: 'Could not repeat the automated review.', startQueue: 'Could not start the AI queue.'
    },
    openAria: 'Open intelligent moderation', smartModeration: 'Intelligent moderation', summary: 'Pending: {{count}}', oldest: 'oldest {{wait}}',
    title: 'Listing moderation', subtitle: 'Oldest first · Mexico City time', sending: 'Sending…', processWithAi: 'Process pending with AI', close: 'Close', pending: 'Pending: {{count}}', refresh: 'Refresh', loadingQueue: 'Loading queue…', noPending: 'No pending listings.', illustrative: 'Illustrative', submitted: 'Submitted', waiting: 'Waiting', review: 'Review', openingAd: 'Opening full listing…', selectHelp: 'Select a listing and review its photos, description, seller, attributes, and history before deciding.',
    adNumber: 'Listing #{{id}}', submissionDate: 'Submission date', imageAlt: 'Image {{number}}', illustrativeNotice: 'Illustrative image, not a seller photo', noImages: 'No images', fullDescription: 'Full description', noDescription: 'No description', adData: 'Listing details', category: 'Category', subcategory: 'Subcategory', condition: 'Condition', location: 'Location', seller: 'Seller', noName: 'No name', noEmail: 'No email', verifiedAccount: 'Verified account', originalPhotos: 'Original photos', yes: 'Yes', no: 'No', noOriginalPhotos: 'No; an illustrative cover is used', declaredFeatures: 'Declared features', analysisHistory: 'Analysis and history', retryAnalysis: 'Repeat AI analysis', lastResult: 'Latest result:', noDecisions: 'No decisions have been recorded yet.', administrator: 'Administrator', ai: 'AI', commentLabel: 'Comment or rejection reason', commentPlaceholder: 'Required when rejecting and saved in the history…', approvePublish: 'Approve and publish', requestChanges: 'Request changes', leavePending: 'Leave pending', reject: 'Reject', sourceDecision: '{{source}} · {{decision}}',
    decisions: { approved: 'Approved', rejected: 'Rejected', manual_review: 'Manual review', changes_requested: 'Changes requested' },
    wait: { daysHours: '{{days}} d {{hours}} h', hoursMinutes: '{{hours}} h {{minutes}} min', minutes: '{{minutes}} min' }
  },
  ru: {
    noDate: 'Нет даты',
    statuses: { approved: 'Одобрено', rejected: 'Отклонено', processing: 'ИИ проверяет', queued: 'В очереди ИИ', failed: 'Ошибка ИИ', manualReview: 'Ручная проверка' },
    errors: {
      loadQueue: 'Не удалось загрузить очередь ({{status}})', loadModeration: 'Не удалось загрузить модерацию.', openFullAd: 'Не удалось открыть объявление полностью.', openAd: 'Не удалось открыть объявление.', rejectionReason: 'Укажите причину отклонения, чтобы продавец мог исправить объявление.', changesReason: 'Укажите конкретные изменения, которые должен внести продавец.', saveDecision: 'Не удалось сохранить решение.', retryAi: 'Не удалось повторить автоматическую проверку.', startQueue: 'Не удалось запустить очередь ИИ.'
    },
    openAria: 'Открыть интеллектуальную модерацию', smartModeration: 'Интеллектуальная модерация', summary: 'Ожидают: {{count}}', oldest: 'самое старое {{wait}}',
    title: 'Модерация объявлений', subtitle: 'От самых старых к новым · время Мехико', sending: 'Отправка…', processWithAi: 'Проверить ожидающие с ИИ', close: 'Закрыть', pending: 'Ожидают: {{count}}', refresh: 'Обновить', loadingQueue: 'Загрузка очереди…', noPending: 'Нет объявлений на проверке.', illustrative: 'Иллюстрация', submitted: 'Подано', waiting: 'Ожидает', review: 'Проверить', openingAd: 'Открываем объявление полностью…', selectHelp: 'Выберите объявление и перед решением проверьте фотографии, описание, продавца, характеристики и историю.',
    adNumber: 'Объявление №{{id}}', submissionDate: 'Дата подачи', imageAlt: 'Изображение {{number}}', illustrativeNotice: 'Иллюстративное изображение, не фотография продавца', noImages: 'Нет изображений', fullDescription: 'Полное описание', noDescription: 'Нет описания', adData: 'Данные объявления', category: 'Категория', subcategory: 'Подкатегория', condition: 'Состояние', location: 'Местоположение', seller: 'Продавец', noName: 'Имя не указано', noEmail: 'Email не указан', verifiedAccount: 'Подтверждённый аккаунт', originalPhotos: 'Оригинальные фотографии', yes: 'Да', no: 'Нет', noOriginalPhotos: 'Нет; используется иллюстративная обложка', declaredFeatures: 'Заявленные характеристики', analysisHistory: 'Анализ и история', retryAnalysis: 'Повторить анализ ИИ', lastResult: 'Последний результат:', noDecisions: 'Решения пока не записаны.', administrator: 'Администратор', ai: 'ИИ', commentLabel: 'Комментарий или причина отклонения', commentPlaceholder: 'Обязательно при отклонении и сохраняется в истории…', approvePublish: 'Одобрить и опубликовать', requestChanges: 'Запросить изменения', leavePending: 'Оставить на проверке', reject: 'Отклонить', sourceDecision: '{{source}} · {{decision}}',
    decisions: { approved: 'Одобрено', rejected: 'Отклонено', manual_review: 'Ручная проверка', changes_requested: 'Запрошены изменения' },
    wait: { daysHours: '{{days}} д. {{hours}} ч.', hoursMinutes: '{{hours}} ч. {{minutes}} мин.', minutes: '{{minutes}} мин.' }
  },
  pt: {
    noDate: 'Sem data', statuses: { approved: 'Aprovado', rejected: 'Rejeitado', processing: 'IA analisando', queued: 'Na fila da IA', failed: 'Erro da IA', manualReview: 'Revisão manual' },
    errors: { loadQueue: 'Não foi possível carregar a fila ({{status}})', loadModeration: 'Não foi possível carregar a moderação.', openFullAd: 'Não foi possível abrir o anúncio completo.', openAd: 'Não foi possível abrir o anúncio.', rejectionReason: 'Informe o motivo da rejeição para que o vendedor possa corrigir o anúncio.', changesReason: 'Descreva as alterações concretas que o vendedor deve fazer.', saveDecision: 'Não foi possível salvar a decisão.', retryAi: 'Não foi possível repetir a revisão automática.', startQueue: 'Não foi possível iniciar a fila da IA.' },
    openAria: 'Abrir moderação inteligente', smartModeration: 'Moderação inteligente', summary: 'Pendentes: {{count}}', oldest: 'mais antigo {{wait}}', title: 'Moderação de anúncios', subtitle: 'Do mais antigo ao mais recente · horário da Cidade do México', sending: 'Enviando…', processWithAi: 'Processar pendentes com IA', close: 'Fechar', pending: 'Pendentes: {{count}}', refresh: 'Atualizar', loadingQueue: 'Carregando fila…', noPending: 'Não há anúncios pendentes.', illustrative: 'Ilustrativa', submitted: 'Enviado', waiting: 'Aguardando', review: 'Revisar', openingAd: 'Abrindo anúncio completo…', selectHelp: 'Selecione um anúncio e revise fotos, descrição, vendedor, atributos e histórico antes de decidir.', adNumber: 'Anúncio #{{id}}', submissionDate: 'Data de envio', imageAlt: 'Imagem {{number}}', illustrativeNotice: 'Imagem ilustrativa, não é foto do vendedor', noImages: 'Sem imagens', fullDescription: 'Descrição completa', noDescription: 'Sem descrição', adData: 'Dados do anúncio', category: 'Categoria', subcategory: 'Subcategoria', condition: 'Condição', location: 'Localização', seller: 'Vendedor', noName: 'Sem nome', noEmail: 'Sem e-mail', verifiedAccount: 'Conta verificada', originalPhotos: 'Fotos originais', yes: 'Sim', no: 'Não', noOriginalPhotos: 'Não; é usada uma capa ilustrativa', declaredFeatures: 'Características declaradas', analysisHistory: 'Análise e histórico', retryAnalysis: 'Repetir análise da IA', lastResult: 'Último resultado:', noDecisions: 'Ainda não há decisões registradas.', administrator: 'Administrador', ai: 'IA', commentLabel: 'Comentário ou motivo da rejeição', commentPlaceholder: 'Obrigatório ao rejeitar e salvo no histórico…', approvePublish: 'Aprovar e publicar', requestChanges: 'Solicitar alterações', leavePending: 'Manter pendente', reject: 'Rejeitar', sourceDecision: '{{source}} · {{decision}}', decisions: { approved: 'Aprovado', rejected: 'Rejeitado', manual_review: 'Revisão manual', changes_requested: 'Alterações solicitadas' }, wait: { daysHours: '{{days}} d {{hours}} h', hoursMinutes: '{{hours}} h {{minutes}} min', minutes: '{{minutes}} min' }
  },
  fr: {
    noDate: 'Aucune date', statuses: { approved: 'Approuvée', rejected: 'Rejetée', processing: 'Analyse par l’IA', queued: 'En attente IA', failed: 'Erreur IA', manualReview: 'Vérification manuelle' },
    errors: { loadQueue: 'Impossible de charger la file ({{status}})', loadModeration: 'Impossible de charger la modération.', openFullAd: 'Impossible d’ouvrir l’annonce complète.', openAd: 'Impossible d’ouvrir l’annonce.', rejectionReason: 'Indiquez le motif du rejet afin que le vendeur puisse corriger l’annonce.', changesReason: 'Décrivez les modifications précises que le vendeur doit effectuer.', saveDecision: 'Impossible d’enregistrer la décision.', retryAi: 'Impossible de relancer la vérification automatique.', startQueue: 'Impossible de démarrer la file IA.' },
    openAria: 'Ouvrir la modération intelligente', smartModeration: 'Modération intelligente', summary: 'En attente : {{count}}', oldest: 'plus ancienne {{wait}}', title: 'Modération des annonces', subtitle: 'De la plus ancienne à la plus récente · heure de Mexico', sending: 'Envoi…', processWithAi: 'Traiter avec l’IA', close: 'Fermer', pending: 'En attente : {{count}}', refresh: 'Actualiser', loadingQueue: 'Chargement de la file…', noPending: 'Aucune annonce en attente.', illustrative: 'Illustration', submitted: 'Soumise', waiting: 'En attente', review: 'Vérifier', openingAd: 'Ouverture de l’annonce complète…', selectHelp: 'Sélectionnez une annonce et vérifiez les photos, la description, le vendeur, les attributs et l’historique avant de décider.', adNumber: 'Annonce n°{{id}}', submissionDate: 'Date de soumission', imageAlt: 'Image {{number}}', illustrativeNotice: 'Image illustrative, pas une photo du vendeur', noImages: 'Aucune image', fullDescription: 'Description complète', noDescription: 'Aucune description', adData: 'Détails de l’annonce', category: 'Catégorie', subcategory: 'Sous-catégorie', condition: 'État', location: 'Localisation', seller: 'Vendeur', noName: 'Sans nom', noEmail: 'Sans e-mail', verifiedAccount: 'Compte vérifié', originalPhotos: 'Photos originales', yes: 'Oui', no: 'Non', noOriginalPhotos: 'Non ; une couverture illustrative est utilisée', declaredFeatures: 'Caractéristiques déclarées', analysisHistory: 'Analyse et historique', retryAnalysis: 'Relancer l’analyse IA', lastResult: 'Dernier résultat :', noDecisions: 'Aucune décision enregistrée pour le moment.', administrator: 'Administrateur', ai: 'IA', commentLabel: 'Commentaire ou motif du rejet', commentPlaceholder: 'Obligatoire en cas de rejet et enregistré dans l’historique…', approvePublish: 'Approuver et publier', requestChanges: 'Demander des modifications', leavePending: 'Laisser en attente', reject: 'Rejeter', sourceDecision: '{{source}} · {{decision}}', decisions: { approved: 'Approuvée', rejected: 'Rejetée', manual_review: 'Vérification manuelle', changes_requested: 'Modifications demandées' }, wait: { daysHours: '{{days}} j {{hours}} h', hoursMinutes: '{{hours}} h {{minutes}} min', minutes: '{{minutes}} min' }
  },
  de: {
    noDate: 'Kein Datum', statuses: { approved: 'Genehmigt', rejected: 'Abgelehnt', processing: 'KI prüft', queued: 'In KI-Warteschlange', failed: 'KI-Fehler', manualReview: 'Manuelle Prüfung' },
    errors: { loadQueue: 'Warteschlange konnte nicht geladen werden ({{status}})', loadModeration: 'Moderation konnte nicht geladen werden.', openFullAd: 'Die vollständige Anzeige konnte nicht geöffnet werden.', openAd: 'Die Anzeige konnte nicht geöffnet werden.', rejectionReason: 'Geben Sie einen Ablehnungsgrund an, damit der Verkäufer die Anzeige korrigieren kann.', changesReason: 'Beschreiben Sie die konkreten Änderungen, die der Verkäufer vornehmen muss.', saveDecision: 'Die Entscheidung konnte nicht gespeichert werden.', retryAi: 'Die automatische Prüfung konnte nicht wiederholt werden.', startQueue: 'Die KI-Warteschlange konnte nicht gestartet werden.' },
    openAria: 'Intelligente Moderation öffnen', smartModeration: 'Intelligente Moderation', summary: 'Ausstehend: {{count}}', oldest: 'älteste {{wait}}', title: 'Anzeigenmoderation', subtitle: 'Älteste zuerst · Zeit in Mexiko-Stadt', sending: 'Wird gesendet…', processWithAi: 'Ausstehende mit KI prüfen', close: 'Schließen', pending: 'Ausstehend: {{count}}', refresh: 'Aktualisieren', loadingQueue: 'Warteschlange wird geladen…', noPending: 'Keine ausstehenden Anzeigen.', illustrative: 'Illustrativ', submitted: 'Eingereicht', waiting: 'Wartet', review: 'Prüfen', openingAd: 'Vollständige Anzeige wird geöffnet…', selectHelp: 'Wählen Sie eine Anzeige und prüfen Sie Fotos, Beschreibung, Verkäufer, Merkmale und Verlauf, bevor Sie entscheiden.', adNumber: 'Anzeige Nr. {{id}}', submissionDate: 'Einreichungsdatum', imageAlt: 'Bild {{number}}', illustrativeNotice: 'Illustratives Bild, kein Verkäuferfoto', noImages: 'Keine Bilder', fullDescription: 'Vollständige Beschreibung', noDescription: 'Keine Beschreibung', adData: 'Anzeigendaten', category: 'Kategorie', subcategory: 'Unterkategorie', condition: 'Zustand', location: 'Standort', seller: 'Verkäufer', noName: 'Kein Name', noEmail: 'Keine E-Mail', verifiedAccount: 'Verifiziertes Konto', originalPhotos: 'Originalfotos', yes: 'Ja', no: 'Nein', noOriginalPhotos: 'Nein; es wird ein illustratives Titelbild verwendet', declaredFeatures: 'Angegebene Merkmale', analysisHistory: 'Analyse und Verlauf', retryAnalysis: 'KI-Analyse wiederholen', lastResult: 'Letztes Ergebnis:', noDecisions: 'Noch keine Entscheidungen erfasst.', administrator: 'Administrator', ai: 'KI', commentLabel: 'Kommentar oder Ablehnungsgrund', commentPlaceholder: 'Bei Ablehnung erforderlich und im Verlauf gespeichert…', approvePublish: 'Genehmigen und veröffentlichen', requestChanges: 'Änderungen anfordern', leavePending: 'Ausstehend lassen', reject: 'Ablehnen', sourceDecision: '{{source}} · {{decision}}', decisions: { approved: 'Genehmigt', rejected: 'Abgelehnt', manual_review: 'Manuelle Prüfung', changes_requested: 'Änderungen angefordert' }, wait: { daysHours: '{{days}} T. {{hours}} Std.', hoursMinutes: '{{hours}} Std. {{minutes}} Min.', minutes: '{{minutes}} Min.' }
  },
  it: {
    noDate: 'Nessuna data', statuses: { approved: 'Approvato', rejected: 'Rifiutato', processing: 'IA in revisione', queued: 'In coda IA', failed: 'Errore IA', manualReview: 'Revisione manuale' },
    errors: { loadQueue: 'Impossibile caricare la coda ({{status}})', loadModeration: 'Impossibile caricare la moderazione.', openFullAd: 'Impossibile aprire l’annuncio completo.', openAd: 'Impossibile aprire l’annuncio.', rejectionReason: 'Inserisci il motivo del rifiuto affinché il venditore possa correggere l’annuncio.', changesReason: 'Indica le modifiche concrete che il venditore deve apportare.', saveDecision: 'Impossibile salvare la decisione.', retryAi: 'Impossibile ripetere la revisione automatica.', startQueue: 'Impossibile avviare la coda IA.' },
    openAria: 'Apri moderazione intelligente', smartModeration: 'Moderazione intelligente', summary: 'In attesa: {{count}}', oldest: 'più vecchio {{wait}}', title: 'Moderazione annunci', subtitle: 'Dal più vecchio al più recente · ora di Città del Messico', sending: 'Invio…', processWithAi: 'Elabora con IA', close: 'Chiudi', pending: 'In attesa: {{count}}', refresh: 'Aggiorna', loadingQueue: 'Caricamento coda…', noPending: 'Nessun annuncio in attesa.', illustrative: 'Illustrativa', submitted: 'Inviato', waiting: 'In attesa', review: 'Controlla', openingAd: 'Apertura annuncio completo…', selectHelp: 'Seleziona un annuncio e controlla foto, descrizione, venditore, attributi e cronologia prima di decidere.', adNumber: 'Annuncio n. {{id}}', submissionDate: 'Data di invio', imageAlt: 'Immagine {{number}}', illustrativeNotice: 'Immagine illustrativa, non una foto del venditore', noImages: 'Nessuna immagine', fullDescription: 'Descrizione completa', noDescription: 'Nessuna descrizione', adData: 'Dati annuncio', category: 'Categoria', subcategory: 'Sottocategoria', condition: 'Condizione', location: 'Posizione', seller: 'Venditore', noName: 'Senza nome', noEmail: 'Senza email', verifiedAccount: 'Account verificato', originalPhotos: 'Foto originali', yes: 'Sì', no: 'No', noOriginalPhotos: 'No; viene usata una copertina illustrativa', declaredFeatures: 'Caratteristiche dichiarate', analysisHistory: 'Analisi e cronologia', retryAnalysis: 'Ripeti analisi IA', lastResult: 'Ultimo risultato:', noDecisions: 'Nessuna decisione registrata.', administrator: 'Amministratore', ai: 'IA', commentLabel: 'Commento o motivo del rifiuto', commentPlaceholder: 'Obbligatorio in caso di rifiuto e salvato nella cronologia…', approvePublish: 'Approva e pubblica', requestChanges: 'Richiedi modifiche', leavePending: 'Lascia in attesa', reject: 'Rifiuta', sourceDecision: '{{source}} · {{decision}}', decisions: { approved: 'Approvato', rejected: 'Rifiutato', manual_review: 'Revisione manuale', changes_requested: 'Modifiche richieste' }, wait: { daysHours: '{{days}} g {{hours}} h', hoursMinutes: '{{hours}} h {{minutes}} min', minutes: '{{minutes}} min' }
  },
  zh: {
    noDate: '无日期', statuses: { approved: '已批准', rejected: '已拒绝', processing: 'AI 审核中', queued: 'AI 队列中', failed: 'AI 错误', manualReview: '人工审核' },
    errors: { loadQueue: '无法加载队列（{{status}}）', loadModeration: '无法加载审核页面。', openFullAd: '无法打开完整广告。', openAd: '无法打开广告。', rejectionReason: '请输入拒绝原因，以便卖家修改广告。', changesReason: '请说明卖家必须进行的具体修改。', saveDecision: '无法保存决定。', retryAi: '无法重新进行自动审核。', startQueue: '无法启动 AI 队列。' },
    openAria: '打开智能审核', smartModeration: '智能审核', summary: '待审核：{{count}}', oldest: '最早 {{wait}}', title: '广告审核', subtitle: '按最早到最新排序 · 墨西哥城时间', sending: '发送中…', processWithAi: '使用 AI 处理待审核广告', close: '关闭', pending: '待审核：{{count}}', refresh: '刷新', loadingQueue: '正在加载队列…', noPending: '没有待审核广告。', illustrative: '示意图', submitted: '提交于', waiting: '已等待', review: '审核', openingAd: '正在打开完整广告…', selectHelp: '请选择广告，并在决定前检查照片、描述、卖家、属性和历史记录。', adNumber: '广告 #{{id}}', submissionDate: '提交日期', imageAlt: '图片 {{number}}', illustrativeNotice: '示意图片，并非卖家照片', noImages: '无图片', fullDescription: '完整描述', noDescription: '无描述', adData: '广告信息', category: '类别', subcategory: '子类别', condition: '状况', location: '位置', seller: '卖家', noName: '未提供姓名', noEmail: '未提供邮箱', verifiedAccount: '已验证账户', originalPhotos: '原始照片', yes: '是', no: '否', noOriginalPhotos: '否；使用示意封面', declaredFeatures: '声明的特征', analysisHistory: '分析与历史', retryAnalysis: '重新进行 AI 分析', lastResult: '最新结果：', noDecisions: '尚未记录任何决定。', administrator: '管理员', ai: 'AI', commentLabel: '备注或拒绝原因', commentPlaceholder: '拒绝时必填，并将保存到历史记录…', approvePublish: '批准并发布', requestChanges: '要求修改', leavePending: '保持待审核', reject: '拒绝', sourceDecision: '{{source}} · {{decision}}', decisions: { approved: '已批准', rejected: '已拒绝', manual_review: '人工审核', changes_requested: '已要求修改' }, wait: { daysHours: '{{days}}天 {{hours}}小时', hoursMinutes: '{{hours}}小时 {{minutes}}分钟', minutes: '{{minutes}}分钟' }
  },
  ko: {
    noDate: '날짜 없음', statuses: { approved: '승인됨', rejected: '거부됨', processing: 'AI 검토 중', queued: 'AI 대기열', failed: 'AI 오류', manualReview: '수동 검토' },
    errors: { loadQueue: '대기열을 불러올 수 없습니다 ({{status}})', loadModeration: '검토 화면을 불러올 수 없습니다.', openFullAd: '전체 광고를 열 수 없습니다.', openAd: '광고를 열 수 없습니다.', rejectionReason: '판매자가 광고를 수정할 수 있도록 거부 사유를 입력하세요.', changesReason: '판매자가 해야 할 구체적인 수정 사항을 입력하세요.', saveDecision: '결정을 저장할 수 없습니다.', retryAi: '자동 검토를 다시 실행할 수 없습니다.', startQueue: 'AI 대기열을 시작할 수 없습니다.' },
    openAria: '지능형 검토 열기', smartModeration: '지능형 검토', summary: '대기: {{count}}', oldest: '가장 오래된 항목 {{wait}}', title: '광고 검토', subtitle: '오래된 순서 · 멕시코시티 시간', sending: '전송 중…', processWithAi: 'AI로 대기 항목 처리', close: '닫기', pending: '대기: {{count}}', refresh: '새로고침', loadingQueue: '대기열 로딩 중…', noPending: '대기 중인 광고가 없습니다.', illustrative: '예시 이미지', submitted: '제출', waiting: '대기', review: '검토', openingAd: '전체 광고 여는 중…', selectHelp: '결정하기 전에 광고를 선택하고 사진, 설명, 판매자, 속성 및 이력을 확인하세요.', adNumber: '광고 #{{id}}', submissionDate: '제출 날짜', imageAlt: '이미지 {{number}}', illustrativeNotice: '예시 이미지이며 판매자 사진이 아닙니다', noImages: '이미지 없음', fullDescription: '전체 설명', noDescription: '설명 없음', adData: '광고 정보', category: '카테고리', subcategory: '하위 카테고리', condition: '상태', location: '위치', seller: '판매자', noName: '이름 없음', noEmail: '이메일 없음', verifiedAccount: '인증된 계정', originalPhotos: '원본 사진', yes: '예', no: '아니요', noOriginalPhotos: '아니요; 예시 표지가 사용됩니다', declaredFeatures: '신고된 특성', analysisHistory: '분석 및 이력', retryAnalysis: 'AI 분석 다시 실행', lastResult: '최근 결과:', noDecisions: '아직 기록된 결정이 없습니다.', administrator: '관리자', ai: 'AI', commentLabel: '메모 또는 거부 사유', commentPlaceholder: '거부 시 필수이며 이력에 저장됩니다…', approvePublish: '승인 및 게시', requestChanges: '수정 요청', leavePending: '대기 상태 유지', reject: '거부', sourceDecision: '{{source}} · {{decision}}', decisions: { approved: '승인됨', rejected: '거부됨', manual_review: '수동 검토', changes_requested: '수정 요청됨' }, wait: { daysHours: '{{days}}일 {{hours}}시간', hoursMinutes: '{{hours}}시간 {{minutes}}분', minutes: '{{minutes}}분' }
  },
  ja: {
    noDate: '日付なし', statuses: { approved: '承認済み', rejected: '却下', processing: 'AI確認中', queued: 'AI待機中', failed: 'AIエラー', manualReview: '手動確認' },
    errors: { loadQueue: 'キューを読み込めませんでした（{{status}}）', loadModeration: 'モデレーションを読み込めませんでした。', openFullAd: '広告全体を開けませんでした。', openAd: '広告を開けませんでした。', rejectionReason: '出品者が修正できるよう、却下理由を入力してください。', changesReason: '出品者が行う必要のある具体的な修正内容を入力してください。', saveDecision: '判断を保存できませんでした。', retryAi: '自動確認を再実行できませんでした。', startQueue: 'AIキューを開始できませんでした。' },
    openAria: 'インテリジェントモデレーションを開く', smartModeration: 'インテリジェントモデレーション', summary: '保留中：{{count}}', oldest: '最古 {{wait}}', title: '広告モデレーション', subtitle: '古い順 · メキシコシティ時間', sending: '送信中…', processWithAi: 'AIで保留中を処理', close: '閉じる', pending: '保留中：{{count}}', refresh: '更新', loadingQueue: 'キューを読み込み中…', noPending: '保留中の広告はありません。', illustrative: 'イメージ', submitted: '提出', waiting: '待機', review: '確認', openingAd: '広告全体を開いています…', selectHelp: '広告を選択し、判断前に写真、説明、出品者、属性、履歴を確認してください。', adNumber: '広告 #{{id}}', submissionDate: '提出日', imageAlt: '画像 {{number}}', illustrativeNotice: 'イメージ画像であり、出品者の写真ではありません', noImages: '画像なし', fullDescription: '完全な説明', noDescription: '説明なし', adData: '広告情報', category: 'カテゴリー', subcategory: 'サブカテゴリー', condition: '状態', location: '場所', seller: '出品者', noName: '名前なし', noEmail: 'メールなし', verifiedAccount: '確認済みアカウント', originalPhotos: '元の写真', yes: 'はい', no: 'いいえ', noOriginalPhotos: 'いいえ；イメージカバーを使用', declaredFeatures: '申告された特徴', analysisHistory: '分析と履歴', retryAnalysis: 'AI分析を再実行', lastResult: '最新結果：', noDecisions: 'まだ判断は記録されていません。', administrator: '管理者', ai: 'AI', commentLabel: 'コメントまたは却下理由', commentPlaceholder: '却下時は必須で履歴に保存されます…', approvePublish: '承認して公開', requestChanges: '修正を依頼', leavePending: '保留のままにする', reject: '却下', sourceDecision: '{{source}} · {{decision}}', decisions: { approved: '承認済み', rejected: '却下', manual_review: '手動確認', changes_requested: '修正依頼済み' }, wait: { daysHours: '{{days}}日 {{hours}}時間', hoursMinutes: '{{hours}}時間 {{minutes}}分', minutes: '{{minutes}}分' }
  },
  ar: {
    noDate: 'بلا تاريخ', statuses: { approved: 'تمت الموافقة', rejected: 'مرفوض', processing: 'الذكاء الاصطناعي يراجع', queued: 'في قائمة انتظار الذكاء الاصطناعي', failed: 'خطأ في الذكاء الاصطناعي', manualReview: 'مراجعة يدوية' },
    errors: { loadQueue: 'تعذر تحميل قائمة الانتظار ({{status}})', loadModeration: 'تعذر تحميل المراجعة.', openFullAd: 'تعذر فتح الإعلان كاملًا.', openAd: 'تعذر فتح الإعلان.', rejectionReason: 'اكتب سبب الرفض حتى يتمكن البائع من تصحيح الإعلان.', changesReason: 'اكتب التعديلات المحددة التي يجب على البائع إجراؤها.', saveDecision: 'تعذر حفظ القرار.', retryAi: 'تعذرت إعادة المراجعة الآلية.', startQueue: 'تعذر بدء قائمة انتظار الذكاء الاصطناعي.' },
    openAria: 'فتح المراجعة الذكية', smartModeration: 'المراجعة الذكية', summary: 'قيد الانتظار: {{count}}', oldest: 'الأقدم {{wait}}', title: 'مراجعة الإعلانات', subtitle: 'من الأقدم إلى الأحدث · توقيت مكسيكو سيتي', sending: 'جارٍ الإرسال…', processWithAi: 'معالجة المعلّق بالذكاء الاصطناعي', close: 'إغلاق', pending: 'قيد الانتظار: {{count}}', refresh: 'تحديث', loadingQueue: 'جارٍ تحميل القائمة…', noPending: 'لا توجد إعلانات معلّقة.', illustrative: 'توضيحية', submitted: 'قُدّم', waiting: 'ينتظر', review: 'مراجعة', openingAd: 'جارٍ فتح الإعلان كاملًا…', selectHelp: 'اختر إعلانًا وراجع الصور والوصف والبائع والسمات والسجل قبل اتخاذ القرار.', adNumber: 'الإعلان رقم {{id}}', submissionDate: 'تاريخ التقديم', imageAlt: 'الصورة {{number}}', illustrativeNotice: 'صورة توضيحية وليست صورة من البائع', noImages: 'لا توجد صور', fullDescription: 'الوصف الكامل', noDescription: 'لا يوجد وصف', adData: 'بيانات الإعلان', category: 'الفئة', subcategory: 'الفئة الفرعية', condition: 'الحالة', location: 'الموقع', seller: 'البائع', noName: 'بلا اسم', noEmail: 'بلا بريد إلكتروني', verifiedAccount: 'حساب موثّق', originalPhotos: 'الصور الأصلية', yes: 'نعم', no: 'لا', noOriginalPhotos: 'لا؛ تُستخدم صورة غلاف توضيحية', declaredFeatures: 'الخصائص المعلنة', analysisHistory: 'التحليل والسجل', retryAnalysis: 'إعادة تحليل الذكاء الاصطناعي', lastResult: 'آخر نتيجة:', noDecisions: 'لم تُسجل قرارات بعد.', administrator: 'المشرف', ai: 'الذكاء الاصطناعي', commentLabel: 'تعليق أو سبب الرفض', commentPlaceholder: 'إلزامي عند الرفض ويُحفظ في السجل…', approvePublish: 'الموافقة والنشر', requestChanges: 'طلب تعديلات', leavePending: 'إبقاؤه معلّقًا', reject: 'رفض', sourceDecision: '{{source}} · {{decision}}', decisions: { approved: 'تمت الموافقة', rejected: 'مرفوض', manual_review: 'مراجعة يدوية', changes_requested: 'طُلبت تعديلات' }, wait: { daysHours: '{{days}} ي {{hours}} س', hoursMinutes: '{{hours}} س {{minutes}} د', minutes: '{{minutes}} د' }
  },


};

const aiAssistResources = {
  es: { title: 'Evidencia de asistencia IA', description: 'La IA solo asesora. La decisión sensible sigue siendo humana.', humanAuthoritative: 'Decisión humana', advisory: 'Solo asesoría', provider: 'Proveedor', gatewayVersion: 'Versión gateway', model: 'Modelo', runtime: 'Tiempo', mode: 'Modo', proposed: 'Propuesta IA', finalRoute: 'Ruta final', policyIds: 'Señales de política', images: 'Fotos preparadas', modelMedia: 'Media en modelo', omittedMedia: 'Media omitida', videoFrames: 'Fotogramas', none: 'Ninguna', disabled: 'Desactivada', disabledNote: 'La asistencia IA está desactivada; el caso permanece en revisión humana.', manualFallback: 'La revisión automática no fue concluyente; el caso permanece en revisión humana.' },
  en: { title: 'AI assist evidence', description: 'AI is advisory only. Sensitive decisions remain human-authoritative.', humanAuthoritative: 'Human decision', advisory: 'Advisory only', provider: 'Provider', gatewayVersion: 'Gateway version', model: 'Model', runtime: 'Runtime', mode: 'Mode', proposed: 'AI proposal', finalRoute: 'Final route', policyIds: 'Policy signals', images: 'Prepared images', modelMedia: 'Model media', omittedMedia: 'Omitted media', videoFrames: 'Video frames', none: 'None', disabled: 'Disabled', disabledNote: 'AI assistance is disabled; the case remains in human review.', manualFallback: 'Automated review was inconclusive; the case remains in human review.' },
  ru: { title: 'Данные ИИ-помощника', description: 'ИИ только помогает. Чувствительные решения принимает человек.', humanAuthoritative: 'Решение человека', advisory: 'Только рекомендация', provider: 'Провайдер', gatewayVersion: 'Версия gateway', model: 'Модель', runtime: 'Время', mode: 'Режим', proposed: 'Предложение ИИ', finalRoute: 'Итоговый маршрут', policyIds: 'Сигналы политики', images: 'Подготовлено фото', modelMedia: 'Медиа в модели', omittedMedia: 'Пропущено медиа', videoFrames: 'Кадры видео', none: 'Нет', disabled: 'Отключено', disabledNote: 'ИИ-помощник отключён; случай остаётся на ручной проверке.', manualFallback: 'Автопроверка не дала надёжного результата; случай остаётся на ручной проверке.' },
  pt: { title: 'Evidência da assistência de IA', description: 'A IA apenas auxilia. Decisões sensíveis continuam humanas.', humanAuthoritative: 'Decisão humana', advisory: 'Somente assistência', provider: 'Provedor', gatewayVersion: 'Versão do gateway', model: 'Modelo', runtime: 'Tempo', mode: 'Modo', proposed: 'Proposta da IA', finalRoute: 'Rota final', policyIds: 'Sinais de política', images: 'Imagens preparadas', modelMedia: 'Mídia no modelo', omittedMedia: 'Mídia omitida', videoFrames: 'Quadros de vídeo', none: 'Nenhum', disabled: 'Desativada', disabledNote: 'A assistência de IA está desativada; o caso permanece em revisão humana.', manualFallback: 'A revisão automática foi inconclusiva; o caso permanece em revisão humana.' },
  fr: { title: 'Preuves de l’assistance IA', description: 'L’IA est seulement consultative. Les décisions sensibles restent humaines.', humanAuthoritative: 'Décision humaine', advisory: 'Conseil uniquement', provider: 'Fournisseur', gatewayVersion: 'Version de la passerelle', model: 'Modèle', runtime: 'Durée', mode: 'Mode', proposed: 'Proposition IA', finalRoute: 'Traitement final', policyIds: 'Signaux de politique', images: 'Images préparées', modelMedia: 'Médias du modèle', omittedMedia: 'Médias omis', videoFrames: 'Images vidéo', none: 'Aucun', disabled: 'Désactivée', disabledNote: 'L’assistance IA est désactivée ; le cas reste en vérification humaine.', manualFallback: 'La vérification automatique est non concluante ; le cas reste en vérification humaine.' },
  de: { title: 'Nachweise der KI-Unterstützung', description: 'Die KI berät nur. Sensible Entscheidungen bleiben beim Menschen.', humanAuthoritative: 'Menschliche Entscheidung', advisory: 'Nur Beratung', provider: 'Anbieter', gatewayVersion: 'Gateway-Version', model: 'Modell', runtime: 'Laufzeit', mode: 'Modus', proposed: 'KI-Vorschlag', finalRoute: 'Endgültiger Weg', policyIds: 'Richtliniensignale', images: 'Vorbereitete Bilder', modelMedia: 'Modellmedien', omittedMedia: 'Ausgelassene Medien', videoFrames: 'Videoframes', none: 'Keine', disabled: 'Deaktiviert', disabledNote: 'Die KI-Unterstützung ist deaktiviert; der Fall bleibt in menschlicher Prüfung.', manualFallback: 'Die automatische Prüfung war nicht eindeutig; der Fall bleibt in menschlicher Prüfung.' },
  it: { title: 'Evidenza assistenza IA', description: 'L’IA fornisce solo assistenza. Le decisioni sensibili restano umane.', humanAuthoritative: 'Decisione umana', advisory: 'Solo assistenza', provider: 'Provider', gatewayVersion: 'Versione gateway', model: 'Modello', runtime: 'Durata', mode: 'Modalità', proposed: 'Proposta IA', finalRoute: 'Percorso finale', policyIds: 'Segnali di policy', images: 'Immagini preparate', modelMedia: 'Media nel modello', omittedMedia: 'Media omessi', videoFrames: 'Fotogrammi video', none: 'Nessuno', disabled: 'Disattivata', disabledNote: 'L’assistenza IA è disattivata; il caso resta in revisione umana.', manualFallback: 'La revisione automatica non è conclusiva; il caso resta in revisione umana.' },
  zh: { title: 'AI 辅助证据', description: 'AI 仅提供建议，敏感决定仍由人工做出。', humanAuthoritative: '人工决定', advisory: '仅供辅助', provider: '提供方', gatewayVersion: '网关版本', model: '模型', runtime: '耗时', mode: '模式', proposed: 'AI 建议', finalRoute: '最终路径', policyIds: '政策信号', images: '已准备图片', modelMedia: '模型媒体', omittedMedia: '省略媒体', videoFrames: '视频帧', none: '无', disabled: '已停用', disabledNote: 'AI 辅助已停用；该案例继续由人工审核。', manualFallback: '自动审核未得出可靠结论；该案例继续由人工审核。' },
  ko: { title: 'AI 보조 근거', description: 'AI는 조언만 제공합니다. 민감한 결정은 사람이 내립니다.', humanAuthoritative: '사람의 결정', advisory: '보조 전용', provider: '제공자', gatewayVersion: '게이트웨이 버전', model: '모델', runtime: '실행 시간', mode: '모드', proposed: 'AI 제안', finalRoute: '최종 경로', policyIds: '정책 신호', images: '준비된 이미지', modelMedia: '모델 미디어', omittedMedia: '생략된 미디어', videoFrames: '비디오 프레임', none: '없음', disabled: '비활성화', disabledNote: 'AI 보조가 비활성화되어 사례는 사람의 검토 상태로 유지됩니다.', manualFallback: '자동 검토 결과가 불확실하여 사례는 사람의 검토 상태로 유지됩니다.' },
  ja: { title: 'AI支援の根拠', description: 'AIは助言のみを行い、重要な判断は人が行います。', humanAuthoritative: '人による判断', advisory: '助言のみ', provider: 'プロバイダー', gatewayVersion: 'ゲートウェイ版', model: 'モデル', runtime: '処理時間', mode: 'モード', proposed: 'AI提案', finalRoute: '最終経路', policyIds: 'ポリシー信号', images: '準備済み画像', modelMedia: 'モデル媒体', omittedMedia: '省略媒体', videoFrames: '動画フレーム', none: 'なし', disabled: '無効', disabledNote: 'AI支援は無効です。このケースは人による確認のままです。', manualFallback: '自動確認で確定できなかったため、このケースは人による確認のままです。' },
  ar: { title: 'أدلة مساعدة الذكاء الاصطناعي', description: 'الذكاء الاصطناعي استشاري فقط، والقرارات الحساسة تبقى بشرية.', humanAuthoritative: 'قرار بشري', advisory: 'استشاري فقط', provider: 'المزوّد', gatewayVersion: 'إصدار البوابة', model: 'النموذج', runtime: 'المدة', mode: 'الوضع', proposed: 'اقتراح الذكاء الاصطناعي', finalRoute: 'المسار النهائي', policyIds: 'إشارات السياسة', images: 'الصور المجهزة', modelMedia: 'وسائط النموذج', omittedMedia: 'الوسائط المتروكة', videoFrames: 'إطارات الفيديو', none: 'لا يوجد', disabled: 'معطّل', disabledNote: 'مساعدة الذكاء الاصطناعي معطّلة؛ تبقى الحالة قيد المراجعة البشرية.', manualFallback: 'لم تكن المراجعة الآلية حاسمة؛ تبقى الحالة قيد المراجعة البشرية.' },
};


Object.entries(resources).forEach(([language, resource]) => {
  resource.aiAssist = aiAssistResources[language] || aiAssistResources.en;
  if (!i18n.hasResourceBundle(language, ADMIN_MODERATION_NAMESPACE)) {
    i18n.addResourceBundle(language, ADMIN_MODERATION_NAMESPACE, resource, true, true);
  }
});

export default resources;
