import i18n from '../../i18n';

export const ADMIN_FRAUD_RISK_NAMESPACE = 'adminFraudRisk';

const resources = {
  es: {
    open: 'Abrir asistencia de riesgo', title: 'Riesgo de spam y fraude', subtitle: 'Solo asistencia · las decisiones siguen siendo humanas', close: 'Cerrar', refresh: 'Actualizar', runBatch: 'Analizar recientes', running: 'Analizando…', empty: 'No hay anuncios por encima del umbral de revisión.', loading: 'Cargando riesgo…', error: 'No se pudo cargar la asistencia de riesgo.', total: '{{count}} para revisar', score: 'Riesgo', seller: 'Vendedor', status: 'Estado', checked: 'Último análisis', reasons: 'Señales', noReasons: 'Sin señales elevadas', analyze: 'Volver a analizar', analyzing: 'Analizando…', threshold: 'Umbral {{score}}', advisory: 'Esta puntuación no bloquea, elimina ni suspende cuentas o anuncios.', provider: 'Motor', degraded: 'Modo degradado', normal: 'Python privado', fallback: 'Fallback local', unchanged: 'Estado sin cambios', unknown: 'Sin datos', batchDone: 'Lote analizado: {{count}}', ad: 'Anuncio #{{id}}', scoreAria: 'Puntuación de riesgo {{score}} de 100',
  },
  en: {
    open: 'Open risk assist', title: 'Spam and fraud risk', subtitle: 'Advisory only · decisions remain human', close: 'Close', refresh: 'Refresh', runBatch: 'Analyze recent', running: 'Analyzing…', empty: 'No listings are above the review threshold.', loading: 'Loading risk…', error: 'Could not load risk assistance.', total: '{{count}} to review', score: 'Risk', seller: 'Seller', status: 'Status', checked: 'Last analysis', reasons: 'Signals', noReasons: 'No elevated signals', analyze: 'Analyze again', analyzing: 'Analyzing…', threshold: 'Threshold {{score}}', advisory: 'This score does not block, delete, or suspend accounts or listings.', provider: 'Engine', degraded: 'Degraded mode', normal: 'Private Python', fallback: 'Local fallback', unchanged: 'Status unchanged', unknown: 'No data', batchDone: 'Batch analyzed: {{count}}', ad: 'Listing #{{id}}', scoreAria: 'Risk score {{score}} of 100',
  },
  ru: {
    open: 'Открыть оценку риска', title: 'Риск спама и мошенничества', subtitle: 'Только рекомендация · решения остаются за человеком', close: 'Закрыть', refresh: 'Обновить', runBatch: 'Проверить свежие', running: 'Анализ…', empty: 'Нет объявлений выше порога ручной проверки.', loading: 'Загрузка оценки риска…', error: 'Не удалось загрузить оценку риска.', total: 'На проверку: {{count}}', score: 'Риск', seller: 'Продавец', status: 'Статус', checked: 'Последний анализ', reasons: 'Сигналы', noReasons: 'Повышенных сигналов нет', analyze: 'Проверить снова', analyzing: 'Анализ…', threshold: 'Порог {{score}}', advisory: 'Эта оценка сама не блокирует, не удаляет и не приостанавливает аккаунты или объявления.', provider: 'Движок', degraded: 'Резервный режим', normal: 'Приватный Python', fallback: 'Локальный fallback', unchanged: 'Статус не изменён', unknown: 'Нет данных', batchDone: 'Проверено в пакете: {{count}}', ad: 'Объявление №{{id}}', scoreAria: 'Оценка риска {{score}} из 100',
  },
  pt: {
    open: 'Abrir assistência de risco', title: 'Risco de spam e fraude', subtitle: 'Somente assistência · decisões continuam humanas', close: 'Fechar', refresh: 'Atualizar', runBatch: 'Analisar recentes', running: 'Analisando…', empty: 'Nenhum anúncio acima do limite de revisão.', loading: 'Carregando risco…', error: 'Não foi possível carregar a assistência de risco.', total: '{{count}} para revisar', score: 'Risco', seller: 'Vendedor', status: 'Status', checked: 'Última análise', reasons: 'Sinais', noReasons: 'Sem sinais elevados', analyze: 'Analisar novamente', analyzing: 'Analisando…', threshold: 'Limite {{score}}', advisory: 'Esta pontuação não bloqueia, exclui ou suspende contas ou anúncios.', provider: 'Motor', degraded: 'Modo degradado', normal: 'Python privado', fallback: 'Fallback local', unchanged: 'Status inalterado', unknown: 'Sem dados', batchDone: 'Lote analisado: {{count}}', ad: 'Anúncio #{{id}}', scoreAria: 'Pontuação de risco {{score}} de 100',
  },
  fr: {
    open: 'Ouvrir l’assistance risque', title: 'Risque spam et fraude', subtitle: 'Conseil uniquement · les décisions restent humaines', close: 'Fermer', refresh: 'Actualiser', runBatch: 'Analyser les récents', running: 'Analyse…', empty: 'Aucune annonce au-dessus du seuil de vérification.', loading: 'Chargement du risque…', error: 'Impossible de charger l’assistance risque.', total: '{{count}} à vérifier', score: 'Risque', seller: 'Vendeur', status: 'Statut', checked: 'Dernière analyse', reasons: 'Signaux', noReasons: 'Aucun signal élevé', analyze: 'Analyser à nouveau', analyzing: 'Analyse…', threshold: 'Seuil {{score}}', advisory: 'Ce score ne bloque, ne supprime et ne suspend aucun compte ni aucune annonce.', provider: 'Moteur', degraded: 'Mode dégradé', normal: 'Python privé', fallback: 'Fallback local', unchanged: 'Statut inchangé', unknown: 'Aucune donnée', batchDone: 'Lot analysé : {{count}}', ad: 'Annonce n°{{id}}', scoreAria: 'Score de risque {{score}} sur 100',
  },
  de: {
    open: 'Risikohilfe öffnen', title: 'Spam- und Betrugsrisiko', subtitle: 'Nur Beratung · Entscheidungen bleiben menschlich', close: 'Schließen', refresh: 'Aktualisieren', runBatch: 'Neue prüfen', running: 'Analyse…', empty: 'Keine Anzeigen über der Prüfschwelle.', loading: 'Risiko wird geladen…', error: 'Risikohilfe konnte nicht geladen werden.', total: '{{count}} zu prüfen', score: 'Risiko', seller: 'Verkäufer', status: 'Status', checked: 'Letzte Analyse', reasons: 'Signale', noReasons: 'Keine erhöhten Signale', analyze: 'Erneut analysieren', analyzing: 'Analyse…', threshold: 'Schwelle {{score}}', advisory: 'Dieser Wert sperrt, löscht oder pausiert keine Konten oder Anzeigen.', provider: 'Engine', degraded: 'Degradierter Modus', normal: 'Privates Python', fallback: 'Lokaler Fallback', unchanged: 'Status unverändert', unknown: 'Keine Daten', batchDone: 'Batch analysiert: {{count}}', ad: 'Anzeige #{{id}}', scoreAria: 'Risikowert {{score}} von 100',
  },
  it: {
    open: 'Apri assistenza rischio', title: 'Rischio spam e frode', subtitle: 'Solo assistenza · le decisioni restano umane', close: 'Chiudi', refresh: 'Aggiorna', runBatch: 'Analizza recenti', running: 'Analisi…', empty: 'Nessun annuncio sopra la soglia di revisione.', loading: 'Caricamento rischio…', error: 'Impossibile caricare l’assistenza rischio.', total: '{{count}} da verificare', score: 'Rischio', seller: 'Venditore', status: 'Stato', checked: 'Ultima analisi', reasons: 'Segnali', noReasons: 'Nessun segnale elevato', analyze: 'Analizza di nuovo', analyzing: 'Analisi…', threshold: 'Soglia {{score}}', advisory: 'Questo punteggio non blocca, elimina o sospende account o annunci.', provider: 'Motore', degraded: 'Modalità degradata', normal: 'Python privato', fallback: 'Fallback locale', unchanged: 'Stato invariato', unknown: 'Nessun dato', batchDone: 'Lotto analizzato: {{count}}', ad: 'Annuncio #{{id}}', scoreAria: 'Punteggio rischio {{score}} su 100',
  },
  zh: {
    open: '打开风险辅助', title: '垃圾信息与欺诈风险', subtitle: '仅提供辅助 · 最终决定由人工做出', close: '关闭', refresh: '刷新', runBatch: '分析近期项目', running: '分析中…', empty: '没有超过人工审核阈值的广告。', loading: '正在加载风险…', error: '无法加载风险辅助。', total: '{{count}} 个待审核', score: '风险', seller: '卖家', status: '状态', checked: '上次分析', reasons: '信号', noReasons: '没有高风险信号', analyze: '重新分析', analyzing: '分析中…', threshold: '阈值 {{score}}', advisory: '此分数不会自动封禁、删除或暂停账号或广告。', provider: '引擎', degraded: '降级模式', normal: '私有 Python', fallback: '本地回退', unchanged: '状态未更改', unknown: '无数据', batchDone: '批量分析：{{count}}', ad: '广告 #{{id}}', scoreAria: '风险分数 {{score}}/100',
  },
  ko: {
    open: '위험 보조 열기', title: '스팸 및 사기 위험', subtitle: '보조 전용 · 최종 결정은 사람이 합니다', close: '닫기', refresh: '새로고침', runBatch: '최근 항목 분석', running: '분석 중…', empty: '검토 임계값을 넘는 광고가 없습니다.', loading: '위험 로딩 중…', error: '위험 보조를 불러올 수 없습니다.', total: '{{count}}개 검토', score: '위험', seller: '판매자', status: '상태', checked: '최근 분석', reasons: '신호', noReasons: '높은 신호 없음', analyze: '다시 분석', analyzing: '분석 중…', threshold: '임계값 {{score}}', advisory: '이 점수만으로 계정이나 광고를 차단, 삭제, 중지하지 않습니다.', provider: '엔진', degraded: '저하 모드', normal: '비공개 Python', fallback: '로컬 폴백', unchanged: '상태 변경 없음', unknown: '데이터 없음', batchDone: '일괄 분석: {{count}}', ad: '광고 #{{id}}', scoreAria: '위험 점수 {{score}}/100',
  },
  ja: {
    open: 'リスク支援を開く', title: 'スパム・詐欺リスク', subtitle: '助言のみ · 最終判断は人が行います', close: '閉じる', refresh: '更新', runBatch: '最近を分析', running: '分析中…', empty: '確認しきい値を超える広告はありません。', loading: 'リスクを読み込み中…', error: 'リスク支援を読み込めませんでした。', total: '{{count}}件を確認', score: 'リスク', seller: '出品者', status: '状態', checked: '最終分析', reasons: 'シグナル', noReasons: '高いシグナルなし', analyze: '再分析', analyzing: '分析中…', threshold: 'しきい値 {{score}}', advisory: 'このスコアだけでアカウントや広告を停止・削除することはありません。', provider: 'エンジン', degraded: '縮退モード', normal: 'プライベート Python', fallback: 'ローカル fallback', unchanged: '状態は変更されていません', unknown: 'データなし', batchDone: '一括分析: {{count}}', ad: '広告 #{{id}}', scoreAria: 'リスクスコア {{score}}/100',
  },
  ar: {
    open: 'فتح مساعد المخاطر', title: 'مخاطر الرسائل المزعجة والاحتيال', subtitle: 'للمساعدة فقط · القرار النهائي بشري', close: 'إغلاق', refresh: 'تحديث', runBatch: 'تحليل الأحدث', running: 'جارٍ التحليل…', empty: 'لا توجد إعلانات فوق عتبة المراجعة.', loading: 'جارٍ تحميل المخاطر…', error: 'تعذر تحميل مساعد المخاطر.', total: '{{count}} للمراجعة', score: 'المخاطر', seller: 'البائع', status: 'الحالة', checked: 'آخر تحليل', reasons: 'الإشارات', noReasons: 'لا توجد إشارات مرتفعة', analyze: 'إعادة التحليل', analyzing: 'جارٍ التحليل…', threshold: 'العتبة {{score}}', advisory: 'هذه الدرجة لا تحظر أو تحذف أو توقف الحسابات أو الإعلانات تلقائياً.', provider: 'المحرك', degraded: 'وضع مخفّض', normal: 'Python خاص', fallback: 'بديل محلي', unchanged: 'الحالة لم تتغير', unknown: 'لا بيانات', batchDone: 'تم تحليل الدفعة: {{count}}', ad: 'الإعلان #{{id}}', scoreAria: 'درجة المخاطر {{score}} من 100',
  },
};

Object.entries(resources).forEach(([language, resource]) => {
  if (!i18n.hasResourceBundle(language, ADMIN_FRAUD_RISK_NAMESPACE)) {
    i18n.addResourceBundle(language, ADMIN_FRAUD_RISK_NAMESPACE, resource, true, true);
  }
});

export default resources;
