import { normalizeLanguage } from './translations.js';

const ADMIN_SURFACE_COPY = {
  "es": {
    "admin_by": "Por:",
    "admin_promotion_revenue_30d": "Ingresos por promociones — 30 días",
    "admin_promotion_products": "Subir / Resaltar / Destacado",
    "admin_global_ctr": "CTR global",
    "admin_business_verifications_pending": "Verificaciones RFC / CSF pendientes",
    "admin_business_verifications_desc": "Casos que la AI marcó para revisión manual (dudosos o rechazados).",
    "admin_plan": "Plan",
    "admin_email_phone_pending": "Email/teléfono pendiente",
    "admin_anonymous": "Anónimo",
    "admin_discard_report": "Descartar reporte",
    "admin_email_ip": "Email / IP",
    "deleteUserConfirm": "Eliminar este usuario permanentemente?",
    "deleteUserError": "No se pudo eliminar el usuario.",
    "changeRoleConfirm": "Cambiar el rol a {role}?",
    "changeRoleError": "No se pudo cambiar el rol.",
    "rejectReasonPrompt": "Indica el motivo del rechazo:",
    "deleteReportConfirm": "Eliminar este reporte?",
    "deleteUserReportConfirm": "Eliminar este reporte de usuario?",
    "couponCreated": "Cupón creado.",
    "couponCreateError": "No se pudo crear el cupón.",
    "couponDeleteConfirm": "Eliminar este cupón?",
    "categorySaved": "Categoría guardada.",
    "categorySaveError": "No se pudo guardar la categoría.",
    "roleIndividual": "Particular",
    "roleBusiness": "Negocio (PRO)",
    "roleAdmin": "Admin"
  },
  "en": {
    "admin_by": "By:",
    "admin_promotion_revenue_30d": "Promotion revenue — 30 days",
    "admin_promotion_products": "Boost / Highlight / Featured",
    "admin_global_ctr": "Global CTR",
    "admin_business_verifications_pending": "Pending RFC / CSF verifications",
    "admin_business_verifications_desc": "Cases flagged by AI for manual review (uncertain or rejected).",
    "admin_plan": "Plan",
    "admin_email_phone_pending": "Pending email/phone verification",
    "admin_anonymous": "Anonymous",
    "admin_discard_report": "Dismiss report",
    "admin_email_ip": "Email / IP",
    "deleteUserConfirm": "Delete this user permanently?",
    "deleteUserError": "Could not delete user.",
    "changeRoleConfirm": "Change role to {role}?",
    "changeRoleError": "Could not change role.",
    "rejectReasonPrompt": "Indicate the reason for the rejection:",
    "deleteReportConfirm": "Delete this report?",
    "deleteUserReportConfirm": "Delete this user report?",
    "couponCreated": "Coupon created.",
    "couponCreateError": "Coupon could not be created.",
    "couponDeleteConfirm": "Delete this coupon?",
    "categorySaved": "Category saved.",
    "categorySaveError": "The category could not be saved.",
    "roleIndividual": "Individual",
    "roleBusiness": "Business (PRO)",
    "roleAdmin": "Admin"
  },
  "pt": {
    "admin_by": "Por:",
    "admin_promotion_revenue_30d": "Receita de promoções – 30 dias",
    "admin_promotion_products": "Impulsionar / Destacar / Em evidência",
    "admin_global_ctr": "CTR global",
    "admin_business_verifications_pending": "Verificações RFC / CSF pendentes",
    "admin_business_verifications_desc": "Casos que a AI marcou para revisão manual (duvidosos ou rejeitados).",
    "admin_plan": "Plano",
    "admin_email_phone_pending": "Verificação de e-mail/telefone pendente",
    "admin_anonymous": "Anônimo",
    "admin_discard_report": "Descartar denúncia",
    "admin_email_ip": "E-mail / IP",
    "deleteUserConfirm": "Excluir este usuário permanentemente?",
    "deleteUserError": "Não foi possível excluir o usuário.",
    "changeRoleConfirm": "Alterar função para {role}?",
    "changeRoleError": "Não foi possível alterar a função.",
    "rejectReasonPrompt": "Indique o motivo da rejeição:",
    "deleteReportConfirm": "Excluir esta denúncia?",
    "deleteUserReportConfirm": "Excluir esta denúncia de usuário?",
    "couponCreated": "Cupom criado.",
    "couponCreateError": "Não foi possível criar o cupom.",
    "couponDeleteConfirm": "Excluir este cupom?",
    "categorySaved": "Categoria salva.",
    "categorySaveError": "A categoria não pôde ser salva.",
    "roleIndividual": "Particular",
    "roleBusiness": "Empresa (PRO)",
    "roleAdmin": "Admin"
  },
  "fr": {
    "admin_by": "Par :",
    "admin_promotion_revenue_30d": "Revenus des promotions — 30 jours",
    "admin_promotion_products": "Boost / Mise en avant / Vedette",
    "admin_global_ctr": "CTR global",
    "admin_business_verifications_pending": "En attente de vérifications RFC / CSF",
    "admin_business_verifications_desc": "Cas signalés par AI pour vérification manuelle (incertains ou rejetés).",
    "admin_plan": "Plan",
    "admin_email_phone_pending": "Vérification e-mail/téléphone en attente",
    "admin_anonymous": "Anonyme",
    "admin_discard_report": "Supprimer le signalement",
    "admin_email_ip": "E-mail / IP",
    "deleteUserConfirm": "Supprimer définitivement cet utilisateur ?",
    "deleteUserError": "Impossible de supprimer l'utilisateur.",
    "changeRoleConfirm": "Changer de rôle pour {role} ?",
    "changeRoleError": "Impossible de changer de rôle.",
    "rejectReasonPrompt": "Indiquez le motif du refus :",
    "deleteReportConfirm": "Supprimer ce signalement ?",
    "deleteUserReportConfirm": "Supprimer ce signalement utilisateur ?",
    "couponCreated": "Coupon créé.",
    "couponCreateError": "Le coupon n'a pas pu être créé.",
    "couponDeleteConfirm": "Supprimer ce coupon ?",
    "categorySaved": "Catégorie enregistrée.",
    "categorySaveError": "La catégorie n'a pas pu être enregistrée.",
    "roleIndividual": "Particulier",
    "roleBusiness": "Entreprise (PRO)",
    "roleAdmin": "Administrateur"
  },
  "zh": {
    "admin_by": "发布者：",
    "admin_promotion_revenue_30d": "促销收入 — 30 天",
    "admin_promotion_products": "提升 / 高亮 / 精选",
    "admin_global_ctr": "全局 CTR",
    "admin_business_verifications_pending": "待定 RFC / CSF 验证",
    "admin_business_verifications_desc": "AI 标记为人工审核（可疑或拒绝）的案例。",
    "admin_plan": "套餐",
    "admin_email_phone_pending": "等待邮箱/电话验证",
    "admin_anonymous": "匿名",
    "admin_discard_report": "删除举报",
    "admin_email_ip": "邮箱 / IP",
    "deleteUserConfirm": "永久删除该用户？",
    "deleteUserError": "无法删除用户。",
    "changeRoleConfirm": "将角色更改为 {role}？",
    "changeRoleError": "无法更改角色。",
    "rejectReasonPrompt": "请输入拒绝原因：",
    "deleteReportConfirm": "删除此举报？",
    "deleteUserReportConfirm": "删除此用户举报？",
    "couponCreated": "优惠券已创建。",
    "couponCreateError": "无法创建优惠券。",
    "couponDeleteConfirm": "删除此优惠券吗？",
    "categorySaved": "类别已保存。",
    "categorySaveError": "无法保存该类别。",
    "roleIndividual": "个人",
    "roleBusiness": "商家 (PRO)",
    "roleAdmin": "管理员"
  },
  "ko": {
    "admin_by": "게시자:",
    "admin_promotion_revenue_30d": "판촉 수입 — 30일",
    "admin_promotion_products": "상단 노출 / 강조 / 추천",
    "admin_global_ctr": "전체 CTR",
    "admin_business_verifications_pending": "RFC / CSF 확인 보류 중",
    "admin_business_verifications_desc": "AI가 수동 검토 대상으로 표시한 사례(의심 또는 거부).",
    "admin_plan": "요금제",
    "admin_email_phone_pending": "이메일/전화 인증 대기 중",
    "admin_anonymous": "익명",
    "admin_discard_report": "신고 삭제",
    "admin_email_ip": "이메일 / IP",
    "deleteUserConfirm": "이 사용자를 영구적으로 삭제하시겠습니까?",
    "deleteUserError": "사용자를 삭제할 수 없습니다.",
    "changeRoleConfirm": "역할을 {role}로 변경하시겠습니까?",
    "changeRoleError": "역할을 변경할 수 없습니다.",
    "rejectReasonPrompt": "거부 사유를 입력하세요.",
    "deleteReportConfirm": "이 신고를 삭제하시겠습니까?",
    "deleteUserReportConfirm": "이 사용자 신고를 삭제하시겠습니까?",
    "couponCreated": "쿠폰이 생성되었습니다.",
    "couponCreateError": "쿠폰을 생성할 수 없습니다.",
    "couponDeleteConfirm": "이 쿠폰을 삭제하시겠습니까?",
    "categorySaved": "카테고리가 저장되었습니다.",
    "categorySaveError": "카테고리를 저장할 수 없습니다.",
    "roleIndividual": "개인",
    "roleBusiness": "비즈니스 (PRO)",
    "roleAdmin": "관리자"
  },
  "de": {
    "admin_by": "Von:",
    "admin_promotion_revenue_30d": "Einnahmen aus Werbeaktionen – 30 Tage",
    "admin_promotion_products": "Hochstufen / Hervorheben / Featured",
    "admin_global_ctr": "CTR global",
    "admin_business_verifications_pending": "Ausstehende RFC / CSF-Verifizierungen",
    "admin_business_verifications_desc": "Von AI zur manuellen Prüfung markierte Fälle (unklar oder abgelehnt).",
    "admin_plan": "Tarif",
    "admin_email_phone_pending": "E-Mail-/Telefonverifizierung ausstehend",
    "admin_anonymous": "Anonym",
    "admin_discard_report": "Meldung verwerfen",
    "admin_email_ip": "E-Mail / IP",
    "deleteUserConfirm": "Diesen Benutzer dauerhaft löschen?",
    "deleteUserError": "Benutzer konnte nicht gelöscht werden.",
    "changeRoleConfirm": "Rolle in {role} ändern?",
    "changeRoleError": "Die Rolle konnte nicht geändert werden.",
    "rejectReasonPrompt": "Geben Sie den Grund für die Ablehnung an:",
    "deleteReportConfirm": "Diese Meldung löschen?",
    "deleteUserReportConfirm": "Diese Benutzermeldung löschen?",
    "couponCreated": "Gutschein erstellt.",
    "couponCreateError": "Gutschein konnte nicht erstellt werden.",
    "couponDeleteConfirm": "Diesen Gutschein löschen?",
    "categorySaved": "Kategorie gespeichert.",
    "categorySaveError": "Die Kategorie konnte nicht gespeichert werden.",
    "roleIndividual": "Privat",
    "roleBusiness": "Unternehmen (PRO)",
    "roleAdmin": "Admin"
  },
  "it": {
    "admin_by": "Di:",
    "admin_promotion_revenue_30d": "Entrate da promozioni — 30 giorni",
    "admin_promotion_products": "Boost / Evidenzia / In primo piano",
    "admin_global_ctr": "CTR globale",
    "admin_business_verifications_pending": "In attesa di verifiche RFC / CSF",
    "admin_business_verifications_desc": "Casi contrassegnati da AI per revisione manuale (dubbi o rifiutati).",
    "admin_plan": "Piano",
    "admin_email_phone_pending": "Verifica e-mail/telefono in attesa",
    "admin_anonymous": "Anonimo",
    "admin_discard_report": "Elimina segnalazione",
    "admin_email_ip": "E-mail / IP",
    "deleteUserConfirm": "Eliminare questo utente in modo permanente?",
    "deleteUserError": "Impossibile eliminare l'utente.",
    "changeRoleConfirm": "Cambiare il ruolo in {role}?",
    "changeRoleError": "Impossibile cambiare ruolo.",
    "rejectReasonPrompt": "Indicare il motivo del rifiuto:",
    "deleteReportConfirm": "Eliminare questa segnalazione?",
    "deleteUserReportConfirm": "Eliminare questa segnalazione utente?",
    "couponCreated": "Coupon creato.",
    "couponCreateError": "Impossibile creare il coupon.",
    "couponDeleteConfirm": "Eliminare questo coupon?",
    "categorySaved": "Categoria salvata.",
    "categorySaveError": "Impossibile salvare la categoria.",
    "roleIndividual": "Privato",
    "roleBusiness": "Azienda (PRO)",
    "roleAdmin": "Admin"
  },
  "ar": {
    "admin_by": "بواسطة:",
    "admin_promotion_revenue_30d": "الدخل من العروض الترويجية — 30 يومًا",
    "admin_promotion_products": "رفع / إبراز / مميز",
    "admin_global_ctr": "CTR الإجمالي",
    "admin_business_verifications_pending": "في انتظار التحقق من RFC / CSF",
    "admin_business_verifications_desc": "حالات وضعت AI علامة عليها للمراجعة اليدوية (مشكوك فيها أو مرفوضة).",
    "admin_plan": "الخطة",
    "admin_email_phone_pending": "بانتظار التحقق من البريد الإلكتروني/الهاتف",
    "admin_anonymous": "مجهول",
    "admin_discard_report": "حذف البلاغ",
    "admin_email_ip": "البريد الإلكتروني / IP",
    "deleteUserConfirm": "هل تريد حذف هذا المستخدم نهائيًا؟",
    "deleteUserError": "لا يمكن حذف المستخدم.",
    "changeRoleConfirm": "هل تريد تغيير الدور إلى {role}؟",
    "changeRoleError": "لا يمكن تغيير الدور.",
    "rejectReasonPrompt": "اذكر سبب الرفض:",
    "deleteReportConfirm": "هل تريد حذف هذا البلاغ؟",
    "deleteUserReportConfirm": "هل تريد حذف هذا البلاغ عن المستخدم؟",
    "couponCreated": "تم إنشاء القسيمة.",
    "couponCreateError": "لا يمكن إنشاء القسيمة.",
    "couponDeleteConfirm": "هل تريد حذف هذه القسيمة؟",
    "categorySaved": "تم حفظ الفئة.",
    "categorySaveError": "لا يمكن حفظ الفئة.",
    "roleIndividual": "فرد",
    "roleBusiness": "نشاط تجاري (PRO)",
    "roleAdmin": "مشرف"
  },
  "ru": {
    "admin_by": "Автор:",
    "admin_promotion_revenue_30d": "Доход от промоакций — 30 дней",
    "admin_promotion_products": "Поднять / Выделить / Рекомендуемое",
    "admin_global_ctr": "Общий CTR",
    "admin_business_verifications_pending": "Ожидающие проверки RFC / CSF",
    "admin_business_verifications_desc": "Случаи, которые AI отправил на ручную проверку (сомнительные или отклонённые).",
    "admin_plan": "План",
    "admin_email_phone_pending": "Ожидается подтверждение email/телефона",
    "admin_anonymous": "Анонимно",
    "admin_discard_report": "Удалить жалобу",
    "admin_email_ip": "Email / IP",
    "deleteUserConfirm": "Удалить этого пользователя навсегда?",
    "deleteUserError": "Не удалось удалить пользователя.",
    "changeRoleConfirm": "Изменить роль на {role}?",
    "changeRoleError": "Не удалось сменить роль.",
    "rejectReasonPrompt": "Укажите причину отклонения:",
    "deleteReportConfirm": "Удалить эту жалобу?",
    "deleteUserReportConfirm": "Удалить эту жалобу на пользователя?",
    "couponCreated": "Купон создан.",
    "couponCreateError": "Купон не удалось создать.",
    "couponDeleteConfirm": "Удалить этот купон?",
    "categorySaved": "Категория сохранена.",
    "categorySaveError": "Не удалось сохранить категорию.",
    "roleIndividual": "Частное лицо",
    "roleBusiness": "Бизнес (PRO)",
    "roleAdmin": "Администратор"
  },
  "ja": {
    "admin_by": "投稿者：",
    "admin_promotion_revenue_30d": "プロモーションによる収入 — 30 日",
    "admin_promotion_products": "上位表示 / ハイライト / 注目",
    "admin_global_ctr": "全体 CTR",
    "admin_business_verifications_pending": "RFC / CSF 検証が保留中です",
    "admin_business_verifications_desc": "AI が手動確認対象としてマークしたケース（不明確または却下済み）。",
    "admin_plan": "プラン",
    "admin_email_phone_pending": "メール/電話の確認待ち",
    "admin_anonymous": "匿名",
    "admin_discard_report": "通報を削除",
    "admin_email_ip": "メール / IP",
    "deleteUserConfirm": "このユーザーを完全に削除しますか?",
    "deleteUserError": "ユーザーを削除できませんでした。",
    "changeRoleConfirm": "役割を {role} に変更しますか?",
    "changeRoleError": "役割を変更できませんでした。",
    "rejectReasonPrompt": "却下理由を入力してください：",
    "deleteReportConfirm": "この通報を削除しますか？",
    "deleteUserReportConfirm": "このユーザーへの通報を削除しますか？",
    "couponCreated": "クーポンが作成されました。",
    "couponCreateError": "クーポンを作成できませんでした。",
    "couponDeleteConfirm": "このクーポンを削除しますか?",
    "categorySaved": "カテゴリを保存しました。",
    "categorySaveError": "カテゴリを保存できませんでした。",
    "roleIndividual": "個人",
    "roleBusiness": "ビジネス (PRO)",
    "roleAdmin": "管理者"
  }
};

export function getAdminSurfaceCopy(language = 'es') {
  return ADMIN_SURFACE_COPY[normalizeLanguage(language)] || ADMIN_SURFACE_COPY.es;
}

export { ADMIN_SURFACE_COPY };
