import { normalizeLanguage } from './translations.js';

const copy = {
  es: {
    subsections: ['Autos', 'Motos', 'Camionetas', 'Camiones', 'Refacciones', 'Segunda mano', 'Autopartes'],
    conditions: { nuevo: 'Nuevo', usado: 'Usado' },
    applyFilters: 'Aplicar filtros →',
    mapTitle: 'Autos en el mapa',
    mapDescription: 'Explora vehículos por ubicación, precio y coordenadas GPS.',
    mapMarkerTitle: 'Autos en México',
    stats: [
      ['Todo México', 'Busca por estado y ciudad'],
      ['Directo', 'Contacto con el vendedor'],
      ['32 estados', 'Cobertura de búsqueda'],
      ['Gratis', 'Publicar anuncio'],
    ],
    brandsTitle: 'Marcas populares',
    sellTitle: 'Quieres vender tu auto?',
    sellBody: 'Publica gratis en minutos y llega a miles de compradores en México.',
    sellButton: 'Publicar anuncio gratis →',
  },
  en: {
    subsections: ['Cars', 'Motorcycles', 'Pickups & SUVs', 'Trucks', 'Spare parts', 'Used vehicles', 'Auto parts'],
    conditions: { nuevo: 'New', usado: 'Used' },
    applyFilters: 'Apply filters →',
    mapTitle: 'Cars on the map',
    mapDescription: 'Explore vehicles by location, price and GPS coordinates.',
    mapMarkerTitle: 'Cars in Mexico',
    stats: [
      ['All Mexico', 'Search by state and city'],
      ['Direct', 'Contact the seller'],
      ['32 states', 'Search coverage'],
      ['Free', 'Post an ad'],
    ],
    brandsTitle: 'Popular brands',
    sellTitle: 'Want to sell your car?',
    sellBody: 'Post for free in minutes and reach thousands of buyers in Mexico.',
    sellButton: 'Post a free ad →',
  },
  pt: {
    subsections: ['Carros', 'Motos', 'Caminhonetes e SUVs', 'Caminhões', 'Peças de reposição', 'Veículos usados', 'Autopeças'],
    conditions: { nuevo: 'Novo', usado: 'Usado' },
    applyFilters: 'Aplicar filtros →',
    mapTitle: 'Carros no mapa',
    mapDescription: 'Explore veículos por localização, preço e coordenadas GPS.',
    mapMarkerTitle: 'Carros no México',
    stats: [
      ['Todo o México', 'Busque por estado e cidade'],
      ['Direto', 'Contato com o vendedor'],
      ['32 estados', 'Cobertura de busca'],
      ['Grátis', 'Publicar anúncio'],
    ],
    brandsTitle: 'Marcas populares',
    sellTitle: 'Quer vender seu carro?',
    sellBody: 'Publique grátis em minutos e alcance milhares de compradores no México.',
    sellButton: 'Publicar anúncio grátis →',
  },
  fr: {
    subsections: ['Voitures', 'Motos', 'Pick-up et SUV', 'Camions', 'Pièces détachées', 'Véhicules d’occasion', 'Pièces auto'],
    conditions: { nuevo: 'Neuf', usado: 'Occasion' },
    applyFilters: 'Appliquer les filtres →',
    mapTitle: 'Voitures sur la carte',
    mapDescription: 'Explorez les véhicules par lieu, prix et coordonnées GPS.',
    mapMarkerTitle: 'Voitures au Mexique',
    stats: [
      ['Tout le Mexique', 'Recherchez par État et ville'],
      ['Direct', 'Contact avec le vendeur'],
      ['32 États', 'Couverture de recherche'],
      ['Gratuit', 'Publier une annonce'],
    ],
    brandsTitle: 'Marques populaires',
    sellTitle: 'Vous voulez vendre votre voiture ?',
    sellBody: 'Publiez gratuitement en quelques minutes et touchez des milliers d’acheteurs au Mexique.',
    sellButton: 'Publier une annonce gratuitement →',
  },
  zh: {
    subsections: ['汽车', '摩托车', '皮卡和 SUV', '卡车', '零配件', '二手车', '汽车配件'],
    conditions: { nuevo: '新车', usado: '二手' },
    applyFilters: '应用筛选 →',
    mapTitle: '地图上的汽车',
    mapDescription: '按位置、价格和 GPS 坐标浏览车辆。',
    mapMarkerTitle: '墨西哥汽车',
    stats: [
      ['墨西哥全境', '按州和城市搜索'],
      ['直接联系', '联系卖家'],
      ['32 个州', '搜索覆盖'],
      ['免费', '发布广告'],
    ],
    brandsTitle: '热门品牌',
    sellTitle: '想卖车吗？',
    sellBody: '几分钟内免费发布，触达墨西哥数千名买家。',
    sellButton: '免费发布广告 →',
  },
  ko: {
    subsections: ['자동차', '오토바이', '픽업·SUV', '트럭', '교체 부품', '중고차', '자동차 부품'],
    conditions: { nuevo: '신차', usado: '중고' },
    applyFilters: '필터 적용 →',
    mapTitle: '지도에서 자동차 보기',
    mapDescription: '위치, 가격, GPS 좌표로 차량을 둘러보세요.',
    mapMarkerTitle: '멕시코 자동차',
    stats: [
      ['멕시코 전역', '주 및 도시로 검색'],
      ['직접', '판매자와 직접 연락'],
      ['32개 주', '검색 범위'],
      ['무료', '광고 등록'],
    ],
    brandsTitle: '인기 브랜드',
    sellTitle: '자동차를 판매하시나요?',
    sellBody: '몇 분 안에 무료로 등록하고 멕시코의 수천 명 구매자에게 도달하세요.',
    sellButton: '무료 광고 등록 →',
  },
  de: {
    subsections: ['Autos', 'Motorräder', 'Pick-ups & SUVs', 'LKWs', 'Ersatzteile', 'Gebrauchtwagen', 'Autoteile'],
    conditions: { nuevo: 'Neu', usado: 'Gebraucht' },
    applyFilters: 'Filter anwenden →',
    mapTitle: 'Autos auf der Karte',
    mapDescription: 'Fahrzeuge nach Standort, Preis und GPS-Koordinaten entdecken.',
    mapMarkerTitle: 'Autos in Mexiko',
    stats: [
      ['Ganz Mexiko', 'Nach Bundesstaat und Stadt suchen'],
      ['Direkt', 'Kontakt mit dem Verkäufer'],
      ['32 Bundesstaaten', 'Suchabdeckung'],
      ['Kostenlos', 'Anzeige aufgeben'],
    ],
    brandsTitle: 'Beliebte Marken',
    sellTitle: 'Möchten Sie Ihr Auto verkaufen?',
    sellBody: 'In wenigen Minuten kostenlos inserieren und Tausende Käufer in Mexiko erreichen.',
    sellButton: 'Kostenlose Anzeige aufgeben →',
  },
  it: {
    subsections: ['Auto', 'Moto', 'Pick-up e SUV', 'Camion', 'Ricambi', 'Veicoli usati', 'Componenti auto'],
    conditions: { nuevo: 'Nuovo', usado: 'Usato' },
    applyFilters: 'Applica filtri →',
    mapTitle: 'Auto sulla mappa',
    mapDescription: 'Esplora veicoli per posizione, prezzo e coordinate GPS.',
    mapMarkerTitle: 'Auto in Messico',
    stats: [
      ['Tutto il Messico', 'Cerca per stato e città'],
      ['Diretto', 'Contatto con il venditore'],
      ['32 stati', 'Copertura di ricerca'],
      ['Gratis', 'Pubblica annuncio'],
    ],
    brandsTitle: 'Marche popolari',
    sellTitle: 'Vuoi vendere la tua auto?',
    sellBody: 'Pubblica gratis in pochi minuti e raggiungi migliaia di acquirenti in Messico.',
    sellButton: 'Pubblica annuncio gratis →',
  },
  ar: {
    subsections: ['سيارات', 'دراجات نارية', 'بيك أب وSUV', 'شاحنات', 'قطع غيار', 'سيارات مستعملة', 'قطع سيارات'],
    conditions: { nuevo: 'جديد', usado: 'مستعمل' },
    applyFilters: 'تطبيق الفلاتر ←',
    mapTitle: 'السيارات على الخريطة',
    mapDescription: 'استكشف المركبات حسب الموقع والسعر وإحداثيات GPS.',
    mapMarkerTitle: 'سيارات في المكسيك',
    stats: [
      ['كل المكسيك', 'ابحث حسب الولاية والمدينة'],
      ['مباشر', 'تواصل مع البائع'],
      ['32 ولاية', 'تغطية البحث'],
      ['مجانًا', 'نشر إعلان'],
    ],
    brandsTitle: 'العلامات التجارية الشائعة',
    sellTitle: 'هل تريد بيع سيارتك؟',
    sellBody: 'انشر مجانًا خلال دقائق وصل إلى آلاف المشترين في المكسيك.',
    sellButton: 'نشر إعلان مجانًا ←',
  },
  ru: {
    subsections: ['Автомобили', 'Мотоциклы', 'Пикапы и SUV', 'Грузовики', 'Запчасти', 'Подержанные', 'Автокомпоненты'],
    conditions: { nuevo: 'Новые', usado: 'Б/у' },
    applyFilters: 'Применить фильтры →',
    mapTitle: 'Автомобили на карте',
    mapDescription: 'Ищите транспорт по местоположению, цене и GPS-координатам.',
    mapMarkerTitle: 'Автомобили в Мексике',
    stats: [
      ['Вся Мексика', 'Поиск по штату и городу'],
      ['Напрямую', 'Связь с продавцом'],
      ['32 штата', 'Охват поиска'],
      ['Бесплатно', 'Разместить объявление'],
    ],
    brandsTitle: 'Популярные марки',
    sellTitle: 'Хотите продать автомобиль?',
    sellBody: 'Разместите бесплатно за несколько минут и покажите объявление тысячам покупателей в Мексике.',
    sellButton: 'Разместить бесплатно →',
  },
  ja: {
    subsections: ['車', 'バイク', 'ピックアップ・SUV', 'トラック', '交換部品', '中古車', '自動車部品'],
    conditions: { nuevo: '新車', usado: '中古' },
    applyFilters: 'フィルターを適用 →',
    mapTitle: '地図上の車',
    mapDescription: '場所、価格、GPS座標から車両を探せます。',
    mapMarkerTitle: 'メキシコの車',
    stats: [
      ['メキシコ全域', '州・都市で検索'],
      ['直接', '販売者に直接連絡'],
      ['32州', '検索範囲'],
      ['無料', '広告を掲載'],
    ],
    brandsTitle: '人気メーカー',
    sellTitle: '車を売りたいですか？',
    sellBody: '数分で無料掲載し、メキシコの何千人もの購入者に届けられます。',
    sellButton: '無料で広告を掲載 →',
  },
};

export function getAutosLandingCopy(language) {
  const lang = normalizeLanguage(language);
  return copy[lang] || copy.es;
}

export function hasAutosLandingCopy(language) {
  const lang = String(language || '').toLowerCase().split('-')[0];
  return Boolean(copy[lang]);
}

export default copy;
