import { normalizeLanguage } from './translations.js';

export const CONTACT_SUBJECT_VALUES = Object.freeze(["Reporte de anuncio", "Problema técnico", "Sugerencia", "Otro"]);

const CONTACT_PAGE_COPY = Object.freeze({
  "es": {
    "seoTitle": "Contacto | Mercasto",
    "seoDescription": "Consulta los canales oficiales para contactar al equipo de Mercasto sobre soporte, seguridad, moderación o tu cuenta.",
    "breadcrumb": "Contacto",
    "title": "Contáctanos",
    "subtitle": "Estamos aquí para ayudarte. Escríbenos por los canales oficiales de contacto.",
    "formTitle": "Envíanos un mensaje",
    "successTitle": "Mensaje enviado!",
    "successMessage": "Mensaje recibido. Nuestro equipo lo revisará.",
    "genericError": "No pudimos enviar el mensaje. Inténtalo más tarde.",
    "name": "Nombre",
    "namePlaceholder": "Tu nombre completo",
    "email": "Correo electrónico",
    "emailPlaceholder": "tu@correo.com",
    "subject": "Asunto",
    "subjectPlaceholder": "Selecciona un asunto...",
    "message": "Mensaje",
    "messagePlaceholder": "Cuéntanos en qué podemos ayudarte...",
    "sending": "Enviando...",
    "send": "Enviar mensaje",
    "emailCardTitle": "Correo electrónico",
    "emailCardSub": "Para consultas generales",
    "responseTitle": "Tiempo de respuesta",
    "responseValue": "Sin plazo fijo",
    "responseSub": "Depende del tipo y la prioridad de la consulta",
    "followUs": "Síguenos",
    "faqTitle": "Tienes preguntas?",
    "faqBody": "Visita nuestro Centro de Ayuda con respuestas a las preguntas más frecuentes.",
    "faqLink": "Ir al Centro de Ayuda",
    "nameRequired": "El nombre es requerido.",
    "emailRequired": "El correo es requerido.",
    "emailInvalid": "Correo no válido.",
    "subjectRequired": "Selecciona un asunto.",
    "messageRequired": "El mensaje es requerido.",
    "messageMin": "Escribe al menos 10 caracteres.",
    "subjects": [
      "🚩 Reporte de anuncio",
      "🔧 Problema técnico",
      "💡 Sugerencia",
      "📋 Otro"
    ]
  },
  "en": {
    "seoTitle": "Contact | Mercasto",
    "seoDescription": "Use Mercasto official contact channels for support, safety, moderation or account questions.",
    "breadcrumb": "Contact",
    "title": "Contact us",
    "subtitle": "We are here to help. Write to us through our official contact channels.",
    "formTitle": "Send us a message",
    "successTitle": "Message sent!",
    "successMessage": "We received your message. Our team will review it.",
    "genericError": "We could not send your message. Try again later.",
    "name": "Name",
    "namePlaceholder": "Your full name",
    "email": "Email",
    "emailPlaceholder": "you@email.com",
    "subject": "Subject",
    "subjectPlaceholder": "Choose a subject...",
    "message": "Message",
    "messagePlaceholder": "Tell us how we can help...",
    "sending": "Sending...",
    "send": "Send message",
    "emailCardTitle": "Email",
    "emailCardSub": "For general questions",
    "responseTitle": "Response time",
    "responseValue": "No fixed SLA",
    "responseSub": "Depends on the type and priority of the request",
    "followUs": "Follow us",
    "faqTitle": "Have questions?",
    "faqBody": "Visit our Help Center for answers to common questions.",
    "faqLink": "Go to Help Center",
    "nameRequired": "Name is required.",
    "emailRequired": "Email is required.",
    "emailInvalid": "Enter a valid email.",
    "subjectRequired": "Choose a subject.",
    "messageRequired": "Message is required.",
    "messageMin": "Write at least 10 characters.",
    "subjects": [
      "🚩 Listing report",
      "🔧 Technical issue",
      "💡 Suggestion",
      "📋 Other"
    ]
  },
  "pt": {
    "seoTitle": "Contato | Mercasto",
    "seoDescription": "Use os canais oficiais da Mercasto para suporte, segurança, moderação ou dúvidas sobre sua conta.",
    "breadcrumb": "Contato",
    "title": "Fale conosco",
    "subtitle": "Estamos aqui para ajudar. Escreva pelos nossos canais oficiais de contato.",
    "formTitle": "Envie uma mensagem",
    "successTitle": "Mensagem enviada!",
    "successMessage": "Recebemos sua mensagem. Nossa equipe irá analisá-la.",
    "genericError": "Não foi possível enviar a mensagem. Tente novamente mais tarde.",
    "name": "Nome",
    "namePlaceholder": "Seu nome completo",
    "email": "E-mail",
    "emailPlaceholder": "voce@email.com",
    "subject": "Assunto",
    "subjectPlaceholder": "Selecione um assunto...",
    "message": "Mensagem",
    "messagePlaceholder": "Conte como podemos ajudar...",
    "sending": "Enviando...",
    "send": "Enviar mensagem",
    "emailCardTitle": "E-mail",
    "emailCardSub": "Para dúvidas gerais",
    "responseTitle": "Tempo de resposta",
    "responseValue": "Sem prazo fixo",
    "responseSub": "Depende do tipo e da prioridade da solicitação",
    "followUs": "Siga-nos",
    "faqTitle": "Tem dúvidas?",
    "faqBody": "Visite nossa Central de Ajuda para respostas às perguntas frequentes.",
    "faqLink": "Ir para a Central de Ajuda",
    "nameRequired": "O nome é obrigatório.",
    "emailRequired": "O e-mail é obrigatório.",
    "emailInvalid": "Informe um e-mail válido.",
    "subjectRequired": "Selecione um assunto.",
    "messageRequired": "A mensagem é obrigatória.",
    "messageMin": "Escreva pelo menos 10 caracteres.",
    "subjects": [
      "🚩 Denúncia de anúncio",
      "🔧 Problema técnico",
      "💡 Sugestão",
      "📋 Outro"
    ]
  },
  "fr": {
    "seoTitle": "Contact | Mercasto",
    "seoDescription": "Utilisez les canaux officiels de Mercasto pour le support, la sécurité, la modération ou les questions de compte.",
    "breadcrumb": "Contact",
    "title": "Contactez-nous",
    "subtitle": "Nous sommes là pour vous aider. Écrivez-nous via nos canaux officiels.",
    "formTitle": "Envoyez-nous un message",
    "successTitle": "Message envoyé!",
    "successMessage": "Nous avons reçu votre message. Notre équipe va l’examiner.",
    "genericError": "Impossible d’envoyer le message. Réessayez plus tard.",
    "name": "Nom",
    "namePlaceholder": "Votre nom complet",
    "email": "E-mail",
    "emailPlaceholder": "vous@email.com",
    "subject": "Objet",
    "subjectPlaceholder": "Choisissez un objet...",
    "message": "Message",
    "messagePlaceholder": "Dites-nous comment nous pouvons vous aider...",
    "sending": "Envoi...",
    "send": "Envoyer le message",
    "emailCardTitle": "E-mail",
    "emailCardSub": "Pour les questions générales",
    "responseTitle": "Délai de réponse",
    "responseValue": "Aucun délai fixe",
    "responseSub": "Dépend du type et de la priorité de la demande",
    "followUs": "Suivez-nous",
    "faqTitle": "Des questions?",
    "faqBody": "Consultez notre Centre d’aide pour les réponses aux questions fréquentes.",
    "faqLink": "Aller au Centre d’aide",
    "nameRequired": "Le nom est requis.",
    "emailRequired": "L’e-mail est requis.",
    "emailInvalid": "Saisissez un e-mail valide.",
    "subjectRequired": "Choisissez un objet.",
    "messageRequired": "Le message est requis.",
    "messageMin": "Écrivez au moins 10 caractères.",
    "subjects": [
      "🚩 Signaler une annonce",
      "🔧 Problème technique",
      "💡 Suggestion",
      "📋 Autre"
    ]
  },
  "zh": {
    "seoTitle": "联系 Mercasto | Mercasto",
    "seoDescription": "通过 Mercasto 官方渠道咨询支持、安全、审核或账户问题。",
    "breadcrumb": "联系我们",
    "title": "联系我们",
    "subtitle": "我们随时为你提供帮助。请通过官方联系渠道给我们留言。",
    "formTitle": "发送消息",
    "successTitle": "消息已发送!",
    "successMessage": "我们已收到你的消息，团队会进行查看。",
    "genericError": "消息发送失败，请稍后重试。",
    "name": "姓名",
    "namePlaceholder": "你的全名",
    "email": "电子邮箱",
    "emailPlaceholder": "you@email.com",
    "subject": "主题",
    "subjectPlaceholder": "选择主题...",
    "message": "消息",
    "messagePlaceholder": "告诉我们需要什么帮助...",
    "sending": "发送中...",
    "send": "发送消息",
    "emailCardTitle": "电子邮箱",
    "emailCardSub": "一般咨询",
    "responseTitle": "回复时间",
    "responseValue": "无固定时限",
    "responseSub": "取决于请求类型和优先级",
    "followUs": "关注我们",
    "faqTitle": "有问题?",
    "faqBody": "访问帮助中心，查看常见问题的答案。",
    "faqLink": "前往帮助中心",
    "nameRequired": "请输入姓名。",
    "emailRequired": "请输入电子邮箱。",
    "emailInvalid": "请输入有效的电子邮箱。",
    "subjectRequired": "请选择主题。",
    "messageRequired": "请输入消息。",
    "messageMin": "请至少输入 10 个字符。",
    "subjects": [
      "🚩 举报广告",
      "🔧 技术问题",
      "💡 建议",
      "📋 其他"
    ]
  },
  "ko": {
    "seoTitle": "문의 | Mercasto",
    "seoDescription": "지원, 안전, 검토 또는 계정 문의는 Mercasto 공식 연락 채널을 이용하세요.",
    "breadcrumb": "문의",
    "title": "문의하기",
    "subtitle": "도움이 필요하시면 공식 연락 채널로 메시지를 보내주세요.",
    "formTitle": "메시지 보내기",
    "successTitle": "메시지를 보냈습니다!",
    "successMessage": "메시지를 받았습니다. 담당 팀이 확인하겠습니다.",
    "genericError": "메시지를 보내지 못했습니다. 나중에 다시 시도하세요.",
    "name": "이름",
    "namePlaceholder": "전체 이름",
    "email": "이메일",
    "emailPlaceholder": "you@email.com",
    "subject": "제목",
    "subjectPlaceholder": "제목 선택...",
    "message": "메시지",
    "messagePlaceholder": "어떤 도움이 필요한지 알려주세요...",
    "sending": "전송 중...",
    "send": "메시지 보내기",
    "emailCardTitle": "이메일",
    "emailCardSub": "일반 문의",
    "responseTitle": "응답 시간",
    "responseValue": "고정 기한 없음",
    "responseSub": "문의 유형과 우선순위에 따라 달라집니다",
    "followUs": "팔로우하기",
    "faqTitle": "질문이 있나요?",
    "faqBody": "도움말 센터에서 자주 묻는 질문의 답변을 확인하세요.",
    "faqLink": "도움말 센터로 이동",
    "nameRequired": "이름을 입력하세요.",
    "emailRequired": "이메일을 입력하세요.",
    "emailInvalid": "올바른 이메일을 입력하세요.",
    "subjectRequired": "제목을 선택하세요.",
    "messageRequired": "메시지를 입력하세요.",
    "messageMin": "10자 이상 입력하세요.",
    "subjects": [
      "🚩 광고 신고",
      "🔧 기술 문제",
      "💡 제안",
      "📋 기타"
    ]
  },
  "de": {
    "seoTitle": "Kontakt | Mercasto",
    "seoDescription": "Nutze die offiziellen Mercasto-Kontaktkanäle für Support, Sicherheit, Moderation oder Kontofragen.",
    "breadcrumb": "Kontakt",
    "title": "Kontakt aufnehmen",
    "subtitle": "Wir helfen dir gerne. Schreib uns über unsere offiziellen Kontaktkanäle.",
    "formTitle": "Nachricht senden",
    "successTitle": "Nachricht gesendet!",
    "successMessage": "Wir haben deine Nachricht erhalten. Unser Team wird sie prüfen.",
    "genericError": "Die Nachricht konnte nicht gesendet werden. Versuche es später erneut.",
    "name": "Name",
    "namePlaceholder": "Vollständiger Name",
    "email": "E-Mail",
    "emailPlaceholder": "du@email.com",
    "subject": "Betreff",
    "subjectPlaceholder": "Betreff auswählen...",
    "message": "Nachricht",
    "messagePlaceholder": "Sag uns, wie wir helfen können...",
    "sending": "Wird gesendet...",
    "send": "Nachricht senden",
    "emailCardTitle": "E-Mail",
    "emailCardSub": "Für allgemeine Fragen",
    "responseTitle": "Antwortzeit",
    "responseValue": "Keine feste Frist",
    "responseSub": "Abhängig von Art und Priorität der Anfrage",
    "followUs": "Folge uns",
    "faqTitle": "Noch Fragen?",
    "faqBody": "Im Hilfe-Center findest du Antworten auf häufige Fragen.",
    "faqLink": "Zum Hilfe-Center",
    "nameRequired": "Name ist erforderlich.",
    "emailRequired": "E-Mail ist erforderlich.",
    "emailInvalid": "Gib eine gültige E-Mail ein.",
    "subjectRequired": "Wähle einen Betreff.",
    "messageRequired": "Nachricht ist erforderlich.",
    "messageMin": "Schreibe mindestens 10 Zeichen.",
    "subjects": [
      "🚩 Anzeige melden",
      "🔧 Technisches Problem",
      "💡 Vorschlag",
      "📋 Sonstiges"
    ]
  },
  "it": {
    "seoTitle": "Contatti | Mercasto",
    "seoDescription": "Usa i canali ufficiali Mercasto per assistenza, sicurezza, moderazione o domande sull’account.",
    "breadcrumb": "Contatti",
    "title": "Contattaci",
    "subtitle": "Siamo qui per aiutarti. Scrivici tramite i nostri canali ufficiali.",
    "formTitle": "Inviaci un messaggio",
    "successTitle": "Messaggio inviato!",
    "successMessage": "Abbiamo ricevuto il messaggio. Il nostro team lo esaminerà.",
    "genericError": "Non è stato possibile inviare il messaggio. Riprova più tardi.",
    "name": "Nome",
    "namePlaceholder": "Nome completo",
    "email": "E-mail",
    "emailPlaceholder": "tu@email.com",
    "subject": "Oggetto",
    "subjectPlaceholder": "Seleziona un oggetto...",
    "message": "Messaggio",
    "messagePlaceholder": "Dicci come possiamo aiutarti...",
    "sending": "Invio...",
    "send": "Invia messaggio",
    "emailCardTitle": "E-mail",
    "emailCardSub": "Per domande generali",
    "responseTitle": "Tempo di risposta",
    "responseValue": "Nessuna scadenza fissa",
    "responseSub": "Dipende dal tipo e dalla priorità della richiesta",
    "followUs": "Seguici",
    "faqTitle": "Hai domande?",
    "faqBody": "Visita il Centro assistenza per le risposte alle domande frequenti.",
    "faqLink": "Vai al Centro assistenza",
    "nameRequired": "Il nome è obbligatorio.",
    "emailRequired": "L’e-mail è obbligatoria.",
    "emailInvalid": "Inserisci un’e-mail valida.",
    "subjectRequired": "Seleziona un oggetto.",
    "messageRequired": "Il messaggio è obbligatorio.",
    "messageMin": "Scrivi almeno 10 caratteri.",
    "subjects": [
      "🚩 Segnala annuncio",
      "🔧 Problema tecnico",
      "💡 Suggerimento",
      "📋 Altro"
    ]
  },
  "ar": {
    "seoTitle": "تواصل معنا | Mercasto",
    "seoDescription": "استخدم قنوات Mercasto الرسمية للدعم أو الأمان أو الإشراف أو الاستفسارات المتعلقة بالحساب.",
    "breadcrumb": "اتصل بنا",
    "title": "تواصل معنا",
    "subtitle": "نحن هنا للمساعدة. راسلنا عبر قنوات التواصل الرسمية.",
    "formTitle": "أرسل لنا رسالة",
    "successTitle": "تم إرسال الرسالة!",
    "successMessage": "استلمنا رسالتك وسيراجعها فريقنا.",
    "genericError": "تعذر إرسال الرسالة. حاول مرة أخرى لاحقًا.",
    "name": "الاسم",
    "namePlaceholder": "الاسم الكامل",
    "email": "البريد الإلكتروني",
    "emailPlaceholder": "you@email.com",
    "subject": "الموضوع",
    "subjectPlaceholder": "اختر موضوعًا...",
    "message": "الرسالة",
    "messagePlaceholder": "أخبرنا كيف يمكننا مساعدتك...",
    "sending": "جارٍ الإرسال...",
    "send": "إرسال الرسالة",
    "emailCardTitle": "البريد الإلكتروني",
    "emailCardSub": "للاستفسارات العامة",
    "responseTitle": "وقت الرد",
    "responseValue": "لا توجد مهلة ثابتة",
    "responseSub": "يعتمد على نوع الطلب وأولويته",
    "followUs": "تابعنا",
    "faqTitle": "لديك أسئلة?",
    "faqBody": "زر مركز المساعدة للاطلاع على إجابات الأسئلة الشائعة.",
    "faqLink": "الذهاب إلى مركز المساعدة",
    "nameRequired": "الاسم مطلوب.",
    "emailRequired": "البريد الإلكتروني مطلوب.",
    "emailInvalid": "أدخل بريدًا إلكترونيًا صالحًا.",
    "subjectRequired": "اختر موضوعًا.",
    "messageRequired": "الرسالة مطلوبة.",
    "messageMin": "اكتب 10 أحرف على الأقل.",
    "subjects": [
      "🚩 الإبلاغ عن إعلان",
      "🔧 مشكلة تقنية",
      "💡 اقتراح",
      "📋 أخرى"
    ]
  },
  "ru": {
    "seoTitle": "Контакты | Mercasto",
    "seoDescription": "Используйте официальные каналы Mercasto для вопросов о поддержке, безопасности, модерации или аккаунте.",
    "breadcrumb": "Контакты",
    "title": "Связаться с нами",
    "subtitle": "Мы готовы помочь. Напишите нам через официальные каналы связи.",
    "formTitle": "Отправить сообщение",
    "successTitle": "Сообщение отправлено!",
    "successMessage": "Мы получили сообщение. Команда его рассмотрит.",
    "genericError": "Не удалось отправить сообщение. Попробуйте позже.",
    "name": "Имя",
    "namePlaceholder": "Ваше полное имя",
    "email": "Электронная почта",
    "emailPlaceholder": "you@email.com",
    "subject": "Тема",
    "subjectPlaceholder": "Выберите тему...",
    "message": "Сообщение",
    "messagePlaceholder": "Расскажите, чем мы можем помочь...",
    "sending": "Отправка...",
    "send": "Отправить сообщение",
    "emailCardTitle": "Электронная почта",
    "emailCardSub": "Для общих вопросов",
    "responseTitle": "Срок ответа",
    "responseValue": "Без фиксированного срока",
    "responseSub": "Зависит от типа и приоритета обращения",
    "followUs": "Мы в соцсетях",
    "faqTitle": "Есть вопросы?",
    "faqBody": "В Центре помощи есть ответы на частые вопросы.",
    "faqLink": "Перейти в Центр помощи",
    "nameRequired": "Введите имя.",
    "emailRequired": "Введите электронную почту.",
    "emailInvalid": "Введите корректный адрес электронной почты.",
    "subjectRequired": "Выберите тему.",
    "messageRequired": "Введите сообщение.",
    "messageMin": "Введите не менее 10 символов.",
    "subjects": [
      "🚩 Жалоба на объявление",
      "🔧 Техническая проблема",
      "💡 Предложение",
      "📋 Другое"
    ]
  },
  "ja": {
    "seoTitle": "お問い合わせ | Mercasto",
    "seoDescription": "サポート、安全、モデレーション、アカウントに関する質問は Mercasto の公式窓口をご利用ください。",
    "breadcrumb": "お問い合わせ",
    "title": "お問い合わせ",
    "subtitle": "サポートが必要な場合は、公式の連絡窓口からメッセージをお送りください。",
    "formTitle": "メッセージを送る",
    "successTitle": "送信しました!",
    "successMessage": "メッセージを受け取りました。担当チームが確認します。",
    "genericError": "メッセージを送信できませんでした。後でもう一度お試しください。",
    "name": "名前",
    "namePlaceholder": "氏名",
    "email": "メール",
    "emailPlaceholder": "you@email.com",
    "subject": "件名",
    "subjectPlaceholder": "件名を選択...",
    "message": "メッセージ",
    "messagePlaceholder": "どのようなサポートが必要かお知らせください...",
    "sending": "送信中...",
    "send": "メッセージを送信",
    "emailCardTitle": "メール",
    "emailCardSub": "一般的なお問い合わせ",
    "responseTitle": "返信時間",
    "responseValue": "固定期限なし",
    "responseSub": "お問い合わせの種類と優先度によって異なります",
    "followUs": "フォローする",
    "faqTitle": "質問がありますか?",
    "faqBody": "よくある質問の回答はヘルプセンターで確認できます。",
    "faqLink": "ヘルプセンターへ",
    "nameRequired": "名前を入力してください。",
    "emailRequired": "メールアドレスを入力してください。",
    "emailInvalid": "有効なメールアドレスを入力してください。",
    "subjectRequired": "件名を選択してください。",
    "messageRequired": "メッセージを入力してください。",
    "messageMin": "10文字以上入力してください。",
    "subjects": [
      "🚩 広告を報告",
      "🔧 技術的な問題",
      "💡 提案",
      "📋 その他"
    ]
  }
});

export const CONTACT_PAGE_LANGUAGES = Object.freeze(Object.keys(CONTACT_PAGE_COPY));

export function hasContactPageCopy(language) {
  const raw = String(language || '').trim().toLowerCase().split('-')[0];
  return CONTACT_PAGE_LANGUAGES.includes(raw);
}

export function getContactPageCopy(language = 'es') {
  return CONTACT_PAGE_COPY[normalizeLanguage(language)] || CONTACT_PAGE_COPY.es;
}

export function getContactSubjects(language = 'es') {
  const labels = getContactPageCopy(language).subjects;
  return CONTACT_SUBJECT_VALUES.map((value, index) => ({ value, label: labels[index] }));
}
