import { normalizeLanguage } from './translations.js';

const HELP_CENTER_COPY = Object.freeze({
  es: {
    seoTitle: 'Centro de Ayuda de Mercasto | Comprar y vender',
    seoDescription: 'Encuentra guías oficiales sobre publicación, seguridad, compra, contacto, pagos y políticas de Mercasto.',
    breadcrumb: 'Centro de Ayuda',
    heroTitle: 'Cómo podemos ayudarte?',
    heroSubtitle: 'Encuentra respuestas rápidas a las preguntas más frecuentes.',
    searchPlaceholder: 'Buscar en el Centro de Ayuda...',
    noResults: 'Sin resultados para',
    tryOther: 'Intenta con otras palabras o',
    clearSearch: 'borra la búsqueda',
    contactTitle: 'No encontraste lo que buscabas?',
    contactBody: 'Nuestro equipo de soporte está listo para ayudarte.',
    contactButton: 'Contactar soporte',
    sections: [
      { id: 'publicar', title: 'Publicar anuncios', faqs: [
        { q: 'Cómo publico un anuncio?', a: 'Haz clic en "Publicar", completa categoría, título, descripción, precio, condición, ubicación y fotografías cuando correspondan. El anuncio puede quedar pendiente mientras pasa por moderación.' },
        { q: 'Cuántos anuncios puedo publicar?', a: 'El límite vigente depende de las condiciones mostradas en tu cuenta y del producto contratado. La sección "Mis anuncios" muestra cuántos anuncios puedes gestionar.' },
        { q: 'Cuánto tiempo dura mi anuncio?', a: 'Los anuncios gratuitos están activos durante 7 días. Después puedes renovarlos por $49 MXN por otros 7 días o eliminarlos sin costo desde la sección "Mis anuncios" de tu perfil.' },
        { q: 'Puedo editar mi anuncio después de publicarlo?', a: 'Sí. Ve a tu perfil → "Mis anuncios", selecciona el anuncio que deseas modificar y haz clic en "Editar". Puedes cambiar título, descripción, precio, fotos y ubicación en cualquier momento.' },
      ]},
      { id: 'comprar', title: 'Comprar y contactar', faqs: [
        { q: 'Cómo contacto al vendedor?', a: 'Puedes contactar al vendedor por los canales públicos que haya habilitado, como WhatsApp, Telegram o correo electrónico.' },
        { q: 'Puedo hacer una oferta al vendedor?', a: 'Sí. Puedes proponer un precio por el canal público del vendedor y coordinar la entrega con seguridad.' },
        { q: 'Mercasto garantiza las transacciones?', a: 'Mercasto es una plataforma intermediaria: conectamos compradores y vendedores pero no participamos directamente en las transacciones. Te recomendamos acordar el lugar de entrega en sitio público, verificar el artículo antes de pagar y nunca realizar transferencias anticipadas a desconocidos.' },
      ]},
      { id: 'cuenta', title: 'Mi cuenta', faqs: [
        { q: 'Cómo verifico mi número de teléfono?', a: 'La verificación por SMS se encuentra temporalmente deshabilitada. Puedes usar email, Google o Telegram para acceder a tu cuenta; Mercasto mostrará la opción telefónica cuando el proveedor esté disponible.' },
        { q: 'Cómo cambio mi contraseña?', a: 'Ve a tu Perfil → "Seguridad" → "Cambiar contraseña". También puedes restablecer tu contraseña desde la pantalla de inicio de sesión usando la opción "Olvidaste tu contraseña?".' },
        { q: 'Puedo iniciar sesión con Google?', a: 'Sí. En la pantalla de inicio de sesión o registro encontrarás el botón "Continuar con Google". Esta opción es rápida y segura; no necesitas recordar una contraseña adicional.' },
      ]},
      { id: 'seguridad', title: 'Seguridad', faqs: [
        { q: 'Cómo reporto un anuncio sospechoso?', a: 'En cada anuncio puedes usar la opción de reporte y explicar el motivo. Mercasto prioriza los casos según el riesgo y no promete un plazo fijo de resolución.' },
        { q: 'Cómo evito fraudes al comprar?', a: 'Nunca compartas datos bancarios, números de tarjeta ni contraseñas. Desconfía de precios extremadamente bajos. Siempre acuerda la entrega en un lugar público y verifica el producto antes de pagar. Si algo parece demasiado bueno para ser verdad, probablemente lo es.' },
        { q: 'Mercasto me pedirá mi contraseña alguna vez?', a: 'Nunca. Mercasto jamás te solicitará tu contraseña por ningún medio: ni por correo electrónico, ni por WhatsApp, ni por Telegram. Si alguien que dice ser Mercasto te la pide, es un intento de fraude. Repórtalo inmediatamente.' },
      ]},
      { id: 'destacar', title: 'Destacar anuncios', faqs: [
        { q: 'Qué es un anuncio Destacado?', a: 'Un producto de promoción puede cambiar la posición o presentación del anuncio durante el periodo indicado. No garantiza impresiones, contactos ni una venta.' },
        { q: 'Cuánto cuesta destacar un anuncio?', a: 'Las opciones vigentes son: Subir 3 días por $49 MXN, Resaltar 7 días por $79 MXN, Destacado 7 días por $149 MXN y Top de categoría 7 días por $399 MXN.' },
        { q: 'Cómo se realiza el pago para destacar?', a: 'El checkout muestra el proveedor, el concepto, el importe y los medios de pago disponibles. Revisa esos datos antes de confirmar y conserva el comprobante del proveedor.' },
      ]},
    ],
  },
  en: {
    seoTitle: 'Mercasto Help Center | Buy and sell',
    seoDescription: 'Find official Mercasto guides about posting, safety, buying, contacting sellers, payments and policies.',
    breadcrumb: 'Help Center',
    heroTitle: 'How can we help?',
    heroSubtitle: 'Find quick answers to the most common questions.',
    searchPlaceholder: 'Search the Help Center...',
    noResults: 'No results for',
    tryOther: 'Try different words or',
    clearSearch: 'clear the search',
    contactTitle: "Didn't find what you needed?",
    contactBody: 'Our support team is ready to help.',
    contactButton: 'Contact support',
    sections: [
      { id: 'publicar', title: 'Posting listings', faqs: [
        { q: 'How do I post a listing?', a: 'Click "Post", then complete the category, title, description, price, condition, location and photos when applicable. The listing may remain pending while it goes through moderation.' },
        { q: 'How many listings can I post?', a: 'The current limit depends on the conditions shown in your account and the product you have purchased. The "My listings" section shows how many listings you can manage.' },
        { q: 'How long does my listing stay active?', a: 'Free listings stay active for 7 days. After that, you can renew for another 7 days for $49 MXN or delete the listing at no cost from "My listings" in your profile.' },
        { q: 'Can I edit my listing after publishing it?', a: 'Yes. Go to your profile → "My listings", select the listing you want to change and click "Edit". You can update the title, description, price, photos and location.' },
      ]},
      { id: 'comprar', title: 'Buying and contacting', faqs: [
        { q: 'How do I contact the seller?', a: 'You can contact the seller through any public channel they have enabled, such as WhatsApp, Telegram or email.' },
        { q: 'Can I make an offer to the seller?', a: 'Yes. You can propose a price through the seller’s public channel and coordinate delivery safely.' },
        { q: 'Does Mercasto guarantee transactions?', a: 'Mercasto is an intermediary platform: we connect buyers and sellers but do not participate directly in transactions. Agree to meet in a public place, inspect the item before paying and never send advance transfers to strangers.' },
      ]},
      { id: 'cuenta', title: 'My account', faqs: [
        { q: 'How do I verify my phone number?', a: 'SMS verification is temporarily disabled. You can use email, Google or Telegram to access your account; Mercasto will show the phone option when the provider is available.' },
        { q: 'How do I change my password?', a: 'Go to Profile → "Security" → "Change password". You can also reset it from the sign-in screen using "Forgot your password?".' },
        { q: 'Can I sign in with Google?', a: 'Yes. The sign-in and registration screens include a "Continue with Google" button. It is fast and secure, and you do not need to remember another password.' },
      ]},
      { id: 'seguridad', title: 'Safety', faqs: [
        { q: 'How do I report a suspicious listing?', a: 'Each listing includes a report option where you can explain the reason. Mercasto prioritizes cases by risk and does not promise a fixed resolution time.' },
        { q: 'How can I avoid fraud when buying?', a: 'Never share banking details, card numbers or passwords. Be cautious with unusually low prices. Meet in a public place and inspect the product before paying. If something looks too good to be true, it probably is.' },
        { q: 'Will Mercasto ever ask for my password?', a: 'Never. Mercasto will not ask for your password by email, WhatsApp, Telegram or any other channel. If someone claiming to be Mercasto asks for it, treat it as fraud and report it immediately.' },
      ]},
      { id: 'destacar', title: 'Promoting listings', faqs: [
        { q: 'What is a Featured listing?', a: 'A promotion product can change the position or presentation of a listing for the stated period. It does not guarantee impressions, contacts or a sale.' },
        { q: 'How much does listing promotion cost?', a: 'Current options are: Boost for 3 days for $49 MXN, Highlight for 7 days for $79 MXN, Featured for 7 days for $149 MXN and Category Top for 7 days for $399 MXN.' },
        { q: 'How do I pay for a promotion?', a: 'Checkout shows the provider, item, amount and available payment methods. Review those details before confirming and keep the provider receipt.' },
      ]},
    ],
  },
  pt: {
    seoTitle: 'Central de Ajuda Mercasto | Comprar e vender',
    seoDescription: 'Encontre guias oficiais da Mercasto sobre anúncios, segurança, compras, contato, pagamentos e políticas.',
    breadcrumb: 'Central de Ajuda',
    heroTitle: 'Como podemos ajudar?',
    heroSubtitle: 'Encontre respostas rápidas para as perguntas mais frequentes.',
    searchPlaceholder: 'Pesquisar na Central de Ajuda...',
    noResults: 'Sem resultados para',
    tryOther: 'Tente outras palavras ou',
    clearSearch: 'limpe a pesquisa',
    contactTitle: 'Não encontrou o que procurava?',
    contactBody: 'Nossa equipe de suporte está pronta para ajudar.',
    contactButton: 'Falar com o suporte',
    sections: [
      { id: 'publicar', title: 'Publicar anúncios', faqs: [
        { q: 'Como publico um anúncio?', a: 'Clique em "Publicar" e preencha categoria, título, descrição, preço, condição, localização e fotos quando aplicável. O anúncio pode ficar pendente durante a moderação.' },
        { q: 'Quantos anúncios posso publicar?', a: 'O limite atual depende das condições exibidas na sua conta e do produto contratado. A seção "Meus anúncios" mostra quantos anúncios você pode gerenciar.' },
        { q: 'Por quanto tempo meu anúncio fica ativo?', a: 'Anúncios gratuitos ficam ativos por 7 dias. Depois, você pode renovar por mais 7 dias por $49 MXN ou excluir sem custo em "Meus anúncios" no perfil.' },
        { q: 'Posso editar o anúncio depois de publicar?', a: 'Sim. Vá ao perfil → "Meus anúncios", escolha o anúncio e clique em "Editar". Você pode alterar título, descrição, preço, fotos e localização.' },
      ]},
      { id: 'comprar', title: 'Comprar e entrar em contato', faqs: [
        { q: 'Como entro em contato com o vendedor?', a: 'Use os canais públicos habilitados pelo vendedor, como WhatsApp, Telegram ou e-mail.' },
        { q: 'Posso fazer uma oferta ao vendedor?', a: 'Sim. Você pode propor um preço pelo canal público do vendedor e combinar a entrega com segurança.' },
        { q: 'A Mercasto garante as transações?', a: 'A Mercasto é uma plataforma intermediária: conecta compradores e vendedores, mas não participa diretamente das transações. Combine a entrega em local público, confira o item antes de pagar e nunca faça transferências antecipadas para desconhecidos.' },
      ]},
      { id: 'cuenta', title: 'Minha conta', faqs: [
        { q: 'Como verifico meu número de telefone?', a: 'A verificação por SMS está temporariamente desativada. Use e-mail, Google ou Telegram; a Mercasto exibirá a opção por telefone quando o provedor estiver disponível.' },
        { q: 'Como altero minha senha?', a: 'Vá para Perfil → "Segurança" → "Alterar senha". Também é possível redefinir pela tela de login usando "Esqueceu sua senha?".' },
        { q: 'Posso entrar com o Google?', a: 'Sim. Nas telas de login e cadastro há o botão "Continuar com Google". É rápido e seguro e não exige outra senha.' },
      ]},
      { id: 'seguridad', title: 'Segurança', faqs: [
        { q: 'Como denuncio um anúncio suspeito?', a: 'Cada anúncio tem uma opção de denúncia para informar o motivo. A Mercasto prioriza os casos pelo risco e não promete prazo fixo de resolução.' },
        { q: 'Como evito fraudes ao comprar?', a: 'Nunca compartilhe dados bancários, números de cartão ou senhas. Desconfie de preços muito baixos. Encontre-se em local público e confira o produto antes de pagar. Se parecer bom demais para ser verdade, provavelmente é.' },
        { q: 'A Mercasto alguma vez pedirá minha senha?', a: 'Nunca. A Mercasto não solicitará sua senha por e-mail, WhatsApp, Telegram ou qualquer outro meio. Se alguém pedir em nome da Mercasto, trate como fraude e denuncie imediatamente.' },
      ]},
      { id: 'destacar', title: 'Promover anúncios', faqs: [
        { q: 'O que é um anúncio em Destaque?', a: 'Um produto de promoção pode mudar a posição ou a apresentação do anúncio pelo período informado. Não garante impressões, contatos ou venda.' },
        { q: 'Quanto custa promover um anúncio?', a: 'As opções atuais são: Subir por 3 dias por $49 MXN, Realçar por 7 dias por $79 MXN, Destaque por 7 dias por $149 MXN e Top da categoria por 7 dias por $399 MXN.' },
        { q: 'Como pago por uma promoção?', a: 'O checkout mostra provedor, conceito, valor e meios de pagamento disponíveis. Revise os dados antes de confirmar e guarde o comprovante do provedor.' },
      ]},
    ],
  },
  fr: {
    seoTitle: 'Centre d’aide Mercasto | Acheter et vendre',
    seoDescription: 'Consultez les guides officiels Mercasto sur les annonces, la sécurité, les achats, le contact, les paiements et les politiques.',
    breadcrumb: 'Centre d’aide',
    heroTitle: 'Comment pouvons-nous vous aider?',
    heroSubtitle: 'Trouvez rapidement les réponses aux questions fréquentes.',
    searchPlaceholder: 'Rechercher dans le Centre d’aide...',
    noResults: 'Aucun résultat pour',
    tryOther: 'Essayez d’autres mots ou',
    clearSearch: 'effacez la recherche',
    contactTitle: 'Vous n’avez pas trouvé ce que vous cherchiez?',
    contactBody: 'Notre équipe de support est prête à vous aider.',
    contactButton: 'Contacter le support',
    sections: [
      { id: 'publicar', title: 'Publier des annonces', faqs: [
        { q: 'Comment publier une annonce?', a: 'Cliquez sur "Publier", puis renseignez catégorie, titre, description, prix, état, localisation et photos si nécessaire. L’annonce peut rester en attente pendant la modération.' },
        { q: 'Combien d’annonces puis-je publier?', a: 'La limite actuelle dépend des conditions affichées dans votre compte et du produit souscrit. La section "Mes annonces" indique combien d’annonces vous pouvez gérer.' },
        { q: 'Combien de temps mon annonce reste-t-elle active?', a: 'Les annonces gratuites restent actives 7 jours. Ensuite, vous pouvez les renouveler 7 jours de plus pour $49 MXN ou les supprimer gratuitement depuis "Mes annonces".' },
        { q: 'Puis-je modifier mon annonce après publication?', a: 'Oui. Allez dans Profil → "Mes annonces", choisissez l’annonce puis cliquez sur "Modifier". Vous pouvez changer le titre, la description, le prix, les photos et la localisation.' },
      ]},
      { id: 'comprar', title: 'Acheter et contacter', faqs: [
        { q: 'Comment contacter le vendeur?', a: 'Utilisez les canaux publics activés par le vendeur, comme WhatsApp, Telegram ou l’e-mail.' },
        { q: 'Puis-je faire une offre au vendeur?', a: 'Oui. Vous pouvez proposer un prix via le canal public du vendeur et organiser la remise en toute sécurité.' },
        { q: 'Mercasto garantit-il les transactions?', a: 'Mercasto est une plateforme intermédiaire: nous mettons acheteurs et vendeurs en relation sans participer directement à la transaction. Privilégiez un lieu public, vérifiez l’article avant de payer et n’envoyez jamais d’avance à un inconnu.' },
      ]},
      { id: 'cuenta', title: 'Mon compte', faqs: [
        { q: 'Comment vérifier mon numéro de téléphone?', a: 'La vérification SMS est temporairement désactivée. Utilisez l’e-mail, Google ou Telegram; Mercasto affichera l’option téléphone lorsque le fournisseur sera disponible.' },
        { q: 'Comment changer mon mot de passe?', a: 'Allez dans Profil → "Sécurité" → "Changer le mot de passe". Vous pouvez aussi le réinitialiser depuis l’écran de connexion avec "Mot de passe oublié?".' },
        { q: 'Puis-je me connecter avec Google?', a: 'Oui. Les écrans de connexion et d’inscription proposent "Continuer avec Google". C’est rapide et sûr et ne nécessite pas de mot de passe supplémentaire.' },
      ]},
      { id: 'seguridad', title: 'Sécurité', faqs: [
        { q: 'Comment signaler une annonce suspecte?', a: 'Chaque annonce propose une option de signalement avec le motif. Mercasto priorise les cas selon le risque et ne promet pas de délai fixe de résolution.' },
        { q: 'Comment éviter les fraudes lors d’un achat?', a: 'Ne partagez jamais vos données bancaires, numéros de carte ou mots de passe. Méfiez-vous des prix anormalement bas. Rencontrez-vous dans un lieu public et vérifiez le produit avant de payer.' },
        { q: 'Mercasto me demandera-t-il un jour mon mot de passe?', a: 'Jamais. Mercasto ne vous demandera votre mot de passe ni par e-mail, ni par WhatsApp, ni par Telegram. Si quelqu’un le demande au nom de Mercasto, considérez cela comme une fraude et signalez-le.' },
      ]},
      { id: 'destacar', title: 'Promouvoir les annonces', faqs: [
        { q: 'Qu’est-ce qu’une annonce en vedette?', a: 'Un produit promotionnel peut modifier la position ou la présentation d’une annonce pendant la période indiquée. Il ne garantit ni impressions, ni contacts, ni vente.' },
        { q: 'Combien coûte la promotion d’une annonce?', a: 'Options actuelles: Remonter 3 jours pour $49 MXN, Surligner 7 jours pour $79 MXN, Vedette 7 jours pour $149 MXN et Top catégorie 7 jours pour $399 MXN.' },
        { q: 'Comment payer une promotion?', a: 'Le checkout affiche le fournisseur, l’objet, le montant et les moyens de paiement disponibles. Vérifiez ces informations avant de confirmer et conservez le reçu du fournisseur.' },
      ]},
    ],
  },
  zh: {
    seoTitle: 'Mercasto 帮助中心 | 买卖指南',
    seoDescription: '查看 Mercasto 关于发布、安全、购买、联系卖家、付款和政策的官方指南。',
    breadcrumb: '帮助中心',
    heroTitle: '我们能为你做什么?',
    heroSubtitle: '快速找到常见问题的答案。',
    searchPlaceholder: '搜索帮助中心...',
    noResults: '没有找到',
    tryOther: '请尝试其他关键词或',
    clearSearch: '清除搜索',
    contactTitle: '没有找到需要的答案?',
    contactBody: '我们的支持团队可以帮助你。',
    contactButton: '联系支持',
    sections: [
      { id: 'publicar', title: '发布广告', faqs: [
        { q: '如何发布广告?', a: '点击“发布”，填写类别、标题、描述、价格、状态、位置，并在适用时上传照片。广告在审核期间可能处于待处理状态。' },
        { q: '我可以发布多少条广告?', a: '当前上限取决于你的账户所显示的条件和购买的产品。“我的广告”会显示你可以管理的广告数量。' },
        { q: '广告可以保持多长时间?', a: '免费广告有效期为 7 天。之后可支付 $49 MXN 再续期 7 天，或在个人资料的“我的广告”中免费删除。' },
        { q: '发布后可以编辑广告吗?', a: '可以。进入个人资料 → “我的广告”，选择需要修改的广告并点击“编辑”。你可以修改标题、描述、价格、照片和位置。' },
      ]},
      { id: 'comprar', title: '购买与联系', faqs: [
        { q: '如何联系卖家?', a: '你可以通过卖家启用的公开渠道联系，例如 WhatsApp、Telegram 或电子邮箱。' },
        { q: '可以向卖家出价吗?', a: '可以。你可以通过卖家的公开渠道提出价格，并安全地协调交付。' },
        { q: 'Mercasto 是否担保交易?', a: 'Mercasto 是中介平台：我们连接买家和卖家，但不直接参与交易。建议在公共场所交付，付款前检查商品，并且不要提前向陌生人转账。' },
      ]},
      { id: 'cuenta', title: '我的账户', faqs: [
        { q: '如何验证手机号?', a: '短信验证目前暂时关闭。你可以使用电子邮箱、Google 或 Telegram 登录；服务提供商恢复可用后，Mercasto 会显示手机验证选项。' },
        { q: '如何修改密码?', a: '进入个人资料 → “安全” → “修改密码”。也可以在登录页面使用“忘记密码?”重置密码。' },
        { q: '可以使用 Google 登录吗?', a: '可以。登录和注册页面都有“使用 Google 继续”按钮。该方式快速且安全，不需要记住额外密码。' },
      ]},
      { id: 'seguridad', title: '安全', faqs: [
        { q: '如何举报可疑广告?', a: '每条广告都有举报选项，可说明原因。Mercasto 会根据风险确定处理优先级，不承诺固定的处理时间。' },
        { q: '购买时如何避免诈骗?', a: '不要分享银行信息、银行卡号或密码。对异常低价保持警惕。请在公共场所见面，并在付款前检查商品。如果好得不像真的，很可能就不是真的。' },
        { q: 'Mercasto 会向我要密码吗?', a: '绝不会。Mercasto 不会通过电子邮件、WhatsApp、Telegram 或其他方式索要密码。如果有人以 Mercasto 名义索要密码，请视为诈骗并立即举报。' },
      ]},
      { id: 'destacar', title: '推广广告', faqs: [
        { q: '什么是精选广告?', a: '推广产品可以在指定时间内改变广告的位置或展示方式，但不保证曝光、联系或成交。' },
        { q: '推广广告多少钱?', a: '当前选项：置顶 3 天 $49 MXN，高亮 7 天 $79 MXN，精选 7 天 $149 MXN，分类顶部 7 天 $399 MXN。' },
        { q: '如何支付推广费用?', a: '结账页面会显示服务提供商、项目、金额和可用支付方式。确认前请检查这些信息，并保留服务提供商的付款凭证。' },
      ]},
    ],
  },
  ko: {
    seoTitle: 'Mercasto 도움말 센터 | 구매 및 판매',
    seoDescription: '게시, 안전, 구매, 판매자 연락, 결제 및 정책에 관한 Mercasto 공식 안내를 확인하세요.',
    breadcrumb: '도움말 센터',
    heroTitle: '무엇을 도와드릴까요?',
    heroSubtitle: '자주 묻는 질문의 답변을 빠르게 찾아보세요.',
    searchPlaceholder: '도움말 센터 검색...',
    noResults: '검색 결과 없음:',
    tryOther: '다른 단어를 사용하거나',
    clearSearch: '검색을 지워보세요',
    contactTitle: '원하는 답을 찾지 못했나요?',
    contactBody: '지원팀이 도와드리겠습니다.',
    contactButton: '지원팀에 문의',
    sections: [
      { id: 'publicar', title: '광고 게시', faqs: [
        { q: '광고는 어떻게 게시하나요?', a: '“게시”를 누르고 카테고리, 제목, 설명, 가격, 상태, 위치와 필요한 경우 사진을 입력하세요. 검토가 진행되는 동안 광고가 대기 상태일 수 있습니다.' },
        { q: '몇 개의 광고를 게시할 수 있나요?', a: '현재 한도는 계정에 표시되는 조건과 구매한 상품에 따라 달라집니다. “내 광고”에서 관리 가능한 광고 수를 확인할 수 있습니다.' },
        { q: '광고는 얼마나 오래 활성화되나요?', a: '무료 광고는 7일 동안 활성화됩니다. 이후 $49 MXN으로 7일 더 갱신하거나 프로필의 “내 광고”에서 무료로 삭제할 수 있습니다.' },
        { q: '게시 후 광고를 수정할 수 있나요?', a: '네. 프로필 → “내 광고”로 이동해 광고를 선택하고 “수정”을 누르세요. 제목, 설명, 가격, 사진과 위치를 변경할 수 있습니다.' },
      ]},
      { id: 'comprar', title: '구매 및 연락', faqs: [
        { q: '판매자에게 어떻게 연락하나요?', a: '판매자가 공개한 WhatsApp, Telegram, 이메일 등의 채널을 이용할 수 있습니다.' },
        { q: '판매자에게 가격을 제안할 수 있나요?', a: '네. 판매자의 공개 채널을 통해 가격을 제안하고 안전하게 전달 방법을 조율할 수 있습니다.' },
        { q: 'Mercasto가 거래를 보장하나요?', a: 'Mercasto는 구매자와 판매자를 연결하는 중개 플랫폼이며 거래에 직접 참여하지 않습니다. 공공장소에서 만나고 결제 전에 상품을 확인하며 모르는 사람에게 선입금을 보내지 마세요.' },
      ]},
      { id: 'cuenta', title: '내 계정', faqs: [
        { q: '전화번호는 어떻게 인증하나요?', a: 'SMS 인증은 현재 일시적으로 비활성화되어 있습니다. 이메일, Google 또는 Telegram으로 로그인할 수 있으며 제공업체가 준비되면 전화 인증 옵션이 표시됩니다.' },
        { q: '비밀번호는 어떻게 변경하나요?', a: '프로필 → “보안” → “비밀번호 변경”으로 이동하세요. 로그인 화면의 “비밀번호를 잊으셨나요?”에서도 재설정할 수 있습니다.' },
        { q: 'Google로 로그인할 수 있나요?', a: '네. 로그인 및 가입 화면에서 “Google로 계속”을 사용할 수 있습니다. 빠르고 안전하며 추가 비밀번호를 기억할 필요가 없습니다.' },
      ]},
      { id: 'seguridad', title: '안전', faqs: [
        { q: '의심스러운 광고는 어떻게 신고하나요?', a: '각 광고의 신고 기능에서 이유를 설명할 수 있습니다. Mercasto는 위험도에 따라 우선순위를 정하며 고정된 처리 시간을 약속하지 않습니다.' },
        { q: '구매 사기를 어떻게 피하나요?', a: '은행 정보, 카드 번호 또는 비밀번호를 공유하지 마세요. 지나치게 낮은 가격을 주의하고, 공공장소에서 만나 결제 전에 상품을 확인하세요.' },
        { q: 'Mercasto가 비밀번호를 요구할 수 있나요?', a: '절대 아닙니다. Mercasto는 이메일, WhatsApp, Telegram 등 어떤 채널로도 비밀번호를 요구하지 않습니다. Mercasto를 사칭해 요구한다면 즉시 신고하세요.' },
      ]},
      { id: 'destacar', title: '광고 프로모션', faqs: [
        { q: '추천 광고란 무엇인가요?', a: '프로모션 상품은 지정된 기간 동안 광고의 위치나 표시 방식을 바꿀 수 있습니다. 노출, 연락 또는 판매를 보장하지 않습니다.' },
        { q: '광고 프로모션 비용은 얼마인가요?', a: '현재 옵션: 3일 끌어올리기 $49 MXN, 7일 강조 $79 MXN, 7일 추천 $149 MXN, 7일 카테고리 최상단 $399 MXN.' },
        { q: '프로모션 비용은 어떻게 결제하나요?', a: '결제 화면에 제공업체, 항목, 금액과 사용 가능한 결제 수단이 표시됩니다. 확인 전에 내용을 검토하고 제공업체 영수증을 보관하세요.' },
      ]},
    ],
  },
  de: {
    seoTitle: 'Mercasto Hilfe-Center | Kaufen und verkaufen',
    seoDescription: 'Offizielle Mercasto-Hilfen zu Anzeigen, Sicherheit, Kaufen, Kontakt, Zahlungen und Richtlinien.',
    breadcrumb: 'Hilfe-Center',
    heroTitle: 'Wie können wir helfen?',
    heroSubtitle: 'Finde schnell Antworten auf häufige Fragen.',
    searchPlaceholder: 'Im Hilfe-Center suchen...',
    noResults: 'Keine Ergebnisse für',
    tryOther: 'Versuche andere Begriffe oder',
    clearSearch: 'lösche die Suche',
    contactTitle: 'Nicht gefunden, was du suchst?',
    contactBody: 'Unser Support-Team hilft dir gerne.',
    contactButton: 'Support kontaktieren',
    sections: [
      { id: 'publicar', title: 'Anzeigen veröffentlichen', faqs: [
        { q: 'Wie veröffentliche ich eine Anzeige?', a: 'Klicke auf „Veröffentlichen“ und ergänze Kategorie, Titel, Beschreibung, Preis, Zustand, Standort und gegebenenfalls Fotos. Während der Moderation kann die Anzeige ausstehend bleiben.' },
        { q: 'Wie viele Anzeigen kann ich veröffentlichen?', a: 'Das aktuelle Limit hängt von den in deinem Konto angezeigten Bedingungen und dem gebuchten Produkt ab. Unter „Meine Anzeigen“ siehst du, wie viele Anzeigen du verwalten kannst.' },
        { q: 'Wie lange bleibt meine Anzeige aktiv?', a: 'Kostenlose Anzeigen sind 7 Tage aktiv. Danach kannst du sie für $49 MXN um weitere 7 Tage verlängern oder unter „Meine Anzeigen“ kostenlos löschen.' },
        { q: 'Kann ich meine Anzeige nach der Veröffentlichung bearbeiten?', a: 'Ja. Gehe zu Profil → „Meine Anzeigen“, wähle die Anzeige und klicke auf „Bearbeiten“. Titel, Beschreibung, Preis, Fotos und Standort können geändert werden.' },
      ]},
      { id: 'comprar', title: 'Kaufen und Kontakt', faqs: [
        { q: 'Wie kontaktiere ich den Verkäufer?', a: 'Nutze die öffentlichen Kanäle, die der Verkäufer aktiviert hat, etwa WhatsApp, Telegram oder E-Mail.' },
        { q: 'Kann ich dem Verkäufer ein Angebot machen?', a: 'Ja. Du kannst über den öffentlichen Kanal einen Preis vorschlagen und die Übergabe sicher abstimmen.' },
        { q: 'Garantiert Mercasto Transaktionen?', a: 'Mercasto ist eine Vermittlungsplattform: Wir bringen Käufer und Verkäufer zusammen, nehmen aber nicht direkt an Transaktionen teil. Triff dich an einem öffentlichen Ort, prüfe den Artikel vor der Zahlung und überweise Unbekannten niemals im Voraus Geld.' },
      ]},
      { id: 'cuenta', title: 'Mein Konto', faqs: [
        { q: 'Wie bestätige ich meine Telefonnummer?', a: 'Die SMS-Verifizierung ist vorübergehend deaktiviert. Du kannst E-Mail, Google oder Telegram nutzen; die Telefonoption erscheint wieder, sobald der Anbieter verfügbar ist.' },
        { q: 'Wie ändere ich mein Passwort?', a: 'Gehe zu Profil → „Sicherheit“ → „Passwort ändern“. Auf dem Anmeldebildschirm kannst du es außerdem über „Passwort vergessen?“ zurücksetzen.' },
        { q: 'Kann ich mich mit Google anmelden?', a: 'Ja. Auf den Anmelde- und Registrierungsseiten gibt es „Mit Google fortfahren“. Das ist schnell und sicher und erfordert kein zusätzliches Passwort.' },
      ]},
      { id: 'seguridad', title: 'Sicherheit', faqs: [
        { q: 'Wie melde ich eine verdächtige Anzeige?', a: 'Bei jeder Anzeige kannst du die Meldefunktion nutzen und den Grund angeben. Mercasto priorisiert Fälle nach Risiko und verspricht keine feste Bearbeitungsfrist.' },
        { q: 'Wie vermeide ich Betrug beim Kauf?', a: 'Teile niemals Bankdaten, Kartennummern oder Passwörter. Sei bei extrem niedrigen Preisen vorsichtig. Triff dich an einem öffentlichen Ort und prüfe den Artikel vor der Zahlung.' },
        { q: 'Wird Mercasto jemals nach meinem Passwort fragen?', a: 'Nein. Mercasto fragt weder per E-Mail noch über WhatsApp, Telegram oder andere Kanäle nach deinem Passwort. Wenn jemand dies im Namen von Mercasto tut, melde den Betrugsversuch sofort.' },
      ]},
      { id: 'destacar', title: 'Anzeigen bewerben', faqs: [
        { q: 'Was ist eine hervorgehobene Anzeige?', a: 'Ein Promotionsprodukt kann Position oder Darstellung einer Anzeige für den angegebenen Zeitraum verändern. Es garantiert weder Impressionen noch Kontakte oder einen Verkauf.' },
        { q: 'Was kostet die Bewerbung einer Anzeige?', a: 'Aktuelle Optionen: 3 Tage nach oben für $49 MXN, 7 Tage hervorheben für $79 MXN, 7 Tage Featured für $149 MXN und 7 Tage Kategorie-Top für $399 MXN.' },
        { q: 'Wie bezahle ich eine Promotion?', a: 'Im Checkout siehst du Anbieter, Leistung, Betrag und verfügbare Zahlungsmethoden. Prüfe diese Angaben vor der Bestätigung und bewahre den Beleg des Anbieters auf.' },
      ]},
    ],
  },
  it: {
    seoTitle: 'Centro assistenza Mercasto | Comprare e vendere',
    seoDescription: 'Guide ufficiali Mercasto su pubblicazione, sicurezza, acquisti, contatti, pagamenti e politiche.',
    breadcrumb: 'Centro assistenza',
    heroTitle: 'Come possiamo aiutarti?',
    heroSubtitle: 'Trova rapidamente le risposte alle domande più frequenti.',
    searchPlaceholder: 'Cerca nel Centro assistenza...',
    noResults: 'Nessun risultato per',
    tryOther: 'Prova altre parole oppure',
    clearSearch: 'cancella la ricerca',
    contactTitle: 'Non hai trovato quello che cercavi?',
    contactBody: 'Il nostro team di supporto è pronto ad aiutarti.',
    contactButton: 'Contatta il supporto',
    sections: [
      { id: 'publicar', title: 'Pubblicare annunci', faqs: [
        { q: 'Come pubblico un annuncio?', a: 'Fai clic su “Pubblica” e completa categoria, titolo, descrizione, prezzo, condizione, posizione e foto quando necessario. L’annuncio può restare in attesa durante la moderazione.' },
        { q: 'Quanti annunci posso pubblicare?', a: 'Il limite attuale dipende dalle condizioni mostrate nel tuo account e dal prodotto acquistato. “I miei annunci” mostra quanti annunci puoi gestire.' },
        { q: 'Quanto dura il mio annuncio?', a: 'Gli annunci gratuiti restano attivi 7 giorni. Poi puoi rinnovarli per altri 7 giorni a $49 MXN oppure eliminarli senza costi da “I miei annunci”.' },
        { q: 'Posso modificare un annuncio dopo averlo pubblicato?', a: 'Sì. Vai a Profilo → “I miei annunci”, scegli l’annuncio e fai clic su “Modifica”. Puoi cambiare titolo, descrizione, prezzo, foto e posizione.' },
      ]},
      { id: 'comprar', title: 'Comprare e contattare', faqs: [
        { q: 'Come contatto il venditore?', a: 'Puoi usare i canali pubblici abilitati dal venditore, come WhatsApp, Telegram o e-mail.' },
        { q: 'Posso fare un’offerta al venditore?', a: 'Sì. Puoi proporre un prezzo tramite il canale pubblico del venditore e concordare la consegna in sicurezza.' },
        { q: 'Mercasto garantisce le transazioni?', a: 'Mercasto è una piattaforma intermediaria: mette in contatto acquirenti e venditori ma non partecipa direttamente alle transazioni. Incontrati in un luogo pubblico, verifica l’articolo prima di pagare e non inviare anticipi a sconosciuti.' },
      ]},
      { id: 'cuenta', title: 'Il mio account', faqs: [
        { q: 'Come verifico il numero di telefono?', a: 'La verifica SMS è temporaneamente disabilitata. Puoi usare e-mail, Google o Telegram; Mercasto mostrerà l’opzione telefono quando il provider sarà disponibile.' },
        { q: 'Come cambio la password?', a: 'Vai a Profilo → “Sicurezza” → “Cambia password”. Puoi anche reimpostarla dalla schermata di accesso con “Password dimenticata?”.' },
        { q: 'Posso accedere con Google?', a: 'Sì. Nelle schermate di accesso e registrazione trovi “Continua con Google”. È rapido e sicuro e non richiede un’altra password.' },
      ]},
      { id: 'seguridad', title: 'Sicurezza', faqs: [
        { q: 'Come segnalo un annuncio sospetto?', a: 'Ogni annuncio offre un’opzione di segnalazione in cui puoi indicare il motivo. Mercasto assegna priorità in base al rischio e non promette tempi fissi di risoluzione.' },
        { q: 'Come evito le frodi quando acquisto?', a: 'Non condividere dati bancari, numeri di carta o password. Diffida dei prezzi estremamente bassi. Incontrati in un luogo pubblico e verifica il prodotto prima di pagare.' },
        { q: 'Mercasto mi chiederà mai la password?', a: 'Mai. Mercasto non chiederà la password tramite e-mail, WhatsApp, Telegram o altri canali. Se qualcuno la chiede fingendosi Mercasto, considera la richiesta una frode e segnalala subito.' },
      ]},
      { id: 'destacar', title: 'Promuovere annunci', faqs: [
        { q: 'Cos’è un annuncio in evidenza?', a: 'Un prodotto promozionale può modificare la posizione o la presentazione dell’annuncio per il periodo indicato. Non garantisce impressioni, contatti o vendita.' },
        { q: 'Quanto costa promuovere un annuncio?', a: 'Opzioni attuali: Salita 3 giorni $49 MXN, Evidenzia 7 giorni $79 MXN, In evidenza 7 giorni $149 MXN e Top categoria 7 giorni $399 MXN.' },
        { q: 'Come pago una promozione?', a: 'Il checkout mostra provider, voce, importo e metodi di pagamento disponibili. Controlla i dati prima di confermare e conserva la ricevuta del provider.' },
      ]},
    ],
  },
  ar: {
    seoTitle: 'مركز مساعدة Mercasto | الشراء والبيع',
    seoDescription: 'اطّلع على أدلة Mercasto الرسمية حول نشر الإعلانات والأمان والشراء والتواصل والمدفوعات والسياسات.',
    breadcrumb: 'مركز المساعدة',
    heroTitle: 'كيف يمكننا مساعدتك?',
    heroSubtitle: 'اعثر بسرعة على إجابات للأسئلة الأكثر شيوعًا.',
    searchPlaceholder: 'البحث في مركز المساعدة...',
    noResults: 'لا توجد نتائج لـ',
    tryOther: 'جرّب كلمات أخرى أو',
    clearSearch: 'امسح البحث',
    contactTitle: 'لم تجد ما تبحث عنه?',
    contactBody: 'فريق الدعم لدينا جاهز لمساعدتك.',
    contactButton: 'اتصل بالدعم',
    sections: [
      { id: 'publicar', title: 'نشر الإعلانات', faqs: [
        { q: 'كيف أنشر إعلانًا?', a: 'اضغط على “نشر” وأكمل الفئة والعنوان والوصف والسعر والحالة والموقع والصور عند الحاجة. قد يبقى الإعلان قيد الانتظار أثناء المراجعة.' },
        { q: 'كم إعلانًا يمكنني نشره?', a: 'يعتمد الحد الحالي على الشروط المعروضة في حسابك والمنتج الذي اشتريته. يعرض قسم “إعلاناتي” عدد الإعلانات التي يمكنك إدارتها.' },
        { q: 'كم يبقى إعلاني نشطًا?', a: 'تبقى الإعلانات المجانية نشطة لمدة 7 أيام. بعد ذلك يمكنك التجديد 7 أيام أخرى مقابل $49 MXN أو الحذف مجانًا من قسم “إعلاناتي”.' },
        { q: 'هل يمكنني تعديل الإعلان بعد نشره?', a: 'نعم. انتقل إلى الملف الشخصي ← “إعلاناتي”، اختر الإعلان ثم اضغط “تعديل”. يمكنك تغيير العنوان والوصف والسعر والصور والموقع.' },
      ]},
      { id: 'comprar', title: 'الشراء والتواصل', faqs: [
        { q: 'كيف أتواصل مع البائع?', a: 'يمكنك استخدام القنوات العامة التي فعّلها البائع مثل WhatsApp أو Telegram أو البريد الإلكتروني.' },
        { q: 'هل يمكنني تقديم عرض للبائع?', a: 'نعم. يمكنك اقتراح سعر عبر القناة العامة للبائع وترتيب التسليم بأمان.' },
        { q: 'هل تضمن Mercasto المعاملات?', a: 'Mercasto منصة وسيطة تربط المشترين بالبائعين ولا تشارك مباشرة في المعاملات. اتفق على التسليم في مكان عام، وافحص المنتج قبل الدفع، ولا ترسل تحويلات مقدمة إلى أشخاص لا تعرفهم.' },
      ]},
      { id: 'cuenta', title: 'حسابي', faqs: [
        { q: 'كيف أتحقق من رقم هاتفي?', a: 'التحقق عبر SMS معطل مؤقتًا. يمكنك استخدام البريد الإلكتروني أو Google أو Telegram؛ وستعرض Mercasto خيار الهاتف عندما يصبح المزود متاحًا.' },
        { q: 'كيف أغيّر كلمة المرور?', a: 'اذهب إلى الملف الشخصي ← “الأمان” ← “تغيير كلمة المرور”. ويمكنك أيضًا إعادة تعيينها من شاشة تسجيل الدخول عبر “نسيت كلمة المرور?”.' },
        { q: 'هل يمكنني تسجيل الدخول باستخدام Google?', a: 'نعم. ستجد زر “المتابعة باستخدام Google” في شاشتي تسجيل الدخول والتسجيل. الطريقة سريعة وآمنة ولا تحتاج إلى تذكر كلمة مرور إضافية.' },
      ]},
      { id: 'seguridad', title: 'الأمان', faqs: [
        { q: 'كيف أبلغ عن إعلان مشبوه?', a: 'يحتوي كل إعلان على خيار للإبلاغ مع توضيح السبب. تعطي Mercasto الأولوية للحالات حسب المخاطر ولا تعد بمدة ثابتة للحل.' },
        { q: 'كيف أتجنب الاحتيال عند الشراء?', a: 'لا تشارك بياناتك المصرفية أو أرقام البطاقات أو كلمات المرور. احذر من الأسعار المنخفضة بشكل غير منطقي. قابل البائع في مكان عام وافحص المنتج قبل الدفع.' },
        { q: 'هل ستطلب Mercasto كلمة مروري يومًا?', a: 'أبدًا. لن تطلب Mercasto كلمة مرورك عبر البريد الإلكتروني أو WhatsApp أو Telegram أو أي قناة أخرى. إذا طلبها شخص يدعي أنه من Mercasto فاعتبر ذلك احتيالًا وأبلغ عنه فورًا.' },
      ]},
      { id: 'destacar', title: 'ترويج الإعلانات', faqs: [
        { q: 'ما هو الإعلان المميز?', a: 'يمكن لمنتج الترويج تغيير موضع الإعلان أو طريقة عرضه خلال الفترة المحددة. ولا يضمن المشاهدات أو الاتصالات أو البيع.' },
        { q: 'كم تبلغ تكلفة ترويج إعلان?', a: 'الخيارات الحالية: رفع لمدة 3 أيام مقابل $49 MXN، إبراز 7 أيام مقابل $79 MXN، مميز 7 أيام مقابل $149 MXN، وأعلى الفئة 7 أيام مقابل $399 MXN.' },
        { q: 'كيف أدفع مقابل الترويج?', a: 'تعرض صفحة الدفع المزود والبند والمبلغ وطرق الدفع المتاحة. راجع البيانات قبل التأكيد واحتفظ بإيصال المزود.' },
      ]},
    ],
  },
  ru: {
    seoTitle: 'Центр помощи Mercasto | Покупка и продажа',
    seoDescription: 'Официальные инструкции Mercasto по публикации, безопасности, покупке, связи с продавцом, оплате и правилам.',
    breadcrumb: 'Центр помощи',
    heroTitle: 'Чем мы можем помочь?',
    heroSubtitle: 'Быстро найдите ответы на самые частые вопросы.',
    searchPlaceholder: 'Поиск в Центре помощи...',
    noResults: 'Нет результатов для',
    tryOther: 'Попробуйте другие слова или',
    clearSearch: 'очистите поиск',
    contactTitle: 'Не нашли нужный ответ?',
    contactBody: 'Наша служба поддержки готова помочь.',
    contactButton: 'Связаться с поддержкой',
    sections: [
      { id: 'publicar', title: 'Публикация объявлений', faqs: [
        { q: 'Как опубликовать объявление?', a: 'Нажмите «Опубликовать» и заполните категорию, заголовок, описание, цену, состояние, местоположение и при необходимости добавьте фотографии. Во время модерации объявление может оставаться на проверке.' },
        { q: 'Сколько объявлений я могу опубликовать?', a: 'Текущий лимит зависит от условий, показанных в аккаунте, и подключенного продукта. В разделе «Мои объявления» видно, сколько объявлений вы можете управлять.' },
        { q: 'Сколько действует мое объявление?', a: 'Бесплатные объявления активны 7 дней. Затем их можно продлить еще на 7 дней за $49 MXN или бесплатно удалить в разделе «Мои объявления» профиля.' },
        { q: 'Можно редактировать объявление после публикации?', a: 'Да. Откройте Профиль → «Мои объявления», выберите объявление и нажмите «Редактировать». Можно изменить заголовок, описание, цену, фотографии и местоположение.' },
      ]},
      { id: 'comprar', title: 'Покупка и связь с продавцом', faqs: [
        { q: 'Как связаться с продавцом?', a: 'Используйте публичные каналы, которые продавец включил: например WhatsApp, Telegram или электронную почту.' },
        { q: 'Можно предложить продавцу свою цену?', a: 'Да. Вы можете предложить цену через публичный канал продавца и безопасно согласовать передачу товара.' },
        { q: 'Mercasto гарантирует сделки?', a: 'Mercasto — посредническая платформа: мы соединяем покупателей и продавцов, но напрямую не участвуем в сделках. Встречайтесь в общественном месте, проверяйте товар до оплаты и не переводите аванс незнакомым людям.' },
      ]},
      { id: 'cuenta', title: 'Мой аккаунт', faqs: [
        { q: 'Как подтвердить номер телефона?', a: 'SMS-подтверждение временно отключено. Для входа можно использовать email, Google или Telegram; Mercasto покажет телефонный вариант, когда провайдер снова будет доступен.' },
        { q: 'Как изменить пароль?', a: 'Откройте Профиль → «Безопасность» → «Изменить пароль». Также пароль можно сбросить на экране входа через «Забыли пароль?». ' },
        { q: 'Можно входить через Google?', a: 'Да. На экранах входа и регистрации есть кнопка «Продолжить с Google». Это быстро и безопасно, и не нужно запоминать дополнительный пароль.' },
      ]},
      { id: 'seguridad', title: 'Безопасность', faqs: [
        { q: 'Как пожаловаться на подозрительное объявление?', a: 'В каждом объявлении есть функция жалобы, где можно указать причину. Mercasto определяет приоритет по уровню риска и не обещает фиксированный срок решения.' },
        { q: 'Как избежать мошенничества при покупке?', a: 'Не сообщайте банковские данные, номера карт или пароли. Остерегайтесь подозрительно низких цен. Встречайтесь в общественном месте и проверяйте товар до оплаты.' },
        { q: 'Mercasto когда-нибудь попросит мой пароль?', a: 'Никогда. Mercasto не просит пароль по email, WhatsApp, Telegram или другим каналам. Если кто-то просит пароль от имени Mercasto, считайте это мошенничеством и сразу сообщите об этом.' },
      ]},
      { id: 'destacar', title: 'Продвижение объявлений', faqs: [
        { q: 'Что такое выделенное объявление?', a: 'Продукт продвижения может изменить позицию или оформление объявления на указанный период. Он не гарантирует показы, обращения или продажу.' },
        { q: 'Сколько стоит продвижение объявления?', a: 'Текущие варианты: поднятие на 3 дня — $49 MXN, выделение на 7 дней — $79 MXN, Featured на 7 дней — $149 MXN, Top категории на 7 дней — $399 MXN.' },
        { q: 'Как оплатить продвижение?', a: 'На странице оплаты указаны провайдер, услуга, сумма и доступные способы оплаты. Проверьте данные перед подтверждением и сохраните квитанцию провайдера.' },
      ]},
    ],
  },
  ja: {
    seoTitle: 'Mercasto ヘルプセンター | 購入と販売',
    seoDescription: '出品、安全、購入、販売者への連絡、支払い、ポリシーに関する Mercasto 公式ガイドです。',
    breadcrumb: 'ヘルプセンター',
    heroTitle: 'どのようなお手伝いが必要ですか?',
    heroSubtitle: 'よくある質問の答えをすばやく確認できます。',
    searchPlaceholder: 'ヘルプセンターを検索...',
    noResults: '検索結果がありません:',
    tryOther: '別の言葉を試すか',
    clearSearch: '検索をクリアしてください',
    contactTitle: '探している答えが見つかりませんか?',
    contactBody: 'サポートチームがお手伝いします。',
    contactButton: 'サポートに連絡',
    sections: [
      { id: 'publicar', title: '広告を出品する', faqs: [
        { q: '広告はどうやって出品しますか?', a: '「出品」を押し、カテゴリー、タイトル、説明、価格、状態、場所、必要に応じて写真を入力してください。モデレーション中は保留になることがあります。' },
        { q: '広告は何件まで出品できますか?', a: '現在の上限はアカウントに表示される条件と購入した商品によって異なります。「マイ広告」で管理できる件数を確認できます。' },
        { q: '広告はどのくらい有効ですか?', a: '無料広告は 7 日間有効です。その後、$49 MXN でさらに 7 日間更新するか、プロフィールの「マイ広告」から無料で削除できます。' },
        { q: '公開後に広告を編集できますか?', a: 'はい。プロフィール →「マイ広告」で広告を選び「編集」を押してください。タイトル、説明、価格、写真、場所を変更できます。' },
      ]},
      { id: 'comprar', title: '購入と連絡', faqs: [
        { q: '販売者にはどう連絡しますか?', a: '販売者が公開している WhatsApp、Telegram、メールなどの連絡手段を利用できます。' },
        { q: '販売者に価格を提案できますか?', a: 'はい。販売者の公開連絡先から価格を提案し、安全に受け渡しを調整できます。' },
        { q: 'Mercasto は取引を保証しますか?', a: 'Mercasto は買い手と売り手をつなぐ仲介プラットフォームで、取引に直接参加しません。公共の場所で受け渡しを行い、支払い前に商品を確認し、知らない相手に前払い送金をしないでください。' },
      ]},
      { id: 'cuenta', title: 'マイアカウント', faqs: [
        { q: '電話番号はどう確認しますか?', a: 'SMS 認証は一時的に無効になっています。メール、Google、Telegram を利用でき、プロバイダーが利用可能になると電話認証の選択肢が表示されます。' },
        { q: 'パスワードはどう変更しますか?', a: 'プロフィール →「セキュリティ」→「パスワード変更」に進んでください。ログイン画面の「パスワードを忘れた場合」からも再設定できます。' },
        { q: 'Google でログインできますか?', a: 'はい。ログインと登録画面に「Google で続行」があります。速く安全で、追加のパスワードを覚える必要もありません。' },
      ]},
      { id: 'seguridad', title: '安全', faqs: [
        { q: '不審な広告はどう報告しますか?', a: '各広告の報告機能から理由を送信できます。Mercasto はリスクに応じて優先順位を決め、固定の解決期限は約束しません。' },
        { q: '購入時の詐欺を避けるには?', a: '銀行情報、カード番号、パスワードを共有しないでください。不自然に安い価格に注意し、公共の場所で会い、支払い前に商品を確認してください。' },
        { q: 'Mercasto がパスワードを求めることはありますか?', a: 'ありません。Mercasto はメール、WhatsApp、Telegram などでパスワードを求めません。Mercasto を名乗る相手が要求した場合は詐欺として直ちに報告してください。' },
      ]},
      { id: 'destacar', title: '広告のプロモーション', faqs: [
        { q: '注目広告とは何ですか?', a: 'プロモーション商品は指定期間中に広告の位置や表示を変更できますが、表示回数、問い合わせ、販売を保証するものではありません。' },
        { q: '広告のプロモーションはいくらですか?', a: '現在のオプション: 3 日間の順位アップ $49 MXN、7 日間のハイライト $79 MXN、7 日間の Featured $149 MXN、7 日間のカテゴリ Top $399 MXN。' },
        { q: 'プロモーション料金はどう支払いますか?', a: 'チェックアウトにはプロバイダー、項目、金額、利用可能な支払い方法が表示されます。確定前に確認し、プロバイダーの領収書を保管してください。' },
      ]},
    ],
  },
});

export const HELP_CENTER_LANGUAGES = Object.freeze(Object.keys(HELP_CENTER_COPY));

export function hasHelpCenterCopy(language) {
  const raw = String(language || '').trim().toLowerCase().split('-')[0];
  return HELP_CENTER_LANGUAGES.includes(raw);
}

export function getHelpCenterCopy(language = 'es') {
  return HELP_CENTER_COPY[normalizeLanguage(language)] || HELP_CENTER_COPY.es;
}
