import { normalizeLanguage } from './translations.js';

const ONBOARDING_EXPERIENCE_COPY = {
  es: {
    roleTitle: 'Qué quieres hacer?', roleSubtitle: 'Personalizaremos tu experiencia',
    roles: {
      buyer: ['Comprar', 'Encuentra lo que necesitas cerca de ti'],
      seller: ['Vender', 'Publica lo que ya no usas u ofrece tus servicios'],
      both: ['Comprar y vender', 'Aprovecha todas las opciones de Mercasto'],
    },
    interestsTitle: 'Qué te interesa?', interestsSubtitle: 'Elige categorías para personalizar tu inicio',
    interestsOptional: 'Esta selección es opcional y puedes cambiarla después', selectedCount: '{count}/9 seleccionadas',
    interests: { motor: 'Autos y motos', inmobiliaria: 'Inmuebles', empleo: 'Empleo', servicios: 'Servicios', tecnologia: 'Tecnología', hogar: 'Hogar', moda: 'Moda', deportes: 'Deportes', mascotas: 'Mascotas' },
    howTitle: { buyer: 'Cómo comprar en Mercasto?', seller: 'Cómo vender en Mercasto?', both: 'Cómo funciona Mercasto?' },
    how: {
      buyer: [['Busca', 'Encuentra lo que necesitas por categoría, ciudad o precio'], ['Contacta', 'Habla directamente con el vendedor por sus canales públicos'], ['Compra', 'Acuerda la entrega y recibe tu producto']],
      seller: [['Crea tu anuncio', 'Sube fotos y describe lo que vendes en minutos'], ['Coordina', 'Responde a interesados y acuerda la entrega'], ['Vende', 'Acuerda la entrega y el pago directamente con la persona interesada']],
      both: [['Crea o busca', 'Publica un anuncio o encuentra lo que necesitas'], ['Coordina con confianza', 'Usa los canales públicos y revisa la reputación'], ['Compra o vende', 'Acuerda la entrega y el pago directamente con la otra persona']],
    },
    welcomeBody: 'Explora clasificados por categoría y publica lo que quieres vender en México.',
    welcomeChips: ['🚗 Autos', '🏠 Casas', '💼 Empleos', '📱 Tecnología', '🔧 Servicios'],
    pricingFree: 'Primera activación elegible: 0 MXN por 7 días', pricingRenew: 'Después puedes renovar por 49 MXN por 7 días adicionales.',
    buyerMapTip: 'Usa el mapa para encontrar anuncios cerca de ti', sellerAiTip: 'La AI te ayuda a escribir descripciones atractivas',
    profileNotificationsTip: 'Activa notificaciones para nuevos anuncios',
    cta: { buyer: ['Explorar anuncios', 'Completar mi perfil'], seller: ['Crear mi primer anuncio', 'Explorar clasificados'], both: ['Crear mi primer anuncio', 'Explorar clasificados'] },
  },
  en: {
    roleTitle: 'What do you want to do?', roleSubtitle: 'We will personalize your experience',
    roles: { buyer: ['Buy', 'Find what you need near you'], seller: ['Sell', 'Post items you no longer use or offer your services'], both: ['Buy and sell', 'Use all of Mercasto’s options'] },
    interestsTitle: 'What are you interested in?', interestsSubtitle: 'Choose categories to personalize your home feed', interestsOptional: 'This selection is optional and you can change it later', selectedCount: '{count}/9 selected',
    interests: { motor: 'Cars and motorcycles', inmobiliaria: 'Real estate', empleo: 'Jobs', servicios: 'Services', tecnologia: 'Technology', hogar: 'Home', moda: 'Fashion', deportes: 'Sports', mascotas: 'Pets' },
    howTitle: { buyer: 'How to buy on Mercasto?', seller: 'How to sell on Mercasto?', both: 'How does Mercasto work?' },
    how: {
      buyer: [['Search', 'Find what you need by category, city, or price'], ['Contact', 'Talk directly with the seller through their public channels'], ['Buy', 'Arrange delivery and receive your item']],
      seller: [['Create your listing', 'Upload photos and describe what you sell in minutes'], ['Coordinate', 'Reply to interested buyers and arrange delivery'], ['Sell', 'Agree on delivery and payment directly with the interested person']],
      both: [['Post or search', 'Create a listing or find what you need'], ['Coordinate confidently', 'Use public channels and check reputation'], ['Buy or sell', 'Agree on delivery and payment directly with the other person']],
    },
    welcomeBody: 'Browse classifieds by category and post what you want to sell in Mexico.', welcomeChips: ['🚗 Cars', '🏠 Homes', '💼 Jobs', '📱 Tech', '🔧 Services'],
    pricingFree: 'Eligible first activation: 0 MXN for 7 days', pricingRenew: 'Then you can renew for 49 MXN for 7 additional days.',
    buyerMapTip: 'Use the map to find listings near you', sellerAiTip: 'AI helps you write attractive descriptions', profileNotificationsTip: 'Turn on notifications for new listings',
    cta: { buyer: ['Browse listings', 'Complete my profile'], seller: ['Create my first listing', 'Browse classifieds'], both: ['Create my first listing', 'Browse classifieds'] },
  },
  pt: {
    roleTitle: 'O que você quer fazer?', roleSubtitle: 'Vamos personalizar sua experiência',
    roles: { buyer: ['Comprar', 'Encontre o que precisa perto de você'], seller: ['Vender', 'Publique o que não usa mais ou ofereça seus serviços'], both: ['Comprar e vender', 'Aproveite todas as opções do Mercasto'] },
    interestsTitle: 'O que interessa a você?', interestsSubtitle: 'Escolha categorias para personalizar sua página inicial', interestsOptional: 'Esta seleção é opcional e pode ser alterada depois', selectedCount: '{count}/9 selecionadas',
    interests: { motor: 'Carros e motos', inmobiliaria: 'Imóveis', empleo: 'Empregos', servicios: 'Serviços', tecnologia: 'Tecnologia', hogar: 'Casa', moda: 'Moda', deportes: 'Esportes', mascotas: 'Animais de estimação' },
    howTitle: { buyer: 'Como comprar no Mercasto?', seller: 'Como vender no Mercasto?', both: 'Como funciona o Mercasto?' },
    how: {
      buyer: [['Busque', 'Encontre o que precisa por categoria, cidade ou preço'], ['Entre em contato', 'Fale diretamente com o vendedor pelos canais públicos'], ['Compre', 'Combine a entrega e receba o produto']],
      seller: [['Crie seu anúncio', 'Envie fotos e descreva o que vende em poucos minutos'], ['Combine', 'Responda aos interessados e combine a entrega'], ['Venda', 'Combine entrega e pagamento diretamente com a pessoa interessada']],
      both: [['Publique ou busque', 'Crie um anúncio ou encontre o que precisa'], ['Combine com confiança', 'Use canais públicos e confira a reputação'], ['Compre ou venda', 'Combine entrega e pagamento diretamente com a outra pessoa']],
    },
    welcomeBody: 'Explore classificados por categoria e publique o que deseja vender no México.', welcomeChips: ['🚗 Carros', '🏠 Imóveis', '💼 Empregos', '📱 Tecnologia', '🔧 Serviços'],
    pricingFree: 'Primeira ativação elegível: 0 MXN por 7 dias', pricingRenew: 'Depois, você pode renovar por 49 MXN por mais 7 dias.',
    buyerMapTip: 'Use o mapa para encontrar anúncios perto de você', sellerAiTip: 'A AI ajuda a escrever descrições atraentes', profileNotificationsTip: 'Ative notificações para novos anúncios',
    cta: { buyer: ['Explorar anúncios', 'Completar meu perfil'], seller: ['Criar meu primeiro anúncio', 'Explorar classificados'], both: ['Criar meu primeiro anúncio', 'Explorar classificados'] },
  },
  fr: {
    roleTitle: 'Que voulez-vous faire ?', roleSubtitle: 'Nous allons personnaliser votre expérience',
    roles: { buyer: ['Acheter', 'Trouvez ce dont vous avez besoin près de chez vous'], seller: ['Vendre', 'Publiez ce que vous n’utilisez plus ou proposez vos services'], both: ['Acheter et vendre', 'Profitez de toutes les possibilités de Mercasto'] },
    interestsTitle: 'Qu’est-ce qui vous intéresse ?', interestsSubtitle: 'Choisissez des catégories pour personnaliser votre accueil', interestsOptional: 'Cette sélection est facultative et peut être modifiée plus tard', selectedCount: '{count}/9 sélectionnées',
    interests: { motor: 'Autos et motos', inmobiliaria: 'Immobilier', empleo: 'Emplois', servicios: 'Services', tecnologia: 'Technologie', hogar: 'Maison', moda: 'Mode', deportes: 'Sports', mascotas: 'Animaux' },
    howTitle: { buyer: 'Comment acheter sur Mercasto ?', seller: 'Comment vendre sur Mercasto ?', both: 'Comment fonctionne Mercasto ?' },
    how: {
      buyer: [['Recherchez', 'Trouvez ce qu’il vous faut par catégorie, ville ou prix'], ['Contactez', 'Échangez directement avec le vendeur via ses canaux publics'], ['Achetez', 'Organisez la remise et recevez votre article']],
      seller: [['Créez votre annonce', 'Ajoutez des photos et décrivez ce que vous vendez en quelques minutes'], ['Organisez', 'Répondez aux personnes intéressées et organisez la remise'], ['Vendez', 'Convenez directement de la remise et du paiement avec la personne intéressée']],
      both: [['Publiez ou recherchez', 'Créez une annonce ou trouvez ce qu’il vous faut'], ['Organisez en confiance', 'Utilisez les canaux publics et vérifiez la réputation'], ['Achetez ou vendez', 'Convenez directement de la remise et du paiement avec l’autre personne']],
    },
    welcomeBody: 'Parcourez les petites annonces par catégorie et publiez ce que vous souhaitez vendre au Mexique.', welcomeChips: ['🚗 Autos', '🏠 Logements', '💼 Emplois', '📱 Tech', '🔧 Services'],
    pricingFree: 'Première activation éligible : 0 MXN pendant 7 jours', pricingRenew: 'Vous pouvez ensuite renouveler pour 49 MXN pendant 7 jours supplémentaires.',
    buyerMapTip: 'Utilisez la carte pour trouver des annonces près de chez vous', sellerAiTip: 'L’AI vous aide à rédiger des descriptions attrayantes', profileNotificationsTip: 'Activez les notifications pour les nouvelles annonces',
    cta: { buyer: ['Voir les annonces', 'Compléter mon profil'], seller: ['Créer ma première annonce', 'Parcourir les annonces'], both: ['Créer ma première annonce', 'Parcourir les annonces'] },
  },
  zh: {
    roleTitle: '你想做什么？', roleSubtitle: '我们会为你定制使用体验',
    roles: { buyer: ['购买', '寻找附近需要的商品或服务'], seller: ['出售', '发布闲置物品或提供服务'], both: ['买卖都需要', '使用 Mercasto 的全部功能'] },
    interestsTitle: '你对什么感兴趣？', interestsSubtitle: '选择类别来个性化首页', interestsOptional: '此选择为可选项，之后可以修改', selectedCount: '已选择 {count}/9',
    interests: { motor: '汽车和摩托车', inmobiliaria: '房地产', empleo: '工作', servicios: '服务', tecnologia: '科技', hogar: '家居', moda: '时尚', deportes: '运动', mascotas: '宠物' },
    howTitle: { buyer: '如何在 Mercasto 购买？', seller: '如何在 Mercasto 出售？', both: 'Mercasto 如何使用？' },
    how: {
      buyer: [['搜索', '按类别、城市或价格查找需要的内容'], ['联系', '通过卖家的公开联系方式直接沟通'], ['购买', '协商交付并收到商品']],
      seller: [['创建广告', '上传照片并在几分钟内描述要出售的内容'], ['协商', '回复感兴趣的买家并安排交付'], ['出售', '直接与对方协商交付和付款']],
      both: [['发布或搜索', '创建广告或查找需要的内容'], ['放心沟通', '使用公开联系方式并查看信誉'], ['购买或出售', '直接与对方协商交付和付款']],
    },
    welcomeBody: '按类别浏览分类广告，并发布你想在墨西哥出售的内容。', welcomeChips: ['🚗 汽车', '🏠 房产', '💼 工作', '📱 科技', '🔧 服务'],
    pricingFree: '符合条件的首次激活：0 MXN，7 天', pricingRenew: '之后可支付 49 MXN 再续 7 天。',
    buyerMapTip: '使用地图查找附近的广告', sellerAiTip: 'AI 可帮助你撰写更吸引人的描述', profileNotificationsTip: '开启新广告通知',
    cta: { buyer: ['浏览广告', '完善个人资料'], seller: ['创建我的第一条广告', '浏览分类广告'], both: ['创建我的第一条广告', '浏览分类广告'] },
  },
  ko: {
    roleTitle: '무엇을 하고 싶으신가요?', roleSubtitle: '사용 경험을 맞춤 설정해 드립니다',
    roles: { buyer: ['구매', '내 주변에서 필요한 것을 찾아보세요'], seller: ['판매', '사용하지 않는 물건을 등록하거나 서비스를 제공하세요'], both: ['구매와 판매', 'Mercasto의 모든 기능을 이용하세요'] },
    interestsTitle: '무엇에 관심이 있나요?', interestsSubtitle: '홈 화면을 맞춤 설정할 카테고리를 선택하세요', interestsOptional: '선택 사항이며 나중에 변경할 수 있습니다', selectedCount: '{count}/9 선택됨',
    interests: { motor: '자동차와 오토바이', inmobiliaria: '부동산', empleo: '채용', servicios: '서비스', tecnologia: '기술', hogar: '홈', moda: '패션', deportes: '스포츠', mascotas: '반려동물' },
    howTitle: { buyer: 'Mercasto에서 어떻게 구매하나요?', seller: 'Mercasto에서 어떻게 판매하나요?', both: 'Mercasto는 어떻게 이용하나요?' },
    how: {
      buyer: [['검색', '카테고리, 도시 또는 가격으로 필요한 것을 찾으세요'], ['연락', '판매자의 공개 연락 채널로 직접 문의하세요'], ['구매', '전달 방법을 정하고 상품을 받으세요']],
      seller: [['광고 만들기', '사진을 올리고 몇 분 안에 판매 내용을 작성하세요'], ['조율', '관심 있는 구매자에게 답하고 전달 방법을 정하세요'], ['판매', '상대방과 직접 전달 및 결제 방법을 합의하세요']],
      both: [['등록 또는 검색', '광고를 만들거나 필요한 것을 찾으세요'], ['안심하고 조율', '공개 연락 채널과 평판을 확인하세요'], ['구매 또는 판매', '상대방과 직접 전달 및 결제 방법을 합의하세요']],
    },
    welcomeBody: '카테고리별 광고를 둘러보고 멕시코에서 판매할 내용을 등록하세요.', welcomeChips: ['🚗 자동차', '🏠 부동산', '💼 채용', '📱 기술', '🔧 서비스'],
    pricingFree: '대상 광고 첫 활성화: 7일간 0 MXN', pricingRenew: '이후 49 MXN으로 7일 더 갱신할 수 있습니다.',
    buyerMapTip: '지도로 주변 광고를 찾아보세요', sellerAiTip: 'AI가 매력적인 설명 작성을 도와줍니다', profileNotificationsTip: '새 광고 알림을 켜세요',
    cta: { buyer: ['광고 둘러보기', '프로필 완성'], seller: ['첫 광고 만들기', '광고 둘러보기'], both: ['첫 광고 만들기', '광고 둘러보기'] },
  },
  de: {
    roleTitle: 'Was möchten Sie tun?', roleSubtitle: 'Wir personalisieren Ihre Erfahrung',
    roles: { buyer: ['Kaufen', 'Finden Sie, was Sie in Ihrer Nähe brauchen'], seller: ['Verkaufen', 'Inserieren Sie ungenutzte Dinge oder bieten Sie Ihre Dienste an'], both: ['Kaufen und verkaufen', 'Nutzen Sie alle Möglichkeiten von Mercasto'] },
    interestsTitle: 'Was interessiert Sie?', interestsSubtitle: 'Wählen Sie Kategorien für eine personalisierte Startseite', interestsOptional: 'Diese Auswahl ist optional und kann später geändert werden', selectedCount: '{count}/9 ausgewählt',
    interests: { motor: 'Autos und Motorräder', inmobiliaria: 'Immobilien', empleo: 'Jobs', servicios: 'Dienstleistungen', tecnologia: 'Technik', hogar: 'Haus und Wohnen', moda: 'Mode', deportes: 'Sport', mascotas: 'Haustiere' },
    howTitle: { buyer: 'Wie kauft man auf Mercasto?', seller: 'Wie verkauft man auf Mercasto?', both: 'Wie funktioniert Mercasto?' },
    how: {
      buyer: [['Suchen', 'Finden Sie nach Kategorie, Stadt oder Preis, was Sie brauchen'], ['Kontaktieren', 'Sprechen Sie direkt über die öffentlichen Kanäle mit dem Verkäufer'], ['Kaufen', 'Vereinbaren Sie die Übergabe und erhalten Sie den Artikel']],
      seller: [['Anzeige erstellen', 'Laden Sie Fotos hoch und beschreiben Sie Ihr Angebot in wenigen Minuten'], ['Abstimmen', 'Antworten Sie Interessenten und vereinbaren Sie die Übergabe'], ['Verkaufen', 'Vereinbaren Sie Übergabe und Zahlung direkt mit der interessierten Person']],
      both: [['Inserieren oder suchen', 'Erstellen Sie eine Anzeige oder finden Sie, was Sie brauchen'], ['Sicher abstimmen', 'Nutzen Sie öffentliche Kanäle und prüfen Sie die Reputation'], ['Kaufen oder verkaufen', 'Vereinbaren Sie Übergabe und Zahlung direkt mit der anderen Person']],
    },
    welcomeBody: 'Durchsuchen Sie Kleinanzeigen nach Kategorie und inserieren Sie, was Sie in Mexiko verkaufen möchten.', welcomeChips: ['🚗 Autos', '🏠 Immobilien', '💼 Jobs', '📱 Technik', '🔧 Dienste'],
    pricingFree: 'Erste berechtigte Aktivierung: 0 MXN für 7 Tage', pricingRenew: 'Danach können Sie für 49 MXN um weitere 7 Tage verlängern.',
    buyerMapTip: 'Nutzen Sie die Karte für Anzeigen in Ihrer Nähe', sellerAiTip: 'AI hilft Ihnen, attraktive Beschreibungen zu schreiben', profileNotificationsTip: 'Aktivieren Sie Benachrichtigungen für neue Anzeigen',
    cta: { buyer: ['Anzeigen ansehen', 'Mein Profil vervollständigen'], seller: ['Meine erste Anzeige erstellen', 'Kleinanzeigen ansehen'], both: ['Meine erste Anzeige erstellen', 'Kleinanzeigen ansehen'] },
  },
  it: {
    roleTitle: 'Cosa vuoi fare?', roleSubtitle: 'Personalizzeremo la tua esperienza',
    roles: { buyer: ['Comprare', 'Trova ciò che ti serve vicino a te'], seller: ['Vendere', 'Pubblica ciò che non usi più o offri i tuoi servizi'], both: ['Comprare e vendere', 'Usa tutte le possibilità di Mercasto'] },
    interestsTitle: 'Cosa ti interessa?', interestsSubtitle: 'Scegli le categorie per personalizzare la home', interestsOptional: 'La selezione è facoltativa e può essere modificata in seguito', selectedCount: '{count}/9 selezionate',
    interests: { motor: 'Auto e moto', inmobiliaria: 'Immobili', empleo: 'Lavoro', servicios: 'Servizi', tecnologia: 'Tecnologia', hogar: 'Casa', moda: 'Moda', deportes: 'Sport', mascotas: 'Animali' },
    howTitle: { buyer: 'Come comprare su Mercasto?', seller: 'Come vendere su Mercasto?', both: 'Come funziona Mercasto?' },
    how: {
      buyer: [['Cerca', 'Trova ciò che ti serve per categoria, città o prezzo'], ['Contatta', 'Parla direttamente con il venditore tramite i suoi canali pubblici'], ['Compra', 'Concorda la consegna e ricevi l’articolo']],
      seller: [['Crea il tuo annuncio', 'Carica foto e descrivi ciò che vendi in pochi minuti'], ['Organizza', 'Rispondi agli interessati e concorda la consegna'], ['Vendi', 'Concorda consegna e pagamento direttamente con la persona interessata']],
      both: [['Pubblica o cerca', 'Crea un annuncio o trova ciò che ti serve'], ['Organizza con fiducia', 'Usa i canali pubblici e controlla la reputazione'], ['Compra o vendi', 'Concorda consegna e pagamento direttamente con l’altra persona']],
    },
    welcomeBody: 'Esplora gli annunci per categoria e pubblica ciò che vuoi vendere in Messico.', welcomeChips: ['🚗 Auto', '🏠 Immobili', '💼 Lavoro', '📱 Tecnologia', '🔧 Servizi'],
    pricingFree: 'Prima attivazione idonea: 0 MXN per 7 giorni', pricingRenew: 'Poi puoi rinnovare per 49 MXN per altri 7 giorni.',
    buyerMapTip: 'Usa la mappa per trovare annunci vicino a te', sellerAiTip: 'AI ti aiuta a scrivere descrizioni accattivanti', profileNotificationsTip: 'Attiva le notifiche per i nuovi annunci',
    cta: { buyer: ['Esplora gli annunci', 'Completa il mio profilo'], seller: ['Crea il mio primo annuncio', 'Esplora gli annunci'], both: ['Crea il mio primo annuncio', 'Esplora gli annunci'] },
  },
  ar: {
    roleTitle: 'ماذا تريد أن تفعل؟', roleSubtitle: 'سنخصص تجربتك',
    roles: { buyer: ['الشراء', 'اعثر على ما تحتاجه بالقرب منك'], seller: ['البيع', 'انشر ما لم تعد تستخدمه أو اعرض خدماتك'], both: ['الشراء والبيع', 'استفد من جميع خيارات Mercasto'] },
    interestsTitle: 'ما الذي يهمك؟', interestsSubtitle: 'اختر فئات لتخصيص صفحتك الرئيسية', interestsOptional: 'هذا الاختيار اختياري ويمكنك تغييره لاحقًا', selectedCount: 'تم اختيار {count}/9',
    interests: { motor: 'السيارات والدراجات النارية', inmobiliaria: 'العقارات', empleo: 'الوظائف', servicios: 'الخدمات', tecnologia: 'التقنية', hogar: 'المنزل', moda: 'الأزياء', deportes: 'الرياضة', mascotas: 'الحيوانات الأليفة' },
    howTitle: { buyer: 'كيف تشتري على Mercasto؟', seller: 'كيف تبيع على Mercasto؟', both: 'كيف يعمل Mercasto؟' },
    how: {
      buyer: [['ابحث', 'اعثر على ما تحتاجه حسب الفئة أو المدينة أو السعر'], ['تواصل', 'تحدث مباشرة مع البائع عبر قنواته العامة'], ['اشترِ', 'نسّق التسليم واستلم المنتج']],
      seller: [['أنشئ إعلانك', 'حمّل الصور وصف ما تبيعه خلال دقائق'], ['نسّق', 'رد على المهتمين واتفق على التسليم'], ['بِع', 'اتفق مباشرة مع الشخص المهتم على التسليم والدفع']],
      both: [['انشر أو ابحث', 'أنشئ إعلانًا أو اعثر على ما تحتاجه'], ['نسّق بثقة', 'استخدم القنوات العامة وتحقق من السمعة'], ['اشترِ أو بِع', 'اتفق مباشرة مع الطرف الآخر على التسليم والدفع']],
    },
    welcomeBody: 'تصفح الإعلانات حسب الفئة وانشر ما تريد بيعه في المكسيك.', welcomeChips: ['🚗 سيارات', '🏠 عقارات', '💼 وظائف', '📱 تقنية', '🔧 خدمات'],
    pricingFree: 'أول تفعيل مؤهل: 0 MXN لمدة 7 أيام', pricingRenew: 'بعد ذلك يمكنك التجديد مقابل 49 MXN لمدة 7 أيام إضافية.',
    buyerMapTip: 'استخدم الخريطة للعثور على إعلانات قريبة منك', sellerAiTip: 'تساعدك AI في كتابة أوصاف جذابة', profileNotificationsTip: 'فعّل إشعارات الإعلانات الجديدة',
    cta: { buyer: ['تصفح الإعلانات', 'إكمال ملفي الشخصي'], seller: ['إنشاء إعلاني الأول', 'تصفح الإعلانات'], both: ['إنشاء إعلاني الأول', 'تصفح الإعلانات'] },
  },
  ru: {
    roleTitle: 'Что вы хотите делать?', roleSubtitle: 'Мы настроим Mercasto под ваши задачи',
    roles: { buyer: ['Покупать', 'Находите нужное рядом с вами'], seller: ['Продавать', 'Размещайте ненужные вещи или предлагайте услуги'], both: ['Покупать и продавать', 'Используйте все возможности Mercasto'] },
    interestsTitle: 'Что вас интересует?', interestsSubtitle: 'Выберите категории, чтобы настроить главную страницу', interestsOptional: 'Это необязательно — выбор можно изменить позже', selectedCount: 'Выбрано {count}/9',
    interests: { motor: 'Авто и мото', inmobiliaria: 'Недвижимость', empleo: 'Работа', servicios: 'Услуги', tecnologia: 'Техника', hogar: 'Дом', moda: 'Мода', deportes: 'Спорт', mascotas: 'Животные' },
    howTitle: { buyer: 'Как покупать на Mercasto?', seller: 'Как продавать на Mercasto?', both: 'Как работает Mercasto?' },
    how: {
      buyer: [['Найдите', 'Ищите нужное по категории, городу или цене'], ['Свяжитесь', 'Напишите продавцу напрямую через его публичные каналы'], ['Купите', 'Договоритесь о передаче и получите товар']],
      seller: [['Создайте объявление', 'Добавьте фотографии и за несколько минут опишите предложение'], ['Договоритесь', 'Ответьте заинтересованным и согласуйте передачу'], ['Продайте', 'Напрямую договоритесь с покупателем о передаче и оплате']],
      both: [['Разместите или найдите', 'Создайте объявление или найдите нужное'], ['Договоритесь уверенно', 'Используйте публичные контакты и проверяйте репутацию'], ['Купите или продайте', 'Напрямую согласуйте с другой стороной передачу и оплату']],
    },
    welcomeBody: 'Просматривайте объявления по категориям и размещайте то, что хотите продать в Мексике.', welcomeChips: ['🚗 Авто', '🏠 Недвижимость', '💼 Работа', '📱 Техника', '🔧 Услуги'],
    pricingFree: 'Первая подходящая активация: 0 MXN на 7 дней', pricingRenew: 'Затем можно продлить ещё на 7 дней за 49 MXN.',
    buyerMapTip: 'Используйте карту, чтобы найти объявления рядом', sellerAiTip: 'AI помогает писать привлекательные описания', profileNotificationsTip: 'Включите уведомления о новых объявлениях',
    cta: { buyer: ['Смотреть объявления', 'Заполнить профиль'], seller: ['Создать первое объявление', 'Смотреть объявления'], both: ['Создать первое объявление', 'Смотреть объявления'] },
  },
  ja: {
    roleTitle: '何をしたいですか？', roleSubtitle: '利用目的に合わせて表示を調整します',
    roles: { buyer: ['購入する', '近くで必要なものを探せます'], seller: ['販売する', '不要になった物を出品したりサービスを提供できます'], both: ['購入と販売', 'Mercasto のすべての機能を利用できます'] },
    interestsTitle: '何に興味がありますか？', interestsSubtitle: 'ホームをカスタマイズするカテゴリを選んでください', interestsOptional: 'この選択は任意で、後から変更できます', selectedCount: '{count}/9 選択済み',
    interests: { motor: '車・バイク', inmobiliaria: '不動産', empleo: '求人', servicios: 'サービス', tecnologia: 'テクノロジー', hogar: 'ホーム', moda: 'ファッション', deportes: 'スポーツ', mascotas: 'ペット' },
    howTitle: { buyer: 'Mercasto で購入するには？', seller: 'Mercasto で販売するには？', both: 'Mercasto の使い方' },
    how: {
      buyer: [['探す', 'カテゴリ、都市、価格から必要なものを探します'], ['連絡する', '出品者の公開連絡先から直接やり取りします'], ['購入する', '受け渡し方法を決めて商品を受け取ります']],
      seller: [['広告を作成', '写真を追加し、数分で販売内容を記入します'], ['調整する', '興味を持った人に返信し、受け渡しを決めます'], ['販売する', '相手と直接、受け渡しと支払いを決めます']],
      both: [['出品または検索', '広告を作成するか、必要なものを探します'], ['安心して調整', '公開連絡先と評価を確認します'], ['購入または販売', '相手と直接、受け渡しと支払いを決めます']],
    },
    welcomeBody: 'カテゴリから広告を探し、メキシコで売りたいものを出品できます。', welcomeChips: ['🚗 車', '🏠 不動産', '💼 求人', '📱 テクノロジー', '🔧 サービス'],
    pricingFree: '対象広告の初回有効化：7日間 0 MXN', pricingRenew: 'その後は 49 MXN でさらに7日間更新できます。',
    buyerMapTip: '地図で近くの広告を探せます', sellerAiTip: 'AI が魅力的な説明文の作成をサポートします', profileNotificationsTip: '新しい広告の通知をオンにする',
    cta: { buyer: ['広告を見る', 'プロフィールを完成'], seller: ['最初の広告を作成', '広告を見る'], both: ['最初の広告を作成', '広告を見る'] },
  },
};

export function getOnboardingExperienceCopy(language = 'es') {
  return ONBOARDING_EXPERIENCE_COPY[normalizeLanguage(language)] || ONBOARDING_EXPERIENCE_COPY.es;
}

export { ONBOARDING_EXPERIENCE_COPY };
