export const listingAutofillCopy = {
  es: { title: 'Completar con IA', subtitle: 'Obtén sugerencias privadas a partir de una foto o una frase. Tú decides qué aplicar.', placeholder: 'Ej. Nissan Versa 2022 usado...', analyze: 'Sugerir datos', analyzing: 'Analizando...', unavailable: 'Las sugerencias no están disponibles. Puedes continuar manualmente.', apply: 'Aplicar', category: 'Categoría', subcategory: 'Subcategoría', titleField: 'Título', description: 'Descripción', attributes: 'Atributos', confidence: 'confianza', privacy: 'Procesamiento privado · no publica ni cambia datos automáticamente', noInput: 'Agrega una frase o al menos una foto nueva.' },
  en: { title: 'Fill with AI', subtitle: 'Get private suggestions from a photo or short phrase. You choose what to apply.', placeholder: 'e.g. Used 2022 Nissan Versa...', analyze: 'Suggest details', analyzing: 'Analyzing...', unavailable: 'Suggestions are unavailable. You can continue manually.', apply: 'Apply', category: 'Category', subcategory: 'Subcategory', titleField: 'Title', description: 'Description', attributes: 'Attributes', confidence: 'confidence', privacy: 'Private processing · never publishes or changes fields automatically', noInput: 'Add a short phrase or at least one new photo.' },
  pt: { title: 'Preencher com IA', subtitle: 'Receba sugestões privadas a partir de uma foto ou frase. Você decide o que aplicar.', placeholder: 'Ex. Nissan Versa 2022 usado...', analyze: 'Sugerir dados', analyzing: 'Analisando...', unavailable: 'As sugestões não estão disponíveis. Continue manualmente.', apply: 'Aplicar', category: 'Categoria', subcategory: 'Subcategoria', titleField: 'Título', description: 'Descrição', attributes: 'Atributos', confidence: 'confiança', privacy: 'Processamento privado · não publica nem altera campos automaticamente', noInput: 'Adicione uma frase ou pelo menos uma foto nova.' },
  fr: { title: 'Remplir avec l’IA', subtitle: 'Obtenez des suggestions privées à partir d’une photo ou d’une phrase. Vous choisissez quoi appliquer.', placeholder: 'Ex. Nissan Versa 2022 d’occasion...', analyze: 'Suggérer', analyzing: 'Analyse...', unavailable: 'Suggestions indisponibles. Vous pouvez continuer manuellement.', apply: 'Appliquer', category: 'Catégorie', subcategory: 'Sous-catégorie', titleField: 'Titre', description: 'Description', attributes: 'Attributs', confidence: 'confiance', privacy: 'Traitement privé · aucune publication ou modification automatique', noInput: 'Ajoutez une phrase ou au moins une nouvelle photo.' },
  de: { title: 'Mit KI ausfüllen', subtitle: 'Private Vorschläge aus Foto oder Kurztext. Du entscheidest, was übernommen wird.', placeholder: 'z. B. gebrauchter Nissan Versa 2022...', analyze: 'Daten vorschlagen', analyzing: 'Analyse...', unavailable: 'Vorschläge sind nicht verfügbar. Du kannst manuell fortfahren.', apply: 'Übernehmen', category: 'Kategorie', subcategory: 'Unterkategorie', titleField: 'Titel', description: 'Beschreibung', attributes: 'Attribute', confidence: 'Sicherheit', privacy: 'Private Verarbeitung · keine automatische Veröffentlichung oder Feldänderung', noInput: 'Füge einen Kurztext oder mindestens ein neues Foto hinzu.' },
  it: { title: 'Compila con IA', subtitle: 'Ottieni suggerimenti privati da una foto o una breve frase. Decidi tu cosa applicare.', placeholder: 'Es. Nissan Versa 2022 usata...', analyze: 'Suggerisci dati', analyzing: 'Analisi...', unavailable: 'Suggerimenti non disponibili. Puoi continuare manualmente.', apply: 'Applica', category: 'Categoria', subcategory: 'Sottocategoria', titleField: 'Titolo', description: 'Descrizione', attributes: 'Attributi', confidence: 'affidabilità', privacy: 'Elaborazione privata · nessuna pubblicazione o modifica automatica', noInput: 'Aggiungi una frase o almeno una nuova foto.' },
  ru: { title: 'Заполнить с ИИ', subtitle: 'Получите приватные подсказки по фото или короткой фразе. Вы сами выбираете, что применить.', placeholder: 'Например: Nissan Versa 2022, б/у...', analyze: 'Предложить данные', analyzing: 'Анализирую...', unavailable: 'Подсказки сейчас недоступны. Можно продолжить вручную.', apply: 'Применить', category: 'Категория', subcategory: 'Подкатегория', titleField: 'Заголовок', description: 'Описание', attributes: 'Характеристики', confidence: 'уверенность', privacy: 'Приватная обработка · ничего не публикуется и не меняется автоматически', noInput: 'Добавьте короткую фразу или хотя бы одно новое фото.' },
  zh: { title: '使用 AI 填写', subtitle: '根据照片或简短描述获取私密建议，由你决定应用哪些内容。', placeholder: '例如：二手 Nissan Versa 2022...', analyze: '生成建议', analyzing: '分析中...', unavailable: '建议暂不可用，你可以手动继续。', apply: '应用', category: '分类', subcategory: '子分类', titleField: '标题', description: '描述', attributes: '属性', confidence: '置信度', privacy: '私密处理 · 不会自动发布或修改字段', noInput: '请输入简短描述或添加至少一张新照片。' },
  ja: { title: 'AIで入力', subtitle: '写真や短い説明から非公開で候補を作成します。適用する項目は自分で選べます。', placeholder: '例：2022 Nissan Versa 中古...', analyze: '候補を作成', analyzing: '解析中...', unavailable: '候補を利用できません。手動で続行できます。', apply: '適用', category: 'カテゴリ', subcategory: 'サブカテゴリ', titleField: 'タイトル', description: '説明', attributes: '属性', confidence: '信頼度', privacy: '非公開処理 · 自動公開・自動変更はしません', noInput: '短い説明または新しい写真を1枚以上追加してください。' },
  ko: { title: 'AI로 채우기', subtitle: '사진이나 짧은 설명으로 비공개 제안을 받습니다. 적용할 항목은 직접 선택합니다.', placeholder: '예: 중고 Nissan Versa 2022...', analyze: '정보 제안', analyzing: '분석 중...', unavailable: '제안을 사용할 수 없습니다. 수동으로 계속할 수 있습니다.', apply: '적용', category: '카테고리', subcategory: '하위 카테고리', titleField: '제목', description: '설명', attributes: '속성', confidence: '신뢰도', privacy: '비공개 처리 · 자동 게시 또는 자동 변경 없음', noInput: '짧은 설명이나 새 사진을 하나 이상 추가하세요.' },
  ar: { title: 'التعبئة بالذكاء الاصطناعي', subtitle: 'احصل على اقتراحات خاصة من صورة أو وصف قصير. أنت تختار ما يتم تطبيقه.', placeholder: 'مثال: Nissan Versa 2022 مستعملة...', analyze: 'اقتراح البيانات', analyzing: 'جارٍ التحليل...', unavailable: 'الاقتراحات غير متاحة الآن. يمكنك المتابعة يدويًا.', apply: 'تطبيق', category: 'الفئة', subcategory: 'الفئة الفرعية', titleField: 'العنوان', description: 'الوصف', attributes: 'الخصائص', confidence: 'الثقة', privacy: 'معالجة خاصة · لا نشر أو تعديل تلقائي', noInput: 'أضف وصفًا قصيرًا أو صورة جديدة واحدة على الأقل.' },
};

export function getListingAutofillCopy(lang) {
  return listingAutofillCopy[lang] || listingAutofillCopy.es;
}
