#!/usr/bin/env bash
#
# Warm and verify the public Mercasto XML sitemaps.
#
# Context: the 03:00 cron entry in /var/spool/cron/crontabs/root pointed at this path, but the
# script was missing from the repository, so the job failed with "not found" 93 nights in a row
# while /sitemap-ads.xml served an empty <urlset> to Google. The sitemaps themselves are
# generated by Laravel (backend/app/Http/Controllers/Api/SitemapController.php) and served
# dynamically, so this job fetches them (warming the 30 minute cache) and fails loudly when a
# sitemap that should list inventory comes back empty or broken.
#
# Read-only: it only issues GET requests. It never writes to the database and never writes
# sitemap artifacts to disk.
#
# Usage:
#   scripts/update-sitemaps.sh
#   MERCASTO_SITEMAP_BASE_URL=http://127.0.0.1 scripts/update-sitemaps.sh
#
set -euo pipefail

BASE_URL="${MERCASTO_SITEMAP_BASE_URL:-https://mercasto.com}"
CURL_TIMEOUT="${MERCASTO_SITEMAP_CURL_TIMEOUT:-30}"
UA='Mozilla/5.0 (compatible; MercastoSitemapJob/1.0)'
TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/mercasto-sitemaps.XXXXXX")"
trap 'rm -rf "$TMP_DIR"' EXIT

# Sitemaps that are legitimately allowed to be empty (no dedicated landing routes yet).
EMPTY_ALLOWED_REGEX='sitemap-states\.xml$'

failures=0
warnings=0

log() { printf '[%s] %s\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')" "$*"; }

fetch() {
  local url="$1" output="$2" code
  code="$(curl -sS -A "$UA" --connect-timeout 10 --max-time "$CURL_TIMEOUT" \
    -D "$output.headers" -o "$output" -w '%{http_code}' "$url" || true)"
  [[ -n "$code" ]] || code="000"
  printf '%s' "$code"
}

header_value() {
  local headers="$1" name="$2"
  awk -v wanted="$name" 'BEGIN{IGNORECASE=1} index(tolower($0), tolower(wanted)":")==1 {sub(/^[^:]*:[ ]*/,""); gsub(/\r/,""); print; exit}' "$headers"
}

loc_count() {
  # grep exits 1 when a sitemap is empty: that is exactly the case we must report, not abort on.
  { grep -o '<loc>' "$1" 2>/dev/null || true; } | wc -l | tr -d ' '
}

log "Starting sitemap warm/verify for ${BASE_URL}"

index_status="$(fetch "${BASE_URL}/sitemap.xml" "$TMP_DIR/index.xml")"
if [[ "$index_status" != "200" ]]; then
  log "FAIL sitemap.xml -> HTTP ${index_status}"
  exit 1
fi

if ! grep -Eq '<sitemapindex|<urlset' "$TMP_DIR/index.xml"; then
  log "FAIL sitemap.xml is not a sitemap document"
  exit 1
fi

# Collect the sitemaps advertised by the index, falling back to the canonical set.
mapfile -t sitemap_urls < <(grep -o '<loc>[^<]*</loc>' "$TMP_DIR/index.xml" | sed -e 's#</\?loc>##g')
if [[ "${#sitemap_urls[@]}" -eq 0 ]]; then
  sitemap_urls=(
    "${BASE_URL}/sitemap-main.xml"
    "${BASE_URL}/sitemap-categories.xml"
    "${BASE_URL}/sitemap-ads.xml"
  )
fi

for url in "${sitemap_urls[@]}"; do
  name="$(basename "$url")"
  target="$TMP_DIR/$name"
  status="$(fetch "$url" "$target")"
  locs="$(loc_count "$target")"
  health="$(header_value "$target.headers" 'X-Mercasto-Sitemap-Health')"

  if [[ "$status" == "503" ]]; then
    log "FAIL ${name} -> HTTP 503 (generator health: ${health:-unknown}). Real listings exist but none is indexable; check the ads sitemap generator logs."
    failures=$((failures + 1))
    continue
  fi

  if [[ "$status" != "200" ]]; then
    log "FAIL ${name} -> HTTP ${status}"
    failures=$((failures + 1))
    continue
  fi

  if ! grep -Eq '<urlset|<sitemapindex' "$target"; then
    log "FAIL ${name} is not a sitemap document"
    failures=$((failures + 1))
    continue
  fi

  log "OK   ${name} -> HTTP 200, ${locs} <loc> entries, health=${health:-n/a}"

  if [[ "$locs" -eq 0 ]] && ! grep -Eq "$EMPTY_ALLOWED_REGEX" <<<"$url"; then
    log "WARN ${name} advertises zero URLs (health=${health:-unknown}). If listings exist, the ads sitemap generator is not publishing them."
    warnings=$((warnings + 1))
  fi
done

if [[ "$failures" -gt 0 ]]; then
  log "Sitemap verification FAILED (${failures} failing, ${warnings} warning(s))"
  exit 1
fi

log "Sitemap verification completed (${#sitemap_urls[@]} sitemaps, ${warnings} warning(s))"
