import fs from 'fs';
import path from 'path';

const cleanedPath = path.resolve('./scratch/cleaned_translations.json');
const cleaned = JSON.parse(fs.readFileSync(cleanedPath, 'utf8'));

const extraKeys = {
  es: {
    change_photo: 'Cambiar foto',
    member_since: 'Miembro desde',
    fullname_placeholder: 'Nombre completo',
    bio_placeholder: 'Biografía',
    phone_verification: 'Verificación de teléfono',
    phone_verify_desc: 'Verifica tu teléfono para ganar confianza con los compradores. Recibirás un código SMS.',
    send_code: 'Enviar código',
    verify: 'Verificar',
    notif_email_desc: 'Correo cuando alguien pregunte por mi anuncio',
    delete_account_confirm: '¿Eliminar tu cuenta?',
    delete_account_warn: 'Esta acción es irreversible. Escribe ELIMINAR para confirmar.',
    email_verification_sent: 'Email de verificación enviado.',
    email_verification_failed: 'No se pudo enviar el email.',
    passwords_mismatch: 'Las contraseñas no coinciden',
    password_length_error: 'La contraseña debe tener al menos 8 caracteres',
    otp_code_sent: 'Código enviado. Revisa tu teléfono.',
    otp_code_error: 'Error al enviar el código',
    otp_length_error: 'El código debe tener 6 dígitos',
    otp_invalid: 'Código incorrecto',
    profile_saved: 'Perfil guardado correctamente',
    photo_uploaded: 'Foto actualizada',
    photo_upload_failed: 'Error al subir la foto',
    network_error: 'Error de red',
    delete_account_error: 'Error al eliminar la cuenta',
    no_ads_yet: 'No tienes anuncios',
    no_favorites_yet: 'No tienes favoritos',
    free_plan: 'Plan Gratis'
  },
  en: {
    change_photo: 'Change photo',
    member_since: 'Member since',
    fullname_placeholder: 'Full name',
    bio_placeholder: 'Biography',
    phone_verification: 'Phone verification',
    phone_verify_desc: 'Verify your phone to gain trust with buyers. You will receive an SMS code.',
    send_code: 'Send code',
    verify: 'Verify',
    notif_email_desc: 'Email when someone asks about my ad',
    delete_account_confirm: 'Delete your account?',
    delete_account_warn: 'This action is irreversible. Type DELETE to confirm.',
    email_verification_sent: 'Verification email sent.',
    email_verification_failed: 'Failed to send email.',
    passwords_mismatch: 'Passwords do not match',
    password_length_error: 'Password must be at least 8 characters long',
    otp_code_sent: 'Code sent. Check your phone.',
    otp_code_error: 'Error sending code',
    otp_length_error: 'Code must be 6 digits',
    otp_invalid: 'Invalid code',
    profile_saved: 'Profile saved successfully',
    photo_uploaded: 'Photo updated',
    photo_upload_failed: 'Failed to upload photo',
    network_error: 'Network error',
    delete_account_error: 'Error deleting account',
    no_ads_yet: 'You have no ads',
    no_favorites_yet: 'You have no favorites',
    free_plan: 'Free Plan'
  },
  pt: {
    change_photo: 'Alterar foto',
    member_since: 'Membro desde',
    fullname_placeholder: 'Nome completo',
    bio_placeholder: 'Biografia',
    phone_verification: 'Verificação de telefone',
    phone_verify_desc: 'Verifique seu telefone para ganhar a confiança dos compradores. Você receberá um código SMS.',
    send_code: 'Enviar código',
    verify: 'Verificar',
    notif_email_desc: 'E-mail quando alguém perguntar sobre o meu anúncio',
    delete_account_confirm: 'Excluir sua conta?',
    delete_account_warn: 'Esta ação é irreversível. Digite EXCLUIR para confirmar.',
    email_verification_sent: 'E-mail de verificação enviado.',
    email_verification_failed: 'Falha ao enviar e-mail.',
    passwords_mismatch: 'As senhas não coincidem',
    password_length_error: 'A senha deve ter pelo menos 8 caracteres',
    otp_code_sent: 'Código enviado. Verifique seu telefone.',
    otp_code_error: 'Erro ao enviar código',
    otp_length_error: 'O código deve ter 6 dígitos',
    otp_invalid: 'Código incorreto',
    profile_saved: 'Perfil salvo com sucesso',
    photo_uploaded: 'Foto atualizada',
    photo_upload_failed: 'Falha ao enviar foto',
    network_error: 'Erro de rede',
    delete_account_error: 'Erro ao excluir conta',
    no_ads_yet: 'Você não tem anúncios',
    no_favorites_yet: 'Você não tem favoritos',
    free_plan: 'Plano Grátis'
  },
  ru: {
    change_photo: 'Изменить фото',
    member_since: 'В сети с',
    fullname_placeholder: 'Полное имя',
    bio_placeholder: 'О себе',
    phone_verification: 'Подтверждение телефона',
    phone_verify_desc: 'Подтвердите телефон, чтобы вызвать доверие у покупателей. Вы получите SMS-код.',
    send_code: 'Отправить код',
    verify: 'Подтвердить',
    notif_email_desc: 'Уведомлять на почту, когда кто-то отвечает на мое объявление',
    delete_account_confirm: 'Удалить аккаунт?',
    delete_account_warn: 'Это действие необратимо. Напишите УДАЛИТЬ для подтверждения.',
    email_verification_sent: 'Письмо с подтверждением отправлено.',
    email_verification_failed: 'Не удалось отправить письмо.',
    passwords_mismatch: 'Пароли не совпадают',
    password_length_error: 'Пароль должен состоять минимум из 8 символов',
    otp_code_sent: 'Код отправлен. Проверьте телефон.',
    otp_code_error: 'Ошибка при отправке кода',
    otp_length_error: 'Код должен состоять из 6 цифр',
    otp_invalid: 'Неверный код',
    profile_saved: 'Профиль успешно сохранен',
    photo_uploaded: 'Фото обновлено',
    photo_upload_failed: 'Не удалось загрузить фото',
    network_error: 'Ошибка сети',
    delete_account_error: 'Ошибка при удалении аккаунта',
    no_ads_yet: 'У вас нет объявлений',
    no_favorites_yet: 'У вас нет избранного',
    free_plan: 'Бесплатный тариф'
  },
  zh: {
    change_photo: '修改头像',
    member_since: '注册时间',
    fullname_placeholder: '全名',
    bio_placeholder: '个人简介',
    phone_verification: '电话验证',
    phone_verify_desc: '验证您的电话以赢得买家的信任。您将收到一条短信验证码。',
    send_code: '发送验证码',
    verify: '验证',
    notif_email_desc: '当有人询问我的广告时向我发送电子邮件',
    delete_account_confirm: '删除您的账户？',
    delete_account_warn: '此操作不可逆。输入“删除”以确认。',
    email_verification_sent: '验证邮件已发送。',
    email_verification_failed: '无法发送邮件。',
    passwords_mismatch: '密码不匹配',
    password_length_error: '密码长度必须至少为 8 个字符',
    otp_code_sent: '验证码已发送。请检查您的手机。',
    otp_code_error: '发送验证码时出错',
    otp_length_error: '验证码必须是 6 位数字',
    otp_invalid: '验证码错误',
    profile_saved: '个人资料保存成功',
    photo_uploaded: '头像已更新',
    photo_upload_failed: '上传头像失败',
    network_error: '网络错误',
    delete_account_error: '删除账户时出错',
    no_ads_yet: '您还没有广告',
    no_favorites_yet: '您还没有收藏',
    free_plan: '免费计划'
  },
  ko: {
    change_photo: '프로필 사진 변경',
    member_since: '가입일',
    fullname_placeholder: '이름',
    bio_placeholder: '소개',
    phone_verification: '전화번호 인증',
    phone_verify_desc: '구매자에게 신뢰를 얻기 위해 전화번호를 인증하세요. SMS 코드가 전송됩니다.',
    send_code: '인증번호 전송',
    verify: '인증하기',
    notif_email_desc: '내 광고에 문의가 올 때 이메일 알림 받기',
    delete_account_confirm: '계정을 삭제하시겠습니까?',
    delete_account_warn: '이 작업은 취소할 수 없습니다. 확인을 위해 ELIMINAR를 입력하세요.',
    email_verification_sent: '인증 이메일이 전송되었습니다.',
    email_verification_failed: '이메일 전송에 실패했습니다.',
    passwords_mismatch: '비밀번호가 일치하지 않습니다',
    password_length_error: '비밀번호는 최소 8자 이상이어야 합니다',
    otp_code_sent: '인증번호가 전송되었습니다. 휴대전화를 확인하세요.',
    otp_code_error: '인증번호 전송 오류',
    otp_length_error: '인증번호는 6자리여야 합니다',
    otp_invalid: '잘못된 인증번호',
    profile_saved: '프로필이 성공적으로 저장되었습니다',
    photo_uploaded: '프로필 사진이 업데이트되었습니다',
    photo_upload_failed: '프로필 사진 업로드 실패',
    network_error: '네트워크 오류',
    delete_account_error: '계정 삭제 오류',
    no_ads_yet: '등록한 광고가 없습니다',
    no_favorites_yet: '관심 목록이 비어 있습니다',
    free_plan: '무료 요금제'
  },
  de: {
    change_photo: 'Foto ändern',
    member_since: 'Mitglied seit',
    fullname_placeholder: 'Vollständiger Name',
    bio_placeholder: 'Biografie',
    phone_verification: 'Telefonverifizierung',
    phone_verify_desc: 'Verifizieren Sie Ihre Telefonnummer, um das Vertrauen der Käufer zu gewinnen. Sie erhalten einen SMS-Code.',
    send_code: 'Code senden',
    verify: 'Verifizieren',
    notif_email_desc: 'E-Mail senden, wenn jemand nach meiner Anzeige fragt',
    delete_account_confirm: 'Konto löschen?',
    delete_account_warn: 'Diese Aktion ist unumkehrbar. Schreiben Sie ELIMINAR zur Bestätigung.',
    email_verification_sent: 'Verifizierungs-E-Mail gesendet.',
    email_verification_failed: 'E-Mail konnte nicht gesendet werden.',
    passwords_mismatch: 'Passwörter stimmen nicht überein',
    password_length_error: 'Das Passwort muss mindestens 8 Zeichen lang sein',
    otp_code_sent: 'Code gesendet. Überprüfen Sie Ihr Telefon.',
    otp_code_error: 'Fehler beim Senden des Codes',
    otp_length_error: 'Der Code muss 6-stellig sein',
    otp_invalid: 'Ungültiger Code',
    profile_saved: 'Profil erfolgreich gespeichert',
    photo_uploaded: 'Foto aktualisiert',
    photo_upload_failed: 'Fehler beim Hochladen des Fotos',
    network_error: 'Netzwerkfehler',
    delete_account_error: 'Fehler beim Löschen des Kontos',
    no_ads_yet: 'Sie haben keine Anzeigen',
    no_favorites_yet: 'Sie haben keine Favoriten',
    free_plan: 'Kostenloser Plan'
  },
  it: {
    change_photo: 'Cambia foto',
    member_since: 'Membro dal',
    fullname_placeholder: 'Nome completo',
    bio_placeholder: 'Biografia',
    phone_verification: 'Verifica del telefono',
    phone_verify_desc: 'Verifica il tuo telefono per guadagnare la fiducia degli acquirenti. Riceverai un codice SMS.',
    send_code: 'Invia codice',
    verify: 'Verifica',
    notif_email_desc: 'E-mail quando qualcuno chiede informazioni sul mio annuncio',
    delete_account_confirm: 'Eliminare l\'account?',
    delete_account_warn: 'Questa azione è irreversibile. Scrivi ELIMINAR per confermare.',
    email_verification_sent: 'E-mail di verifica inviata.',
    email_verification_failed: 'Impossibile inviare l\'e-mail.',
    passwords_mismatch: 'Le password non corrispondono',
    password_length_error: 'La password deve contenere almeno 8 caratteri',
    otp_code_sent: 'Codice inviato. Controlla il tuo telefono.',
    otp_code_error: 'Errore durante l\'invio del codice',
    otp_length_error: 'Il codice deve essere di 6 cifre',
    otp_invalid: 'Codice errato',
    profile_saved: 'Profilo salvato correttamente',
    photo_uploaded: 'Foto aggiornata',
    photo_upload_failed: 'Impossibile caricare la foto',
    network_error: 'Errore di rete',
    delete_account_error: 'Errore durante l\'eliminazione dell\'account',
    no_ads_yet: 'Non hai annunci',
    no_favorites_yet: 'Non hai preferiti',
    free_plan: 'Piano Gratuito'
  },
  ar: {
    change_photo: 'تغيير الصورة',
    member_since: 'عضو منذ',
    fullname_placeholder: 'الاسم الكامل',
    bio_placeholder: 'السيرة الذاتية',
    phone_verification: 'توثيق الهاتف',
    phone_verify_desc: 'وثّق هاتفك لزيادة ثقة المشترين. ستتلقى رمز SMS.',
    send_code: 'إرسال الرمز',
    verify: 'توثيق',
    notif_email_desc: 'إرسال بريد إلكتروني عندما يستفسر شخص ما عن إعلاني',
    delete_account_confirm: 'هل ترغب في حذف حسابك؟',
    delete_account_warn: 'هذا الإجراء غير قابل للتراجع. اكتب ELIMINAR للتأكيد.',
    email_verification_sent: 'تم إرسال بريد التحقق.',
    email_verification_failed: 'فشل إرسال البريد الإلكتروني.',
    passwords_mismatch: 'كلمات المرور غير متطابقة',
    password_length_error: 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
    otp_code_sent: 'تم إرسال الرمز. تحقق من هاتفك.',
    otp_code_error: 'خطأ في إرسال الرمز',
    otp_length_error: 'يجب أن يتكون الرمز من 6 أرقام',
    otp_invalid: 'الرمز غير صحيح',
    profile_saved: 'تم حفظ الملف الشخصي بنجاح',
    photo_uploaded: 'تم تحديث الصورة',
    photo_upload_failed: 'فشل رفع الصورة',
    network_error: 'خطأ في الشبكة',
    delete_account_error: 'خطأ في حذف الحساب',
    no_ads_yet: 'ليس لديك إعلانات',
    no_favorites_yet: 'ليس لديك تفضيلات',
    free_plan: 'خطة مجانية'
  },
  he: {
    change_photo: 'שנה תמונה',
    member_since: 'חבר מאז',
    fullname_placeholder: 'שם מלא',
    bio_placeholder: 'ביוגרפיה',
    phone_verification: 'אימות טלפון',
    phone_verify_desc: 'אמת את הטלפון שלך כדי לזכות באמון הקונים. תקבל קוד SMS.',
    send_code: 'שלח קוד',
    verify: 'אמת',
    notif_email_desc: 'שלח אימייל כשמישהו שואל על המודעה שלי',
    delete_account_confirm: 'למחוק את החשבון שלך?',
    delete_account_warn: 'פעולה זו אינה הפיכה. כתוב ELIMINAR כדי לאשר.',
    email_verification_sent: 'אימייל אימות נשלח.',
    email_verification_failed: 'שליחת האימייל נכשלה.',
    passwords_mismatch: 'הסיסמאות אינן תואמות',
    password_length_error: 'הסיסמה חייבת להכיל לפחות 8 תווים',
    otp_code_sent: 'קוד נשלח. בדוק את הטלפון שלך.',
    otp_code_error: 'שגיאה בשליחת הקוד',
    otp_length_error: 'הקוד חייב להכיל 6 ספרות',
    otp_invalid: 'קוד שגוי',
    profile_saved: 'הפרופיל נשמר בהצלחה',
    photo_uploaded: 'התמונה עודכנה',
    photo_upload_failed: 'העלאת התמונה נכשלה',
    network_error: 'שגיאת רשת',
    delete_account_error: 'שגיאה במחיקת החساب',
    no_ads_yet: 'אין לך מודעות',
    no_favorites_yet: 'אין לך מועדפים',
    free_plan: 'תוכנית חינמית'
  },
  yi: {
    change_photo: 'טוישן פאָטאָ',
    member_since: 'מיטגליד זינט',
    fullname_placeholder: 'פולער נאמען',
    bio_placeholder: 'ביאגראפיע',
    phone_verification: 'טעלעפאָן באַשטעטיקונג',
    phone_verify_desc: 'באַשטעטיקן דיין טעלעפאָן צו געווינען צוטרוי מיט בויערס. איר וועט באַקומען אַן SMS קאָד.',
    send_code: 'שיקן קאָד',
    verify: 'באַשטעטיקן',
    notif_email_desc: 'בליצפּאָסט ווען עמעצער פרעגט וועגן מיין מודעה',
    delete_account_confirm: 'ויסמעקן דיין חשבון?',
    delete_account_warn: 'דעם קאַמף איז ירעוואערסיבלע. טיפּ ELIMINAR צו באַשטעטיקן.',
    email_verification_sent: 'באַשטעטיקונג בליצפּאָסט געשיקט.',
    email_verification_failed: 'ניט געקענט שיקן בליצפּאָסט.',
    passwords_mismatch: 'פּאַסווערדז שטימען נישט',
    password_length_error: 'פּאַסוואָרד מוזן זיין בייַ מינדסטער 8 אותיות לאַנג',
    otp_code_sent: 'קאָד געשיקט. קוק דיין טעלעפאָן.',
    otp_code_error: 'טעות ביים שיקן קאָד',
    otp_length_error: 'קאָד מוזן זיין 6 דידזשאַץ',
    otp_invalid: 'פאַalsש קאָד',
    profile_saved: 'פּראָפיל הצלחה געראטעוועט',
    photo_uploaded: 'פאָטאָ דערהייַנטיקט',
    photo_upload_failed: 'פאָטאָ ופּלאָאַד דורכפאַל',
    network_error: 'נעץ טעות',
    delete_account_error: 'טעות ביים ויסמעקן חשבון',
    no_ads_yet: 'איר האָט קיין מודעות',
    no_favorites_yet: 'איר האָט קיין ফেבוריטס',
    free_plan: 'פריי פּלאַן'
  },
  ja: {
    change_photo: '写真を変更',
    member_since: 'メンバー登録日',
    fullname_placeholder: 'フルネーム',
    bio_placeholder: '自己紹介',
    phone_verification: '電話番号の確認',
    phone_verify_desc: 'バイヤーとの信頼を築くために電話番号を確認してください。SMSコードが送信されます。',
    send_code: 'コードを送信',
    verify: '確認する',
    notif_email_desc: '広告について問い合わせがあった場合にメールで通知する',
    delete_account_confirm: 'アカウントを削除しますか？',
    delete_account_warn: 'この操作は取り消せません。確認のためにELIMINARと入力してください。',
    email_verification_sent: '確認メールを送信しました。',
    email_verification_failed: 'メールの送信に失敗しました。',
    passwords_mismatch: 'パスワードが一致しません',
    password_length_error: 'パスワードは8文字以上である必要があります',
    otp_code_sent: 'コードを送信しました。携帯電話を確認してください。',
    otp_code_error: 'コード送信エラー',
    otp_length_error: 'コードは6桁である必要があります',
    otp_invalid: '無効なコード',
    profile_saved: 'プロフィールが正常に保存されました',
    photo_uploaded: '写真が更新されました',
    photo_upload_failed: '写真のアップロードに失敗しました',
    network_error: 'ネットワークエラー',
    delete_account_error: 'アカウント削除エラー',
    no_ads_yet: '広告がありません',
    no_favorites_yet: 'お気に入りはありません',
    free_plan: '無料プラン'
  },
  fr: {
    change_photo: 'Modifier la photo',
    member_since: 'Membre depuis',
    fullname_placeholder: 'Nom complet',
    bio_placeholder: 'Biographie',
    phone_verification: 'Vérification du téléphone',
    phone_verify_desc: 'Vérifiez votre téléphone pour gagner la confiance des acheteurs. Vous recevrez un code SMS.',
    send_code: 'Envoyer le code',
    verify: 'Vérifier',
    notif_email_desc: 'E-mail lorsque quelqu\'un demande des informations sur mon annonce',
    delete_account_confirm: 'Supprimer votre compte ?',
    delete_account_warn: 'Cette action est irréversible. Écrivez ELIMINAR pour confirmer.',
    email_verification_sent: 'E-mail de vérification envoyé.',
    email_verification_failed: "Impossible d'envoyer l'e-mail.",
    passwords_mismatch: 'Les mots de passe ne correspondent pas',
    password_length_error: 'Le mot de passe doit comporter au moins 8 caractères',
    otp_code_sent: 'Code envoyé. Vérifiez votre téléphone.',
    otp_code_error: "Erreur lors de l'envoi du code",
    otp_length_error: 'Le code doit comporter 6 chiffres',
    otp_invalid: 'Code incorrect',
    profile_saved: 'Profil enregistré avec succès',
    photo_uploaded: 'Photo mise à jour',
    photo_upload_failed: 'Échec du téléchargement de la photo',
    network_error: 'Erreur réseau',
    delete_account_error: 'Erreur lors de la suppression du compte',
    no_ads_yet: "Vous n'avez pas d'annonces",
    no_favorites_yet: "Vous n'avez pas de favoris",
    free_plan: 'Plan Gratuit'
  }
};

for (const [lang, keys] of Object.entries(extraKeys)) {
  if (cleaned[lang]) {
    Object.assign(cleaned[lang], keys);
  }
}

fs.writeFileSync(cleanedPath, JSON.stringify(cleaned, null, 2), 'utf8');
console.log("Updated cleaned_translations.json with profile and toast translations!");
